- src/components/tables/DepartureTable.jsx
- src/containers/adminPage/AdminPage.jsx
- src/containers/departureBoard/DepartureBoard.jsx
- src/utils.js
> Remove stops

- src/components/departureTiles/departureTile.jsx
- src/components/departureTiles/departureTiles.css
> Show max three departures times for each route

- src/assets/icons/settings.js
- src/components/header/Header.jsx
- src/components/header/styles.css
- src/containers/departureBoard/DepartureBoard.jsx
- src/containers/departureBoard/styles.scss
> Move settings button

- src/components/departureTiles/DepartureTile.jsx
- src/components/departureTiles/styles.scss
- src/components/header/Header.jsx
- src/components/header/styles.css
- src/containers/adminPage/SelectionPanel.jsx
- src/containers/adminPage/styles.scss
- src/containers/departureBoard/DepartureBoard.jsx
- src/containers/departureBoard/styles.scss
- src/containers/landingPage/styles.scss
- src/utils.js
- Move settingsbutton to header
- Add scrollbar to selection panel in Admin
- Fix icon size in tile header
- Div styling on admin page
> Dk 1867- Bug fixing

- src/containers/departureBoard/DepartureBoard.jsx
Datagrunnlaget retferdiggjør ikke oppdaterering oftere enn hvert 30 sec. Endret pull interval
> Endret refresh interval til 30sec 

- package-lock.json
- package.json
- src/containers/adminPage/AdminPage.jsx
- src/containers/adminPage/searchPanels/SelectionPanelSearch.jsx
- src/containers/departureBoard/DepartureBoard.jsx
- src/utils.js
* Update SDK
* Add `layers=venue` to geocoder query to get stop places only, not addresses and other things.
> Venues only in stop place search

- package-lock.json
- package.json
- src/containers/adminPage/searchPanels/SelectionPanelSearch.jsx
The coordinates-based approach didn't work anymore. Should probably check the SDK `getStopPlacesByPosition` method. Anyways, fetching by ID is better.
> Fix admin search field

- src/containers/App.jsx
- src/containers/adminPage/AdminPage.jsx
- src/containers/departureBoard/DepartureBoard.jsx
- src/containers/landingPage/LandingPage.jsx
- src/containers/landingPage/styles.scss
- src/containers/privacy/Privacy.jsx
- src/containers/privacy/styles.scss
- src/routes.jsx
> Privacy page

- .gitignore
- src/containers/App.jsx
- src/containers/landingPage/LandingPage.jsx
- src/containers/landingPage/styles.scss
> Move privacy link above picture

- src/components/departureTiles/styles.scss
- src/components/footer/styles.scss
- src/main.scss
> Reduce padding/margin for screens < 1200 px wide

- src/components/searchPanel/SearchPanel.jsx
- src/components/searchPanel/styles.scss
Make it part of a form and type=submit. 
Also use Button from component library.
Remove a bunch of unnecessary styles.
> Make button on front page actionable with enter button

- src/components/departureTiles/DepartureTiles.jsx
Makes sure order is consistent
Fixes #91
> Sort columns alphabetically

- package.json
- scripts/postinstall.js
- scripts/postinstall.sh
#103 
I rewrote the bash script to a Node.js script :)
> rewrite postinstall script

- src/components/departureTiles/styles.scss
- src/components/footer/styles.scss
- src/components/settingsButton/styles.scss
- src/containers/departureBoard/styles.scss
- src/main.scss
Removed pagescroll for low-res screens, fixed footer for low res and touch, centered setting-cog and added fit-content for FireFox
> Footer changes for low-res and touch, setting-cog fix, fit-content for ff

- src/components/searchPanel/SearchPanel.jsx
- src/containers/App.jsx
- src/containers/adminPage/AdminPage.jsx
- src/containers/adminPage/filterPanel/TransportRow.jsx
- src/containers/adminPage/searchPanels/BikePanelSearch.jsx
- src/containers/adminPage/searchPanels/SelectionPanelSearch.jsx
- src/containers/departureBoard/DepartureBoard.jsx
- src/containers/privacy/Privacy.jsx
Fixed #99 
This PR container two major changes
- Replaced lifecycle methods with hooks
- Replaced class components with functional components
Please review the code before merging as I was not able to run the app on my machine.
> Replaced class components with functional components + hooks

- src/assets/icons/github.tsx
- src/assets/icons/index.tsx
- src/containers/Admin/index.tsx
- src/containers/Admin/styles.scss
- src/dashboards/Entur/index.tsx
- src/dashboards/Entur/styles.scss
Fixes https://github.com/entur/tavla/issues/95
> #95: added github link on front page and on admin site

- package-lock.json
- package.json
- webpack.config.js
> Migrated webpack-serve to webpack-dev-server

- src/containers/Admin/ModePanel/ModePanelRow.tsx
- src/containers/Admin/ModePanel/index.tsx
- src/containers/Admin/index.tsx
- src/dashboards/Entur/DepartureTile/index.tsx
- src/utils.ts
Lager en egen oppgave på å fikse det adminsiden, da det nok krever større omskriving.
> Bruke subMode for å få riktig farge og ikon

- src/containers/Admin/StopPlacePanel/index.tsx
For å få riktig farge og ikon :)
> Send transportsubmode i stopPlacePanel på admin-sode

- package-lock.json
- package.json
- src/dashboards/Race/index.tsx
- src/dashboards/Race/styles.scss
> Ny visning: Tidslinja

- .browserslistrc
- package-lock.json
- package.json
- webpack.config.js
Allows using [browserslist](https://github.com/browserslist/browserslist) to control support for browsers, both JS and CSS. Will maybe help with #132.
> Add browserslist setup and postcss

- .browserslistrc
- package-lock.json
- package.json
- src/main.tsx
- webpack.config.js
Old screens don't support ES6: https://github.com/entur/tavla/issues/132 
This should help.
> Support all browsers versions since 2015

- src/constants.ts
🎚️ Increased the default value for max distance from `300` to `500`
> ETU-2678: Increased default max distance

- src/dashboards/Compact/styles.scss
- Der er et lite område under streken for størrelsejustering som ikke er en del av området man kan dra fra. Dette blir fikset her. 
- Området man kan dra fra har blitt gjort litt større.
> Resize handle fixes

- package-lock.json
- package.json
- src/auth.ts
- src/containers/Admin/BikePanel/index.tsx
- src/containers/Admin/BikeSearch/index.tsx
- src/containers/Admin/StopPlacePanel/index.tsx
- src/containers/Admin/index.tsx
- src/containers/DashboardWrapper/Footer/index.tsx
- src/containers/DashboardWrapper/index.tsx
- src/containers/LandingPage/SearchPanel/index.tsx
- src/containers/LandingPage/index.tsx
- src/dashboards/Chrono/DepartureTile/index.tsx
- src/dashboards/Compact/DepartureTile/index.tsx
- src/dashboards/Timeline/index.tsx
- src/firebase-init.ts
- src/hooks.ts
- src/logic/useBikeRentalStations.ts
- src/logic/useStopPlacesWithDepartures.ts
- src/main.tsx
- src/service.ts
- src/services/firebase.ts
- src/settings/index.ts
- src/utils.tsx
Den største endringa er at arrow functions med 1 parameter må også ha parentes rundt det.
> Upgrade Prettier to v2, fix errors

- src/containers/DashboardWrapper/BottomMenu/index.tsx
Her er det noen småendringer på menyen. Det ligger i staging for dem som vil teste, men jeg tenker også at vi bør kjøre det opp i prod ganske fort (akkurat nå forsvinner menyen selv når pekeren ligger over).
> Gjorde justeringer for tilgjengelighet i menyen

- src/containers/LandingPage/index.tsx
Added a created field to FIrestore docs. Might be used for sorting, filtering and statistics.
> Added created date to db doc

- src/containers/Admin/ThemeTab/index.tsx
Toggler av theming i legacy tavler
> :ambulance: Turning of themes in legacy url

- src/containers/Admin/styles.scss
Fikset adminpanelet så det står litt mer i stil med designet på Abstract og ikke skalerer på merkelig vis.
> Admin touchup

- src/components/RadioCard/styles.scss
- src/containers/Admin/EditTab/BikePanel/index.tsx
- src/containers/Admin/EditTab/BikePanel/styles.scss
- src/containers/Admin/LogoTab/Description/index.tsx
- src/containers/Admin/LogoTab/SizePicker/index.tsx
- src/containers/Admin/LogoTab/SizePicker/styles.scss
- src/containers/Admin/LogoTab/index.tsx
- src/containers/Admin/LogoTab/styles.scss
- src/containers/Admin/ThemeTab/index.tsx
- src/containers/Admin/ThemeTab/styles.scss
- src/containers/Privacy/index.tsx
- src/containers/Privacy/styles.scss
* Fjernet back-arrow fra privacy
* eds-paragraph drev med oversikriving av fargen. Nå fikset slik at de elementene som bruker eds-paragraph kun setter fargen lokalt, og ikke påvirker resten.
> Removed back-arrow privacy, and fixed all eds-paragraph colors

- src/components/Header/styles.scss
- src/containers/Admin/EditTab/StopPlacePanel/PanelRow/index.tsx
- src/containers/Admin/styles.scss
- src/dashboards/Chrono/styles.scss
- src/dashboards/Compact/styles.scss
Admin-panel ser bedre ut på mobil
Tavla ser bra ut på mobil =-)
> :iphone: Admin panel and tavla now looking good enough on phone

- src/components/LoginModal/Signup/index.tsx
Fikset noen bugs i signup:
1. Man kunne logge inn selv om passordene var ulike, ettersom dette ikke er en sjekk gjort av Firebase, og det ble ikke sjekket før etter man hadde sendt request til firebase.
2. Sjekker email mot regex.  Før kunne det kan oppstå en case hvor feilmeldingen forsvinner om at e-posten ikke er gyldig, når den fremdeles er ugyldig, eller at du ikke får en feilmelding om at e-posten er ugyldig når den faktisk er det.
> :bug: Fix bug with different passwords and check on valid email

- package-lock.json
- package.json
- src/containers/DashboardWrapper/BottomMenu/index.tsx
Del tavle knapp på meny! ✨ 
Når du klikker på knappen vil url være kopier til ditt clipboard, og en toaster som gir beskjed om dette komme opp.
> :sparkles: Del tavle

- src/components/LoginModal/Signup/index.tsx
- src/components/LoginModal/styles.scss
Må gjøre en sjekk på om man er valid for å logge inn uten å bruke state, ettersom state ikke reker å oppdatere seg raskt nok. Fikset også at slik at en tidligere link ble synlig igjen, etter å ha forsvunnet under theming.
> :bug: Fixing bug in sign up

- src/containers/Admin/ThemeTab/index.tsx
- src/containers/ThemeWrapper/ThemeProvider.tsx
- src/settings/index.ts
Fikser oppdatering av theming via settings og fjerner settings fra paths som ikke bruker det (dermed fjerner themes fra disse sidene).
> Fix themeContext updating from settings

- src/components/Clock/index.tsx
Bitteliten inconsistency i className i klokke-komponenten 😊
> Fix Clock class name

- src/components/Header/DefaultHeader.tsx
- src/components/RadioCard/index.tsx
- src/containers/Admin/DashboardPickerTab/index.tsx
- src/containers/DashboardWrapper/BottomMenu/MenuButton/index.tsx
- src/containers/DashboardWrapper/BottomMenu/index.tsx
- src/containers/Error/ErrorPages.tsx
- src/containers/MyBoards/BoardCard/OverflowMenu/Modals/DeleteTavleModal.tsx
- src/containers/MyBoards/BoardCard/OverflowMenu/Modals/RemoveLockModal.tsx
- src/containers/MyBoards/BoardCard/OverflowMenu/index.tsx
- src/containers/MyBoards/BoardCard/index.tsx
- src/containers/MyBoards/index.tsx
Avoid use of global event, fix some event types, remove some unnecessary preventDefaults
> TypeScript fixes for events

- src/containers/Admin/ThemeTab/index.tsx
> Use Norwegian theme names

- src/utils.tsx
> Fix import of Carferry icon

- src/components/Header/DefaultHeader.tsx
- src/components/LoginModal/EmailLogin/index.tsx
- src/components/LoginModal/EmailSent/index.tsx
- src/components/LoginModal/ResetPassword/index.tsx
- src/components/LoginModal/Signup/index.tsx
- src/containers/DashboardWrapper/BottomMenu/index.tsx
- src/containers/Error/ErrorPages.tsx
- src/containers/MyBoards/index.tsx
- src/services/firebase.ts
Removes this warning in the console:
> Avoid using dev build of firebase

- .stylelintrc
- package.json
- src/components/Header/styles.scss
- src/components/Slider/styles.scss
- src/containers/Admin/EditTab/BikePanel/styles.scss
- src/containers/Admin/EditTab/StopPlacePanel/styles.scss
- src/containers/Admin/EditTab/styles.scss
- src/containers/Admin/FloatingButtons/styles.scss
- src/containers/Admin/LogoTab/SizePicker/styles.scss
- src/containers/Admin/LogoTab/styles.scss
- src/containers/Admin/styles.scss
- src/containers/MineTavlerModal/styles.scss
Stylelint har ikkje fungert, for man må tydeligvis wrappe argumentet `src/**/*.scss` i quotes: `"src/**/*.scss"`.
> Fix stylelint script setup, fix detected errors

- src/assets/icons/ThemeDashboardPreview.ts
- src/components/LoginModal/Signup/index.tsx
- src/containers/DashboardWrapper/BottomMenu/index.tsx
- src/containers/Error/ErrorPages.tsx
- src/containers/MineTavlerModal/index.tsx
- src/dashboards/Compact/DepartureTile/index.tsx
- src/services/firebase.ts
- src/settings/UrlStorage.ts
- src/utils.tsx
Mange TypeScript-feil blir ikkje oppdaga, fordi `strict: true` manglar i configen. Det gjenstår ca. 50 feil etter denne PRen.
> Fix some TS errors if strict: true

- src/containers/Error/ErrorPages.tsx
> Use more friendly message if not logged in

- src/containers/LandingPage/SearchPanel/index.tsx
- src/containers/LandingPage/SearchPanel/styles.scss
> Use 'light' style for search bar although in Contrast section

- src/containers/LandingPage/SearchPanel/index.tsx
- src/containers/LandingPage/SearchPanel/styles.scss
På Tavla i dag er knappen disabled heilt til du har valgt plass. Me skal heller la knappen vere trykkbar, men vise ei melding når du ikkje har valgt plass. _Egentlig_ skal me fokusere søkefeltet og opne dropdownen, men det må endringar i designsystemet til for å få til det på ein god måte, så det får kome seinare.
> Don't disable button but display validation if place not selected

- src/dashboards/Compact/index.tsx
- src/dashboards/Compact/styles.scss
> Endrer farge på håndtaket til sparkesykkelkortet og fjerner fade nederst på kortet

- src/logic/useWalkTime.ts
.filter was run on promises, not the results from the promises.
> Fix crash in MapView if walkTime is null

- src/containers/LandingPage/index.tsx
- src/containers/LandingPage/styles.scss
> Move entur.no link to bottom of page

- src/dashboards/BusStop/DepartureTile/styles.scss
- src/dashboards/Chrono/components/Tile/styles.scss
- src/dashboards/Compact/components/Tile/styles.scss
> Add margin between header icons

- package-lock.json
- package.json
- src/containers/Navbar/index.tsx
- src/containers/Privacy/index.tsx
- types/assets.d.ts
... and update entur/icons to v1.17.0
> Change text and icon for privacy

- src/containers/Privacy/index.tsx
Added some text to the privacy site about Firebase Authentication
> Added Firebase Auth Privacy Text

- src/containers/Privacy/index.tsx
Added whitespace in Privacy section
> Added whitespace in Privacy section

- src/containers/Navbar/index.tsx
- src/containers/Navbar/styles.scss
... og sentrere teksten med ikonene
> Justere ikon-størrelse på forside

- .gitignore
- package-lock.json
- package.json
- src/dashboards/Compact/components/Tile/styles.scss
- src/dashboards/Compact/index.tsx
- src/dashboards/Compact/styles.scss
Cards now have a maximum number of columns, and makes the card size a bit larger and more easy to read.
(and longer station names get trailing dots instead of being cut of mid name)
Before:
After:
> Changed how the compact layout looks when creating a new Tavle

- src/dashboards/Chrono/MapTile/index.tsx
- src/dashboards/Chrono/MapTile/styles.scss
- src/dashboards/Chrono/components/TileRow/styles.scss
- src/dashboards/Chrono/index.tsx
- src/dashboards/Chrono/styles.scss
- src/dashboards/Compact/MapTile/styles.scss
- src/dashboards/Compact/index.tsx
Map is now also visible in chrono view.
> Map is now also in chrono view

- src/dashboards/BusStop/DepartureTile/index.tsx
- src/dashboards/BusStop/styles.scss
- src/dashboards/Map/index.tsx
- src/dashboards/Map/styles.scss
- src/dashboards/Timeline/styles.scss
Added margin to mobile views, changed the stop tiles in map view to not overflow in x-direction
> minor stylistic changes to other views

- src/dashboards/BusStop/DepartureTile/index.tsx
- src/dashboards/BusStop/DepartureTile/styles.scss
- src/dashboards/BusStop/MapTile/index.tsx
- src/dashboards/BusStop/MapTile/styles.scss
- src/dashboards/BusStop/index.tsx
- src/dashboards/BusStop/styles.scss
There is now a map in busstop-view. Made some necessary layout modifications for desktop and mobile. Modified view can be seen below.
> Map in busstop and default toggle off

- src/dashboards/Chrono/MapTile/styles.scss
- src/dashboards/Chrono/index.tsx
- src/dashboards/Compact/MapTile/styles.scss
- src/dashboards/Compact/index.tsx
Make tiles in both Compact and Chrono fit the height of content on all small screens.
> Mobile static layout

- src/dashboards/Chrono/MapTile/styles.scss
- src/dashboards/Chrono/styles.scss
- src/dashboards/Compact/MapTile/styles.scss
- src/dashboards/Compact/styles.scss
> Make mapTile and bikeTile visible on small screens

- src/components/ExclamationIcon/exclamation.tsx
- src/containers/Admin/EditTab/ToggleDetailsPanel/index.tsx
- src/containers/Admin/EditTab/ToggleDetailsPanel/styles.scss
- src/containers/Admin/EditTab/index.tsx
- src/dashboards/BusStop/DepartureTile/index.tsx
- src/dashboards/Chrono/DepartureTile/index.tsx
- src/dashboards/Chrono/components/TileRow/index.tsx
- src/dashboards/Compact/DepartureTile/index.tsx
- src/dashboards/Compact/components/TileRow/index.tsx
- src/settings/index.ts
- src/types.ts
- src/utils.tsx
Added toggle for turning on or off information on situations in chrono, compact and busstop view, and made showing situations default.
> Added toggle for situations 

- src/components/RearrangeModal/index.tsx
- src/components/RearrangeModal/styles.scss
- src/dashboards/Compact/index.tsx
- src/dashboards/Compact/styles.scss
Moved the Modal code from Compact view into a new component called RearrangeModal.
> moved compact view modal into its own component

- package-lock.json
- src/containers/Admin/EditTab/index.tsx
- src/containers/Admin/EditTab/styles.scss
- src/containers/Admin/index.tsx
- src/containers/Admin/styles.scss
Reduced the margins and made the admin panel layout better on mobile devices.
> made admin panel better on mobile devices

- src/dashboards/Chrono/index.tsx
- src/dashboards/Chrono/styles.scss
Removed fade on map in chrono view. Only the tiles have fade.
> Removed map fade in chrono view

- src/components/RearrangeModal/index.tsx
- src/dashboards/Chrono/index.tsx
- src/dashboards/Compact/index.tsx
Added same RearrangeModal found in Compact view to the Chrono view.
> implemented rearrangeable tiles in chrono view

- src/containers/Admin/EditTab/styles.scss
- src/containers/Admin/styles.scss
- src/dashboards/BusStop/styles.scss
- src/dashboards/Timeline/styles.scss
Margins are the same across all views on mobile devices
> Fixed margin to 1.5 rem across different views

- src/containers/Admin/DashboardPickerTab/styles.scss
- src/containers/Admin/EditTab/index.tsx
- src/containers/Admin/EditTab/styles.scss
- src/containers/Admin/ThemeTab/styles.scss
- src/containers/Admin/styles.scss
- src/containers/LandingPage/styles.scss
- src/containers/Navbar/styles.scss
- src/dashboards/BusStop/styles.scss
- src/dashboards/Chrono/styles.scss
- src/dashboards/Compact/styles.scss
- src/dashboards/Timeline/styles.scss
All margins are set to 16px/1rem. Landing page, admin page and different views all have the same margins.
> All pages now have equal margins 16px

- src/components/LoginModal/styles.scss
- src/components/RearrangeModal/styles.scss
- src/containers/LockModal/styles.scss
- src/containers/MineTavlerModal/styles.scss
- src/containers/MyBoards/BoardCard/OverflowMenu/Modals/styles.scss
- src/containers/MyBoards/BoardCard/styles.scss
- src/containers/MyBoards/styles.scss
Added 16px margins to "mine tavler" as well as to all the modals.
> Added margins to modal

- src/containers/Admin/EditTab/styles.scss
Changed font-weight of input field in admin panel.
> Changed font-weight

- src/components/SituationModal/index.tsx
- src/components/SituationModal/styles.scss
- src/dashboards/Chrono/components/TileRow/index.tsx
- src/dashboards/Chrono/styles.scss
- src/dashboards/Compact/components/TileRow/index.tsx
Situation modal on both compact and chrono on mobile. When clicking the situation icon on mobile devices, a modal will show with the situation message.
> Situation modal on both compact and chrono on mobile.

- src/dashboards/Compact/index.tsx
- src/dashboards/Compact/styles.scss
Async loading for the Compact view grid made the tile placements not so reliable, so this view is now displaying a loading indicator until the data has been retrieved.
> added loading indicator to compact view

- src/containers/Admin/EditTab/ToggleDetailsPanel/index.tsx
- src/dashboards/BusStop/DepartureTile/index.tsx
- src/dashboards/Chrono/DepartureTile/index.tsx
- src/dashboards/Compact/DepartureTile/index.tsx
- src/settings/index.ts
Walk information can be toggled in admin panel, and has been applied to all views.
> Walk info can be toggled and showed in every view

- src/containers/Admin/EditTab/index.tsx
- src/containers/Admin/EditTab/styles.scss
Better margins on tiles and headlines.
> fixed margins in admin panel

- src/containers/Admin/EditTab/ToggleDetailsPanel/styles.scss
- src/containers/Admin/EditTab/styles.scss
Margins are no longer ugly bugly on mobile
> fixed margins on admin mobile

- src/dashboards/Compact/BikeTile/index.tsx
- src/dashboards/Compact/components/Tile/styles.scss
- src/dashboards/Compact/components/TileRow/index.tsx
- src/dashboards/Compact/components/TileRow/styles.scss
- src/dashboards/Compact/index.tsx
- src/logic/useWalkInfoBike.ts
Walking distance in minutes and time is now visible in bike tile. Can be toggled.
> Walking distance on bike stations

- src/containers/Admin/styles.scss
- src/dashboards/BusStop/index.tsx
- src/dashboards/BusStop/styles.scss
- src/dashboards/Chrono/index.tsx
- src/dashboards/Chrono/styles.scss
- src/dashboards/Compact/index.tsx
- src/dashboards/Compact/styles.scss
Since the menu is locked on mobile devices, we have added a margin-bottom to every view.
> Margin bottom is nice on mobile

- src/dashboards/BusStop/index.tsx
- src/dashboards/BusStop/styles.scss
Improvements of busstop margin code.
> Busstop margin improvements

- src/containers/Admin/EditTab/index.tsx
- src/containers/Admin/EditTab/styles.scss
Some improvements have been made to the tooltip in the admin panel:
- Tooltip will not flicker upon hover or focus
- Design improvements
> Improvements to tooltip

- src/containers/Admin/EditTab/index.tsx
> changed boolean

- src/dashboards/BusStop/MapTile/styles.scss
- src/dashboards/Chrono/MapTile/styles.scss
- src/dashboards/Chrono/components/TileRow/styles.scss
- src/dashboards/Compact/MapTile/styles.scss
- src/dashboards/Compact/components/TileRow/styles.scss
Add parent (compact, chrono, busStop) in styles.scss, to aviod that files get mixed up in different views
> Add parent in styles files

- src/containers/styles.scss
- src/variables.scss
Updated PWA prompt to use the Nationale font.
Before:
After:
> updated font and text sizes on pwa prompt

- firebase.json
- src/containers/App.tsx
- src/index.html
- sw.js
- tsconfig.json
Hopefully this fixes the bugs which prevented the site from loading.
> Maybe a fix for blocking javascript to load the website?

- src/dashboards/Timeline/index.tsx
- src/dashboards/Timeline/styles.scss
> Display walk distance in Timeline with icon and line

- src/components/Header/DashboardHeader.tsx
- src/dashboards/Compact/MapTile/index.tsx
It is now possible to zoom in maps. After refresh, the zoom level is set back to its default value.
> Add zoom in map

- src/dashboards/BusStop/MapTile/index.tsx
- src/dashboards/Chrono/MapTile/index.tsx
- src/dashboards/Chrono/MapTile/styles.scss
- src/dashboards/Chrono/styles.scss
- src/dashboards/Compact/MapTile/index.tsx
- src/dashboards/Compact/MapTile/styles.scss
- src/dashboards/Compact/styles.scss
- src/dashboards/Map/index.tsx
Made it possible to zoom in map in all views
> Zoom in map in more views

- src/containers/Admin/EditTab/styles.scss
> Set left margin on header only on larger screens

- src/containers/Admin/EditTab/ToggleDetailsPanel/index.tsx
- src/containers/Admin/EditTab/ToggleDetailsPanel/styles.scss
- src/dashboards/BusStop/index.tsx
- src/dashboards/BusStop/styles.scss
Busstop tiles are no longer draggable, and the filter chips in "detaljer i visningen" rearranges more properly when downscaling the screen.
> fixed detaljer i visningen and draggable in busstop

- src/containers/Admin/EditTab/index.tsx
- src/containers/Admin/EditTab/styles.scss
- src/dashboards/BusStop/MapTile/styles.scss
- src/dashboards/BusStop/index.tsx
- src/dashboards/BusStop/styles.scss
Added border radius to the map shown in BusStop view.
> Border radius on BusStop's MapTile

- src/dashboards/BusStop/index.tsx
- src/dashboards/Chrono/index.tsx
- src/dashboards/Compact/index.tsx
- src/dashboards/Timeline/index.tsx
- src/dashboards/Timeline/styles.scss
Longpress implemented in timeline ✌🏼
> Longpress in timeline

- src/dashboards/BusStop/MapTile/styles.scss
- src/dashboards/BusStop/index.tsx
- src/dashboards/BusStop/styles.scss
Busstop-maptile now also has round corners on mobile devices.
> fixed round corners on map busstop mobile

- src/dashboards/BusStop/DepartureTile/index.tsx
Fikser denne feilen her:
Løst på samme måte som i chrono dashboard som del av PR #433.
> Refactor to avoid validateDomNesting warning

- src/dashboards/Compact/BikeTile/index.tsx
- src/logic/useWalkInfoBike.ts
Tar gjerne noe input på om dette er ønsket måte å gjøre clean-up på før jeg gjør det flere steder. Har lest meg litt rundt og sett at det står skrevet en del om AbortController (f. eks. [her)](https://dev.to/pallymore/clean-up-async-requests-in-useeffect-hooks-90h). Slik jeg skjønner det er AbortController bedre, men for vår del vil det kreve litt mer omskriving av koden. Tanker?
> Fikse state update på unmounted component

- firebase.json
- webpack.config.js
Jeg har ikke klart å finne ut hvorfor dette skal være nødvendig. Gjerne opplys meg om noen vet hvorfor.
> Tillate firebase å injecte en iframe for mobilenheter

- src/dashboards/Chrono/index.tsx
Tidligere ble den lagrede (localstorage) layouten på chronoview overskrevet ved refreshing slik at man ikke fikk tilbake layouten man hadde satt opp. Denne PR-en fikser det ved å implementere samme logikk som i compact view. Mesteparten av diffen er indentering pga loaderen som er lagt til. 
Flere av disse komponentene har over tid blitt relativt uhåndterbare i størrelse, logikk og navngiving, og denne PR-en gjør det ikke bedre. Tror vi vil være tjent med å ta en større jobb på å skrive om dette mtp tekninsk gjeld og hvor enkelt/vanskelig det vil være for nye å sette seg inn i prosjektet. Kanskje særlig hvis det er sommerstudenter som skal jobbe videre med det.
> Avoid overwriting locally stored layout on refresh for chrono view

- src/containers/Admin/EditTab/index.tsx
- src/containers/Admin/EditTab/styles.scss
> Readable tooltip for dark theme

- src/logic/useRealtimeVehicleData.ts
Kartet viste fortsatt dataen selv om det var skrudd av i innstillinger
> Skjule sanntidsdata vha innstillinger

- src/components/Map/index.tsx
- src/dashboards/BusStop/index.tsx
- src/dashboards/Chrono/index.tsx
- src/dashboards/Compact/index.tsx
- src/dashboards/Map/index.tsx
- src/dashboards/Timeline/index.tsx
- src/logic/useStopPlacesWithDepartures.ts
- src/types.ts
- src/utils.tsx
- fix crash by not passing undefined to renderTitle
- fix underlying issue where the list of departures could be empty
- also fixed some empty XML bodies and a useMemo returning void (warnings from Intellij IDEA)
> ETU-22647: fix crash on small screens

- .env.development
- .env.prod
- .env.staging
- CONTRIBUTING.md
- src/logic/useNearestPlaces.ts
- src/service.ts
Using Apollo Client to write a more specific query, and there is no SDK support for v3.
> Use JourneyPlanner v3 in useNearestPlaces

- src/containers/Admin/EditTab/index.tsx
- src/logic/getStopPlacesWithLines.ts
- src/logic/useStopPlacesWithLines.ts
- src/logic/useWalkInfo.ts
- src/service.ts
This converts the two queries from OTP 1 to 2 and also optimizes them by not requesting more than needed.
> Use JP v3 for getStopPlaceDeparturesWithLines and useWalkInfo

- src/dashboards/Chrono/index.tsx
- src/dashboards/Chrono/styles.scss
Ikke heelt heldig branch navn, men endte med å gjøre det her uansett 😇 Blir riktige handles OG fikk bekreftet at GPG signeringa funka 🙌
> Gives chrono-view tiles same resize handle as compact-view

- package-lock.json
Used `npm audit fix` to automatic update dependencies that did not required attention :)
> update dependencies using npm audit fix

- src/components/Map/index.tsx
- src/components/RearrangeModal/index.tsx
- src/components/WeatherTile/index.tsx
- src/containers/Admin/EditTab/ScooterPanel/index.tsx
- src/containers/Admin/EditTab/StopPlacePanel/index.tsx
- src/containers/Admin/EditTab/index.tsx
- src/containers/Admin/LogoTab/LogoUpload/index.tsx
- src/containers/LandingPage/SearchPanel/index.tsx
- src/dashboards/BusStop/index.tsx
- src/dashboards/Chrono/index.tsx
- src/dashboards/Compact/DepartureTile/index.tsx
- src/dashboards/Compact/index.tsx
- src/logic/useRealtimeVehicleReducer.ts
- src/logic/useStopPlacesWithLines.ts
- src/settings/index.ts
- src/utils.tsx
- tsconfig.json
- gives better safety checks for undefined values
> Activate noUncheckedIndexedAccess compile flag

- src/containers/MyBoards/index.tsx
- src/services/firebase.ts
Fix bug that resulted in crash if you had more than pending board invites
> Fix bug that resulted in crash if you had more than pending board i

- src/components/Header/DashboardHeader.tsx
- src/containers/App.tsx
* Destructure when using useSettings
> use-settings-destructuring

- src/dashboards/Poster/components/LastUpdated/LastUpdated.tsx
Made time display use Norwegian timezone and formatting explicitly
> Changed time display in Poster dash

- webpack.config.js
* Add cache config to webpack.config. Reduces startup time from 14s to 1.4s.
> webpack-cache

- src/dashboards/Poster/components/BusTile/BusTile.scss
- src/dashboards/Poster/components/BusTile/BusTile.tsx
Added check on the size of a bus route number making it possible to adjust font size in order to make the route number fit in the red box
> Styling - font size in bus line box in Poster view

- src/dashboards/Poster/Poster.scss
- src/dashboards/Poster/components/LastUpdated/LastUpdated.scss
Doubled the gap property value for poster variables
> Doubled the gap property

- src/dashboards/Poster/Poster.scss
- src/dashboards/Poster/components/BusTile/BusTile.scss
Added word break to mobility descriptions
Made fonts for sub-titles and bus tile larger
More left padding on bus icons
> Minor styling changes

- src/dashboards/Poster/Poster.scss
- src/dashboards/Poster/Poster.tsx
- Styling the poster view when bus tile is ticked off
- Created a variable in poster that checks whether or not bus is hidden, and based the styling on this variable
> Styling poster view when bus is not shown

- src/dashboards/Poster/Poster.scss
- src/dashboards/Poster/Poster.tsx
- Added the bike tile with real time data
> Add bike tile

- src/containers/Admin/EditTab/EditTab.tsx
- src/containers/Admin/EditTab/PosterMobilityAlert.tsx
Added component for checking if chosen mobility types are more than it can be, for poster mode
> Component checking if "checked" mobility types exceed the maximum possible for poster mode

- src/dashboards/BusStop/components/BusStopTile/BusStopTile.module.scss
- src/dashboards/BusStop/components/BusStopTile/BusStopTile.tsx
- types/scss-modules.d.ts
- webpack.config.js
* Add support for css-modules. All .module.scss files are treated as a css module that can be imported from
* Use css-modules in BusStopTile.tsx
> css-modules

- src/dashboards/Poster/components/BikeTile/BikeTile.tsx
Poster counted number of bike stations nearby instead of showing number of bikes available
> Bugfix for poster not showing number of bikes

- src/components/QRTile/MobileAppQRTile.module.scss
- src/components/QRTile/MobileAppQRTile.tsx
- src/dashboards/Chrono/ChronoDashboard.tsx
- src/dashboards/Compact/CompactDashboard.tsx
Removed <text> as it is not a valid html tag
1.8 as height messes with spacing between elements slightly
> Minor bug fixes

- src/containers/Admin/EditTab/BikeSearch/BikePanelSearch.tsx
- src/containers/Admin/EditTab/StopPlaceSearch/StopPlaceSearch.tsx
- src/containers/LandingPage/SearchPanel/SearchPanel.tsx
Endret til tydeligere ledetekster
> Endret til tydeligere ledetekster

- src/containers/Admin/DashboardPickerTab/DashboardPickerTab.tsx
* Add map option in DashboardPickerTab
> enable-map-dashboard-again

- CONTRIBUTING.md
- package-lock.json
- package.json
- types/graphql.d.ts
- webpack.config.js
* Remove graphql-loader config
* Remove graphql-tag package
* Add small description of how graphql is used in the project
> remove-graphql-loader

- src/components/TileHeader/TileHeader.module.scss
- src/components/TileHeader/TileHeader.tsx
- src/dashboards/BusStop/components/BusStopTile/BusStopTile.module.scss
- src/dashboards/BusStop/components/BusStopTile/BusStopTile.tsx
> Busstop dash header icons and text

- src/containers/Admin/DashboardPickerTab/DashboardPickerTab.module.scss
- src/containers/Admin/DashboardPickerTab/DashboardPickerTab.tsx
* Use setSettings instead of local state
* Use css-modules
> refactor-dashboard-picker

- stylelint.config.js
* Remove a duplicate stylelint rule that was added by mistake
> remove-duplicate-stylelint-rule

- src/logic/use-stop-place-ids/useStopPlaceIds.ts
* Skip fetching stop place ids if settings.hiddenModes includes 'kollektiv'
> skip-fetching-stops

- src/containers/LandingPage/LandingPage.scss
- src/containers/LandingPage/LandingPage.tsx
- Første element man tabber til på landing page er nå en link som lar deg hoppe direkte til hovedinnholdet
> Uu hoppe over blokker

- graphql-generated/journey-planner-v3.ts
- graphql-schemas/journey-planner-v3.json
- src/dashboards/BusStop/components/SituationInfo/SituationInfo.tsx
- src/logic/use-stop-place-with-estimated-calls/types.ts
- src/logic/use-stop-place-with-estimated-calls/useStopPlaceWithEstimatedCalls.journey-planner.graphql
We have some cases were we want to show description on a situation if not summary exists. This add support for this.
> Using description from situations if not summary exists

- src/components/Footer/Footer.module.scss
- src/components/Footer/Footer.tsx
- src/containers/Admin/AdminPage.tsx
- src/containers/App.tsx
- src/containers/LandingPage/LandingPage.tsx
Lagt til footer med infromasjon om nettsiden. Nettstedkart-siden legges til i annen branch.
(+ added aria label to h1 on admin page)
> Information footer

- src/containers/ResponsiveGridDashboard/ResponsiveGridDashboard.tsx
Waits until stopplaces are fethched to render responsive grid
> Fixes stored layout not being applied

- src/containers/Admin/EditTab/ReloadTile/ReloadTile.tsx
Added confirmation on button for reloading Tavla screens
> Added confirmation on button for reloading Tavla screens

- src/containers/Admin/LogoTab/Description/Description.module.scss
- src/containers/Admin/LogoTab/Description/Description.tsx
Adds button to confirm description change in Logo tab Makes description update on confirm instead of automatically when typing
> Changes description change in logo tab

- src/containers/Navbar/Navbar.module.scss
- src/containers/Navbar/Navbar.tsx
- Link to github opening in new tab
- Icon indicating link will open in new tab
> f(github): link in new tab + icon

- src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveTable/ResponsiveTableHeader/ResponsiveTableHeader.module.scss
- src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveTable/ResponsiveTableRow/ResponsiveTableRow.module.scss
- src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveTable/ResponsiveTableRow/ResponsiveTableRow.tsx
- Teksten på destinasjonen justeres ned i “boldness” 
- Kontrastfarger i rutene for linje 
- Fargen på linjene i tabellen justeres ned
- Skriften til linjenummer i tag justeres ned.
- Skriftstørrelsen på avviksmeldinger justeres ned så man kan se mer av teksten
> styling(responsive-dashboard):  more readable

- src/containers/Admin/EditTab/ReloadTile/ReloadTile.tsx
checks if the refresh is actually done before sending feedback when clicking "Last inn tavler på nytt" in admin panel.
> fix(refresh): checks if the refresh is ok before sending feedback

- src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveTable/ResponsiveTableRow/ResponsiveTableRow.module.scss
- src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveTable/ResponsiveTableRow/ResponsiveTableRow.tsx
> feat(responsive): display delayed departures

- src/assets/styles/CustomProperties.scss
- src/components/DateDisplay.tsx
- src/dashboards/BusStop/components/BusStopTableRow/BusStopTableRow.module.scss
- src/dashboards/BusStop/components/BusStopTableRow/BusStopTableRow.tsx
- src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveTable/ResponsiveTableRow/ResponsiveTableRow.module.scss
- src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveTable/ResponsiveTableRow/ResponsiveTableRow.tsx
Add tavla-sub-font-color to all themes
It has slightly lower contrast than main font color
Change styling of DateDisplay on Responsive and BusStop dashboards
> style(responsive/busstop): change datedisplay

- src/hooks/useLocationPermission.ts
- src/routes/LandingPage/SearchPanel/SearchPanel.tsx
Change hook to use listener for geolocation permission
Change searchpanel to use new hook
> feat(location permission): rewrite hook

- .github/workflows/deploy_next_tavla_staging.yml
- next-tavla/src/types/converters.ts
With temporary converters fix so project builds until other PR is done
> feat(actions): add next deployment workflow

- next-tavla/.gitignore
- next-tavla/cypress/support/commands.ts
- next-tavla/package.json
- next-tavla/src/scenarios/Admin/components/AddTile/AddTile.cy.js
- next-tavla/src/scenarios/Admin/components/AddTile/index.tsx
- next-tavla/src/scenarios/Admin/components/AddTile/styles.module.css
- next-tavla/src/scenarios/Admin/index.tsx
- next-tavla/src/scenarios/Admin/reducer.tsx
- next-tavla/src/styles/global.css
- next-tavla/src/types/tile.ts
- next-tavla/yarn.lock
Use radio cards instead of dropdown for tile type selection.
Re-generate uuid when adding tiles, prevent duplicate when adding same tile twice.
Move AddTile to top of tile options.
> feat(admin): changes to admin layout

- next-tavla/src/scenarios/Admin/components/AddColumn/AddColumn.cy.js
- next-tavla/src/scenarios/Admin/components/AddColumn/index.tsx
- next-tavla/src/scenarios/Admin/components/AddColumn/styles.module.css
- next-tavla/src/scenarios/Admin/components/ColumnSettings/index.tsx
- next-tavla/src/scenarios/Admin/components/ColumnSettings/styles.module.css
- next-tavla/src/scenarios/Admin/components/SortableColumns/SortableColumns.cy.jsx
- next-tavla/src/scenarios/Admin/components/SortableColumns/index.tsx
- next-tavla/src/scenarios/Admin/reducer.tsx
Before:
After:
Collapsed
Uncollapsed
> feat(admin): changes to column settings interface

- next-tavla/src/Admin/scenarios/Edit/index.tsx
- next-tavla/src/Admin/scenarios/Edit/styles.module.css
made buttons for saving and looking at the board stick in the right corner when scrolling
> feat(edit): made button floating

- next-tavla/package.json
- next-tavla/yarn.lock
Automatically installs and sets up husky locally when running "yarn install" in next-tavla directory
> feat(husky): husky config for next-tavla

- next-tavla/src/Admin/components/Button/styles.module.css
- next-tavla/src/Admin/scenarios/TilesSettings/components/StopPlaceSettings.tsx
- next-tavla/src/Admin/scenarios/TilesSettings/components/TileSettingsHeader/index.tsx
> feat(edit): removed sortable button in setting wrapper

- next-tavla/codegen.ts
- next-tavla/src/Board/scenarios/Table/components/Via/index.tsx
- next-tavla/src/Board/scenarios/Table/components/Via/styles.module.css
- next-tavla/src/Board/scenarios/Table/index.tsx
- next-tavla/src/Shared/graphql/fragments/departure.graphql
- next-tavla/src/Shared/graphql/index.ts
- next-tavla/src/Shared/types/tile.ts
> feat(board): adds via destination column for departures

- next-tavla/src/Admin/scenarios/AddTile/components/AddMapTile.tsx
- next-tavla/src/Admin/scenarios/AddTile/components/AddQuayTile.tsx
- next-tavla/src/Admin/scenarios/AddTile/components/AddStopPlaceTile.tsx
- next-tavla/src/Admin/scenarios/AddTile/index.tsx
- next-tavla/src/Admin/scenarios/Edit/reducer.tsx
- next-tavla/src/Admin/types/index.tsx
- next-tavla/src/Shared/types/tile.ts
- next-tavla/src/Shared/utils/converters.test.ts
- next-tavla/src/Shared/utils/converters.ts
Supports new design/flow for creating and editing tiles
> feat(settings): adds stop place field on quay tiles

- next-tavla/src/Board/scenarios/Table/components/Line/index.tsx
- next-tavla/src/Board/scenarios/Table/components/Line/styles.module.css
- next-tavla/src/Board/scenarios/Table/components/TransportIcon/index.tsx
- next-tavla/src/Board/scenarios/Table/components/TransportIcon/styles.module.css
Before
After
removed transportation icon from the line column and created new component for the line icon in board
> feat(board): made line icon for view

- next-tavla/src/Shared/types/column.ts
- next-tavla/src/Shared/utils/converters.ts
New version V5. Not implemented in version list, converter still bumps settings up to V4
> feat(converter): add converter for new column structure

- next-tavla/src/Shared/components/Clock/index.tsx
https://nextjs.org/docs/messages/react-hydration-error
> fix(clock): fixed hydration error in clock

- next-tavla/src/Board/scenarios/StopPlaceTile/index.tsx
- next-tavla/src/Board/scenarios/Table/components/TableHeader/index.tsx
- next-tavla/src/Board/scenarios/Table/components/TableHeader/styles.module.css
- next-tavla/src/Board/scenarios/Table/components/TransportIcon/index.tsx
- next-tavla/src/Board/scenarios/Table/components/TransportIcon/styles.module.css
- next-tavla/src/Shared/graphql/index.ts
- next-tavla/src/Shared/graphql/queries/stopPlace.graphql
Created a new component in table, tableheader and added functionality for adding transportation icons in the header
> feat(board): shows icons for transportationmode in tableheader

- next-tavla/src/Admin/scenarios/AddTile/components/AddStopPlaceTile.tsx
- next-tavla/src/Admin/scenarios/AddTile/index.tsx
- next-tavla/src/Admin/scenarios/AddTile/styles.module.css
feat(addtile): new layout for adding a tile with a header
> feat(addtile): new layout for adding a tile with header

- next-tavla/src/Board/scenarios/Table/index.tsx
- next-tavla/src/Board/scenarios/Table/styles.module.css
- next-tavla/src/Shared/styles/themes/dark.css
> chore(board): edit font size and color on column headers 

- next-tavla/src/Admin/scenarios/AddTile/AddTile.cy.tsx
- next-tavla/src/Admin/scenarios/AddTile/index.tsx
> feat(edit): replaces disabled add tile button with toast

- next-tavla/src/Shared/types/column.ts
platform column should not be default
> fix(columns): change platform to not be default selected

- next-tavla/src/Admin/scenarios/Edit/reducer.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/index.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/styles.module.css
- next-tavla/src/Admin/scenarios/TileSettings/components/QuaySettings.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/StopPlaceSettings.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/TileSettingsWrapper/styles.module.css
- next-tavla/src/Shared/utils/firebase.ts
- next-tavla/src/Shared/utils/typeguards.ts
> feat(edit): adds platform dropdown component

- next-tavla/src/Shared/styles/pages/board.module.css
> fix(board): responsive vertical table

- next-tavla/src/Admin/scenarios/Edit/reducer.tsx
- next-tavla/src/Admin/scenarios/SelectLines/index.tsx
- next-tavla/src/Admin/scenarios/SelectLines/styles.module.css
- next-tavla/src/Admin/scenarios/TileSettings/components/TileSettingsWrapper/styles.module.css
- next-tavla/src/Shared/styles/themes/dark.css
- next-tavla/src/Shared/styles/themes/default.css
- next-tavla/src/Shared/styles/themes/light.css
New toggle for selecting all or none lines.
> feat(edit): adds toggle for selecting all lines 

- next-tavla/src/Board/scenarios/Table/components/Destination/index.tsx
- next-tavla/src/Board/scenarios/Table/components/Situation/index.tsx
- next-tavla/src/Board/scenarios/Table/components/Situation/styles.module.css
- next-tavla/src/Board/scenarios/Table/components/Situations/index.tsx
- next-tavla/src/Board/scenarios/Table/index.tsx
- next-tavla/src/Shared/types/column.ts
Removed the situation column and moved situation to be underneath the destination name.
> feat(board): removed situation column and moved situations beneath destination

- next-tavla/src/Admin/scenarios/TileSettings/index.tsx
- next-tavla/src/Admin/scenarios/TilesOverview/index.tsx
- next-tavla/src/Board/scenarios/Table/components/Situation/index.tsx
- next-tavla/tsconfig.json
> feat(edit): automatically choose tile for editing 

- next-tavla/src/Board/scenarios/Table/styles.module.css
> fix(board): fixed height for table rows in board

- next-tavla/src/Admin/scenarios/SelectTile/components/DeleteButton/index.tsx
- next-tavla/src/Admin/scenarios/SelectTile/components/DeleteButton/styles.module.css
- next-tavla/src/Admin/scenarios/SelectTile/components/RadioOption/index.tsx
- next-tavla/src/Admin/scenarios/SelectTile/components/RadioOption/styles.module.css
- next-tavla/src/Admin/scenarios/SelectTile/index.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/QuaySettings.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/StopPlaceSettings.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/TileSettingsWrapper/index.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/TileSettingsWrapper/styles.module.css
Moved delete button to tile settings to avoid having nested buttons.
before
after
> feat(edit): moved delete button

- next-tavla/src/Admin/scenarios/AddTile/styles.module.css
> feat(edit): tweaks width of add tile search bar

- next-tavla/src/Board/scenarios/Board/index.tsx
- next-tavla/src/Board/scenarios/Board/styles.module.css
- next-tavla/src/Board/scenarios/Table/components/Line/styles.module.css
- next-tavla/src/Board/scenarios/Table/components/Time/index.tsx
- next-tavla/src/Board/scenarios/Table/components/Time/styles.module.css
- next-tavla/src/Board/scenarios/Table/index.tsx
- next-tavla/src/Shared/styles/pages/board.module.css
> feat(board): scaling for multiple tiles

- next-tavla/src/Admin/scenarios/Edit/index.tsx
- next-tavla/src/Admin/scenarios/Landing/index.tsx
- next-tavla/src/Admin/scenarios/SelectLines/index.tsx
- next-tavla/src/Admin/scenarios/ShareTable/index.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/PlatformDropdown/index.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/QuaySettings.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/StopPlaceSettings.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/TileSettingsWrapper/index.tsx
- next-tavla/src/Board/scenarios/Table/components/Time/styles.module.css
- next-tavla/src/Shared/styles/themes/dark.css
Rephrased text in tilesoverview
and sorted the platforms in platform dropdown
> fix(edit): rephrase text 

- next-tavla/src/Shared/components/Clock/index.tsx
> fix(clock): hydration inconsistency in firebase

- next-tavla/src/Board/scenarios/Board/styles.module.css
- next-tavla/src/Board/scenarios/Table/components/TableHeader/index.tsx
- next-tavla/src/Board/scenarios/Table/components/TableHeader/styles.module.css
- next-tavla/src/Shared/styles/pages/board.module.css
> fix(board): spacing error in chrome 56

- next-tavla/src/Board/scenarios/Board/styles.module.css
> fix(styling): set flex-direction to column when screen in portrait mode

- next-tavla/src/Admin/scenarios/BoardList/components/Cell/index.tsx
- next-tavla/src/Admin/scenarios/BoardList/components/Cell/styles.module.css
- next-tavla/src/Admin/scenarios/BoardList/components/Row/index.tsx
- next-tavla/src/Admin/scenarios/BoardList/components/Row/styles.module.css
- next-tavla/src/Admin/scenarios/BoardList/index.tsx
Created a separate component/style wrapper for a cleaner Board-list table.
> chore(boardlist): created Cell-component and moved Row to BoardList/components/

- next-tavla/package.json
- next-tavla/src/Admin/scenarios/BoardList/components/Row/index.tsx
- next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
- next-tavla/src/Admin/scenarios/TileSettings/components/DeleteTile/index.tsx
- next-tavla/src/Shared/styles/imports.css
- next-tavla/yarn.lock
Added tooltips to buttons with no text: 
- edit board title
- delete tile
- copy link
- edit board
> feat(tooltips): added tooltips where necessary

- next-tavla/.gitignore
- next-tavla/.prettierignore
- next-tavla/package.json
Persists emulator-data, by using `yarn dev:persist`
> feat(emulators): persist data between emulator startup

- next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
Makes it so that the textfield is focused on and text selected when you click the "edit title"-button.
Remake of #1205
> feat(autofocus): autofocus and text selected when editing title

- next-tavla/pages/edit/[id].tsx
- next-tavla/pages/edit/boards.tsx
- next-tavla/pages/index.tsx
- next-tavla/src/Admin/components/AdminHeader/index.tsx
- next-tavla/src/Admin/components/CreateBoard/index.tsx
- next-tavla/src/Admin/scenarios/Boards/index.tsx
- next-tavla/src/Admin/scenarios/Login/index.tsx
- next-tavla/src/Shared/styles/pages/admin.module.css
- added AdminHeader component to all pages: landing, edit and boards
- updated AdminHeader component to get optional props about what buttons to show in header
- add icons to all buttons in header
- remove create board component from boards
| Before | After |
|-------|-------|
|<img width="1879" alt="image" src="https://github.com/entur/tavla/assets/64562118/b57172db-1ef0-411b-8fe6-4ff090f83e95">| <img width="1887" alt="image" src="https://github.com/entur/tavla/assets/64562118/62233afc-b35d-4bbd-a248-5a36287f2442">|
|<img width="1877" alt="image" src="https://github.com/entur/tavla/assets/64562118/266e0581-1f64-4b52-8bf1-0e2ef1f57964"> | <img width="1887" alt="image" src="https://github.com/entur/tavla/assets/64562118/0c2e92ab-2f5b-418b-a616-14952f3fbb32">|
| <img width="1864" …
> fix(header): structured navigation header

- next-tavla/src/Admin/scenarios/Edit/components/AddTile/index.tsx
- next-tavla/src/Shared/hooks/useDebouncedFetch.ts
> fix(addTile): non-working debounce

- next-tavla/pages/api/auth.ts
- next-tavla/pages/reset/[oob].tsx
- next-tavla/src/Admin/scenarios/Login/components/Email.tsx
- next-tavla/src/Admin/scenarios/Login/components/ResetPassword.tsx
- next-tavla/src/Admin/scenarios/Login/hooks/useFirebaseAuthError.ts
- next-tavla/src/Admin/scenarios/Login/index.tsx
- next-tavla/src/Admin/scenarios/ResetPassword/index.tsx
- next-tavla/src/Admin/scenarios/ResetPassword/styles.module.css
- next-tavla/src/Admin/types/login.ts
User will receive an e-mail with a link, that will redirect the user to ```/reset/[oob]``` where the user can set a new password.
> feat(user): reset password

- next-tavla/pages/edit/[id].tsx
- next-tavla/pages/edit/boards.tsx
- next-tavla/pages/index.tsx
- next-tavla/src/Admin/components/AdminHeader/index.tsx
- next-tavla/src/Admin/components/CreateBoard/index.tsx
- next-tavla/src/Admin/scenarios/Boards/index.tsx
- next-tavla/src/Admin/scenarios/Edit/index.tsx
- next-tavla/src/Admin/scenarios/Landing/index.tsx
- next-tavla/src/Admin/scenarios/Login/index.tsx
- next-tavla/tsconfig.json
Renders different texts in CreateBoard-button based on the login status of the user.
| Not logged in | Logged in |
|--------|--------|
| ![image](https://github.com/entur/tavla/assets/61384979/acc4d7b0-7ccd-4cca-9dcb-eff6a071d10a) | ![image](https://github.com/entur/tavla/assets/61384979/a7e5088a-08d3-4483-8046-77d82004c93d) |
> feat(landing): conditionally render button text based on login status

- next-tavla/src/Admin/scenarios/Edit/utils/reducer.ts
- next-tavla/src/Board/scenarios/Table/components/Time/components/AimedTime.tsx
- next-tavla/src/Board/scenarios/Table/components/Time/components/ExpectedTime.tsx
- next-tavla/src/Board/scenarios/Table/components/Time/components/styles.module.css
- next-tavla/src/Board/scenarios/Table/index.tsx
- next-tavla/src/Shared/styles/global.css
- next-tavla/src/Shared/types/column.ts
- next-tavla/src/Shared/utils/converters.ts
> feat(time): new column for aimed departure time

- next-tavla/src/Shared/components/Pulse/styles.module.css
Change border radius from fixed size to 50%
> chore(realtime): fix border radius

- next-tavla/src/Shared/components/Pulse/index.tsx
- next-tavla/src/Shared/components/Pulse/styles.module.css
Fix opacity and use sceleton list in CSS
> styling(realtime): remove opacity css

- next-tavla/.eslintrc.json
- next-tavla/package.json
- next-tavla/yarn.lock
Added a new ESlint rule that detects unnecessary curly braces around string in props and other JSX.
I.e. `className={'someClass'}` will trigger an ESlint warning.
> feat(eslint): added eslint rule for detecting unnecessary curly braces

- next-tavla/src/Board/scenarios/Table/components/Time/components/ExpectedTime.tsx
- next-tavla/src/Board/scenarios/Table/components/Time/components/styles.module.css
- next-tavla/src/Shared/utils/time.ts
- Only show 'min' if the departure departs within 10 minutes
- Show date if departure is not today
> feat(time): several small fixes/improvements to time

- next-tavla/src/Admin/scenarios/Boards/components/TableHeader/ColumnHeader.tsx
Adds the `aria-sort` attribute to column headers
> feat(accessibility): added aria-sort attribute to column headers

- next-tavla/src/Admin/scenarios/CreateBoard/components/AddStops.tsx
- next-tavla/src/Admin/scenarios/CreateBoard/components/CreateBoardButton.tsx
Own component for the creation of a board.
> chore(create): component for creating a board

- next-tavla/src/Admin/scenarios/CreateBoard/components/AddStops.tsx
- next-tavla/src/Admin/scenarios/CreateBoard/components/CreateBoardButton.tsx
- next-tavla/src/Admin/scenarios/CreateBoard/components/Name.tsx
- next-tavla/src/Admin/scenarios/CreateBoard/components/NextPage.tsx
- next-tavla/src/Admin/scenarios/CreateBoard/components/StopPlaceList.tsx
- next-tavla/src/Admin/scenarios/Edit/components/AddTile/index.tsx
- next-tavla/src/Admin/scenarios/Edit/index.tsx
- next-tavla/src/Shared/styles/placement.css
More consistency regarding sizing and placement of buttons in the modal.
> styling(create): more consistent placement and size on buttons

- next-tavla/src/Admin/scenarios/Edit/components/AddTile/index.tsx
placeId assigned wrong value when 'Velg alle' was selected.
> fix(create): fix dispatch when 'Vis alle' is selected

- next-tavla/src/Admin/components/DeleteModal/index.tsx
- next-tavla/src/Admin/scenarios/Boards/components/FilterButton/index.tsx
- next-tavla/src/Admin/scenarios/Boards/components/FilterButton/styles.module.css
- next-tavla/src/Admin/scenarios/Boards/components/SelectOrganization/index.tsx
- next-tavla/src/Admin/scenarios/Boards/components/ToggleBoardsColumns/index.tsx
- next-tavla/src/Admin/scenarios/Edit/index.tsx
- next-tavla/src/Admin/scenarios/Organizations/index.tsx
Last commit from the #1326 branch were not pushed before merging 💩
> fix(code quality): revert h1 styling - last commits

- next-tavla/src/Admin/scenarios/Boards/components/FilterButton/index.tsx
- aria: https://www.uutilsynet.no/wcag-standarden/111-ikke-tekstlig-innhold-niva/87
- text on the button: https://www.uutilsynet.no/wcag-standarden/133-sensoriske-egenskaper-niva/92
> chore(accessibility): aria + text filter button

- next-tavla/src/Admin/components/IllustratedInfo/index.tsx
- next-tavla/src/Admin/scenarios/Landing/index.tsx
- next-tavla/src/Admin/scenarios/Login/components/CreateUser.tsx
- next-tavla/src/Admin/scenarios/Login/components/Email.tsx
- next-tavla/src/Admin/scenarios/Login/components/ResetPassword.tsx
- next-tavla/src/Admin/scenarios/Login/components/Start.tsx
> fix(accessibility): added correct aria-hidden attributes and alt-texts

- next-tavla/src/Board/scenarios/Table/components/Situation/index.tsx
Fallback to summary instead of detailed description for deviations.
> feat(situation): summary default

- next-tavla/pages/edit/[id].tsx
- next-tavla/src/Admin/scenarios/Edit/index.tsx
> feat(edit): open board button

- next-tavla/pages/404.tsx
- next-tavla/pages/[id].tsx
- next-tavla/pages/boards/[id].tsx
- next-tavla/pages/boards/index.tsx
- next-tavla/pages/edit/[id].tsx
- next-tavla/pages/index.tsx
- next-tavla/pages/organizations/index.tsx
- next-tavla/pages/reset/[oob].tsx
- next-tavla/src/Shared/components/TavlaHead/index.tsx
Added page title and description to pages in `pagerouter`
> feat(accessibility): add page titles and descriptions

- next-tavla/src/Board/scenarios/Table/components/Time/ExpectedTime.tsx
- next-tavla/src/Board/scenarios/Table/components/Time/styles.module.css
> feat(departure): show cancellations

- next-tavla/app/(admin)/components/Delete/index.tsx
- next-tavla/app/(admin)/organizations/[id]/page.tsx
- next-tavla/app/(admin)/organizations/components/Cell/Actions.tsx
- next-tavla/src/Admin/types/organizations.ts
Delete organization button in list over organizations
> feat(organizations): delete organization in org list

- next-tavla/src/Shared/graphql/index.ts
- next-tavla/src/Shared/graphql/queries/quay.graphql
- next-tavla/src/Shared/graphql/queries/stopPlace.graphql
> fix(board): add missing cancelled departures

- next-tavla/app/(admin)/utils.ts
- next-tavla/src/Admin/scenarios/Organization/components/UploadLogo/LogoInput.tsx
- next-tavla/src/Admin/scenarios/Organization/components/UploadLogo/actions.ts
- next-tavla/src/Admin/scenarios/Organization/components/UploadLogo/index.tsx
- next-tavla/src/Admin/scenarios/Organization/components/UploadLogo/styles.module.css
> feat(logo): limit file upload size to 10mb

- next-tavla/src/Board/scenarios/Table/components/Destination.tsx
- next-tavla/src/Board/scenarios/Table/components/Situation/styles.module.css
- next-tavla/src/Board/scenarios/Table/components/Situations.tsx
- next-tavla/src/Board/scenarios/Table/index.tsx
- next-tavla/src/Shared/styles/misc.css
- next-tavla/src/Shared/types/column.ts
- next-tavla/src/Shared/utils/converters.ts
Deviations now overflow with ellipsis as a placeholder
Removed deviations column and updated destination column name
> feat(deviations): overflow ellipsis and removed deviations column

- next-tavla/src/Shared/components/Header/styles.module.css
> feat(logo): ensure gap between logo and clock

- next-tavla/src/Board/scenarios/QuayTile/index.tsx
> feat(quay): remove description from quay board view

- next-tavla/app/(admin)/boards/components/Column/Delete.tsx
- next-tavla/src/Admin/components/DeleteModal/index.tsx
- Change line spacing in text, by changing from LeadParagraph to Paragraph component
- Change distance between heading and paragraph by adding margin
- Add space and punctuation in modal text
Result:
> styling(delete):  delete board modal text

- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
- next-tavla/pages/[id].tsx
- next-tavla/src/Shared/components/Header/index.tsx
- next-tavla/src/Shared/components/Header/styles.module.css
- next-tavla/src/Shared/types/meta.ts
Show title on board if checked
> feat(board): show title on board

- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
- next-tavla/pages/[id].tsx
- next-tavla/src/Shared/components/Header/index.tsx
- next-tavla/src/Shared/components/Header/styles.module.css
- next-tavla/src/Shared/types/meta.ts
> Revert "feat(board): show title on board"

- next-tavla/app/(admin)/organizations/components/MemberAdministration/index.tsx
- next-tavla/app/(admin)/organizations/components/UploadLogo/LogoInput.tsx
- next-tavla/app/(admin)/organizations/components/UploadLogo/index.tsx
- next-tavla/app/(admin)/organizations/components/UploadLogo/styles.module.css
Changes made  are on the left hand side in the picture, mostly
> feat(logo): improve accessibility and styling

- next-tavla/src/Shared/graphql/index.ts
- next-tavla/src/Shared/styles/fonts.css
- next-tavla/src/Shared/styles/global.css
- next-tavla/src/Shared/styles/reset.css
> feat(edit): fix county select color

- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
- next-tavla/app/(admin)/edit/[id]/page.tsx
> feat(edit): relocate MetaSettings and open board button

- next-tavla/app/(admin)/components/TileSelector/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/TileCard/TransportModeCheckbox.tsx
- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/TileCard/styles.module.css
- next-tavla/app/(admin)/edit/[id]/page.tsx
> style(edit): improve styling of TileCard

- next-tavla/app/(admin)/components/Delete/index.tsx
> feat(delete): move delete organization label above input field

- next-tavla/app/(admin)/components/CreateBoard/actions.ts
- next-tavla/app/(admin)/components/CreateBoard/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/FontChoiceChip.tsx
- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
- next-tavla/app/(admin)/edit/[id]/page.tsx
- next-tavla/app/(admin)/organizations/[id]/page.tsx
- next-tavla/app/(admin)/organizations/components/FontSelect/actions.ts
- next-tavla/app/(admin)/organizations/components/FontSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/FontSelect/styles.module.css
- next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
- next-tavla/src/Shared/types/settings.ts
> feat(organization): set default font size for organization

- next-tavla/app/(admin)/admin.module.css
- next-tavla/app/(admin)/organizations/[id]/page.tsx
- next-tavla/app/(admin)/organizations/components/DefaultColumns/index.tsx
- next-tavla/app/(admin)/organizations/components/FontSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/FontSelect/styles.module.css
- next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/index.tsx
- next-tavla/app/(admin)/organizations/components/UploadLogo/index.tsx
- next-tavla/app/(admin)/organizations/components/UploadLogo/styles.module.css
- next-tavla/src/Shared/styles/global.css
- next-tavla/src/Shared/styles/spacing.css
> feat(organization): clean up writing and styling

- next-tavla/app/(admin)/organizations/components/UploadLogo/styles.module.css
> feat(organizations): focus on logo upload

- next-tavla/app/(admin)/components/Delete/index.tsx
> styling(delete): delete org modal text

- next-tavla/app/(admin)/components/CreateBoard/index.tsx
- next-tavla/app/(admin)/components/TileSelector/index.tsx
- next-tavla/app/(admin)/components/TileSelector/styles.module.css
Before:
-  ![image](https://github.com/entur/tavla/assets/74315929/6f28159c-d2d9-4691-b179-a14947d93b08)
-  ![image](https://github.com/entur/tavla/assets/74315929/87bcbdd6-f475-412a-8cb3-c084c512d90c)
After
- <img width="1636" alt="image" src="https://github.com/entur/tavla/assets/74315929/99920481-61e1-42f2-a0fe-67b2b001d1a0">
- <img width="1424" alt="image" src="https://github.com/entur/tavla/assets/74315929/8cb5987b-9cdc-4e09-a5ff-2d093ec77023">
> fix(edit): textfields jumping when adding new stop-place

- next-tavla/app/(admin)/components/Footer/index.tsx
> feat(landing): improve links

- next-tavla/app/(admin)/components/CreateBoard/components/StopPlaceList.tsx
- next-tavla/app/(admin)/components/CreateBoard/components/TileCard.tsx
- next-tavla/app/(admin)/components/CreateBoard/index.tsx
Add spacing above the heading and between the icon and "Fjern" text on the button to look like this: 
Also removed some unneccessary divs and changed styling to be similar in the two steps in the modal.
> styling(create): add spacing on heading and button

- next-tavla/app/(admin)/organizations/[id]/page.tsx
- next-tavla/app/(admin)/organizations/components/DefaultColumns/index.tsx
- next-tavla/app/(admin)/organizations/components/FontSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/MemberList.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/styles.module.css
Update texts on edit organisation page and fixed spacing on heading and lead paragraph according to the sketches.
> chore(): update texts on edit org

- next-tavla/app/(admin)/organizations/components/DefaultColumns/index.tsx
- next-tavla/app/(admin)/organizations/components/FontSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/styles.module.css
- next-tavla/app/(admin)/organizations/components/UploadLogo/index.tsx
- next-tavla/app/(admin)/organizations/components/UploadLogo/styles.module.css
- next-tavla/app/(admin)/utils/index.ts
- Move heading inside boxes
- Align the boxes (headings are aligned, paragraphs are align, buttons....)
> style(organization): move heading inside boxes and align items

- next-tavla/app/(admin)/components/IllustratedInfo/index.tsx
- next-tavla/app/(admin)/components/IllustratedInfo/styles.module.css
Before
- ![image](https://github.com/entur/tavla/assets/74315929/d1f96da1-4619-45b1-bace-ce8fdd9df7b2)
After
- ![image](https://github.com/entur/tavla/assets/74315929/ed195ff0-b079-40d2-a7fe-18dec8215eed)
> style(boards): spacing on empty board text

- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> feat(edit): prompt user for TileCard change confirmation

- next-tavla/app/(admin)/boards/components/Column/Tags.tsx
> feat(boards): modify badge type

- next-tavla/app/(admin)/boards/components/BoardTable/index.tsx
- next-tavla/app/(admin)/boards/components/SelectOrganization/index.tsx
- next-tavla/app/(admin)/components/CreateBoard/index.tsx
- next-tavla/app/(admin)/organizations/page.tsx
- next-tavla/app/(admin)/utils/types.ts
Follow the "stil og tone" we have set for the application
> chore(reword): fix capitalization

- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- next-tavla/app/globals.css
- next-tavla/src/Board/scenarios/QuayTile/index.tsx
- next-tavla/src/Board/scenarios/StopPlaceTile/index.tsx
- next-tavla/src/Shared/graphql/index.ts
- next-tavla/src/Shared/graphql/queries/quay.graphql
- next-tavla/src/Shared/graphql/queries/stopPlace.graphql
- next-tavla/src/Shared/types/tile.ts
- next-tavla/src/Shared/utils/time.ts
- next-tavla/tailwind.config.js
> feat(board): set offset to show later departures

- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- next-tavla/app/globals.css
- next-tavla/tailwind.config.js
Added red label to warn user on why switch is disabled
> style(edit): warning on walking distance switch disabled

- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- next-tavla/app/globals.css
Before:
- ![image](https://github.com/entur/tavla/assets/74315929/88db9e27-cd37-4c8f-8d8e-567c1d94af03)
After:
- <img width="722" alt="image" src="https://github.com/entur/tavla/assets/74315929/f155c68f-0010-4ef6-b163-9270023b4a75">
> fix(edit): disable switch and label colors

- next-tavla/app/globals.css
- next-tavla/app/privacy/page.tsx
> fix(footer): place footer on bottom of page

- next-tavla/app/(admin)/edit/[id]/components/Footer/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/Adress.tsx
- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- next-tavla/app/(admin)/organizations/components/DefaultColumns/index.tsx
- next-tavla/app/(admin)/organizations/components/FontSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/Footer/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/InviteUser.tsx
> styling(buttons): full width on mobile screen

- next-tavla/src/Board/scenarios/Table/components/Line/index.tsx
- next-tavla/src/Shared/utils/publicCode.ts
> feat(board): show air public code

- next-tavla/app/(admin)/organizations/components/UploadLogo/index.tsx
Before:
- ![image](https://github.com/entur/tavla/assets/74315929/827b298a-8f3e-4eb3-bb2d-fd06f4078f9a)
After:
- ![image](https://github.com/entur/tavla/assets/74315929/46d7b4f5-e04e-47a0-9853-0abd87c28b04)
> fix(organizations): bg color logo preview

- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> style(edit): color on subtexts

- next-tavla/app/(admin)/boards/components/Search/index.tsx
Before:
- ![image](https://github.com/entur/tavla/assets/74315929/d63a5804-8a1a-4f8f-8491-3510958b8023)
After:
- ![image](https://github.com/entur/tavla/assets/74315929/7a049b85-328f-4889-a5de-2304580d3a8d)
> fix(search): clearable

- next-tavla/app/(admin)/edit/[id]/components/MetaSettings/Adress.tsx
Before
- ![image](https://github.com/entur/tavla/assets/74315929/68d817aa-eaad-4bd4-8273-3292e8070e2e)
After
- ![image](https://github.com/entur/tavla/assets/74315929/4a801b30-4203-4be8-a54b-6c30e4b048d2)
> chore(boards): change location text

- next-tavla/app/providers.tsx
> chore(posthog): embed values

- next-tavla/app/(admin)/edit/[id]/components/ClientBoard.tsx
- next-tavla/app/(admin)/edit/[id]/components/Preview/index.tsx
- next-tavla/app/(admin)/edit/[id]/page.tsx
> styling(preview): show full board in preview

- next-tavla/app/(admin)/organizations/[id]/page.tsx
- next-tavla/app/(admin)/organizations/components/MemberAdministration/index.tsx
> fix(organization): update member text

- next-tavla/app/verify/[oob]/page.tsx
> fix(verify): redirect to login

- next-tavla/app/(admin)/boards/components/Column/Delete.tsx
- next-tavla/app/(admin)/components/CreateBoard/actions.ts
- next-tavla/app/(admin)/edit/[id]/components/ActionsMenu/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/DuplicateBoard/index.tsx
- next-tavla/app/(admin)/edit/[id]/page.tsx
> feat(edit): duplicate existing board

- next-tavla/app/(admin)/organizations/components/DefaultColumns/ColumnModal.tsx
> chore(columns): column modal text

- next-tavla/app/(admin)/boards/components/FilterButton/index.tsx
Didnt change the background color of the popover because it is supposed to be this way (see [designsystem](https://design.entur.no/komponenter/feedback/popover)). 
Also didnt make the heading smaller because it looked a bit weird that the heading was same size as the text
> fix(tags): add null tags text and styling

- next-tavla/app/(admin)/components/Login/Create.tsx
- next-tavla/app/(admin)/components/Login/Email.tsx
- next-tavla/app/(admin)/utils/index.ts
- next-tavla/app/verify/[oob]/page.tsx
Removed code for manually checking if email is verified. Related to this PR: . 
Add more decriptive text to make sure the user can try to login because they are most likely verified.
> refactor(verify): remove manual check and change text in message

- next-tavla/app/(admin)/boards/components/Column/Delete.tsx
- next-tavla/app/(admin)/boards/page.tsx
- next-tavla/app/(admin)/components/Footer/index.tsx
- next-tavla/app/(admin)/components/TopNavigation.tsx
- next-tavla/app/(admin)/edit/[id]/components/Buttons/Open.tsx
- next-tavla/app/(admin)/edit/[id]/components/RefreshButton/index.tsx
- next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- next-tavla/app/(admin)/edit/[id]/page.tsx
- next-tavla/app/(admin)/layout.tsx
- next-tavla/app/(admin)/organizations/[id]/page.tsx
- next-tavla/app/(admin)/organizations/page.tsx
- next-tavla/app/demo/page.tsx
- next-tavla/app/globals.css
- next-tavla/app/page.tsx
- next-tavla/app/privacy/page.tsx
- next-tavla/app/verify/[oob]/page.tsx
- next-tavla/package.json
- next-tavla/tailwind.config.ts
- next-tavla/yarn.lock
> feat(edit): redesign of layout

- tavla/app/page.tsx
Fixes:
- spacing
- bulletpoints
- cursive
- updated text
Spacing in main illustration:
> style(landing): fix issue of bulletpoints disappearing

- tavla/app/demo/components/CreateUserButton.tsx
- tavla/app/demo/components/DemoBoard.tsx
- tavla/app/demo/page.tsx
Headings have been modified to align with the hierarchical structure.
> style(demo): modify headings to align with hierarchical structure

- tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> feat(edit): show original stop place name

- tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
> style(tilecard): smaller input fields

- tavla/app/(admin)/components/TileSelector/index.tsx
- tavla/app/(admin)/edit/[id]/page.tsx
After (in edit page)
- <img width="1648" alt="image" src="https://github.com/user-attachments/assets/95fb1514-44c4-4208-b20f-5e4a1d33dbfd">
> fix(edit): show icons on dropdown

- tavla/app/(admin)/edit/[id]/components/TileCard/utils.ts
- tavla/app/globals.css
- tavla/src/Shared/components/TransportIcon/index.tsx
- tavla/tailwind.config.ts
> feat(tilecard): add support for taxi in tilecard and tileselector

- tavla/app/page.tsx
- tavla/tailwind.config.ts
> style(app): add padding when page is less than 768px

- tavla/app/globals.css
- tavla/src/Shared/components/Pulse/index.tsx
- tavla/tailwind.config.ts
Tested on older browsers for compatilibity and our designer approved it visually
Please test this locally as well 🤝 
I have noticed the pulsating icon appears to be different in size on the landing page and preview (in /edit) due to screensizes, let me know if that`s an issue.
Thanks
Before
-
https://github.com/user-attachments/assets/953e2087-b987-4e2f-838f-a6d6b3caf459
After
- 
https://github.com/user-attachments/assets/cd0cb34f-de57-4aa3-9423-d47fbed710e6
> style(board): pulsating real-time icon

- backend/readme.md
- backend/src/main.rs
la til hvordan man kobler lokal backend til lokal frontend for å teste at hele greia funker sammen
> chore(backend): update readme.md and handle return type of redis publish calls

- tavla/app/(admin)/components/Login/Email.tsx
After:
- ![image](https://github.com/user-attachments/assets/854b4f77-1883-40ca-9533-414dc591ceed)
> style(login): forgot password as link

- tavla/app/components/ContactForm.tsx
> style(edit): background color reaches all the way to footer

- tavla/pages/[id].tsx
Prøver å ta en sjekk i `getServerSideProps()` om man skal logge eller ikke basert på om next prefetch headeren er der. Grunnen til at jeg ikke flyttet loggen til middlewaren er fordi der hadde jeg ikke tilgang på `board.id` eller `organization.name`. Derfor sjekker jeg heller requesten når siden lastes ved brukav `context`:
https://nextjs.org/docs/pages/api-reference/functions/get-server-side-props#context-parameter
> fix(board): log on server if prefetched header is not present

- tavla/app/(admin)/components/HorizontalNavBar.tsx
- tavla/app/(admin)/edit/[id]/components/Footer/index.tsx
- tavla/app/(admin)/edit/[id]/components/MetaSettings/Adress.tsx
- tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- tavla/app/(admin)/organizations/components/DefaultColumns/index.tsx
- tavla/package.json
Fikser litt småting som har endret seg i designsystemet.
> fix(ui): ui improvements after version bump 

- tavla/app/(admin)/boards/components/FilterButton/index.tsx
- tavla/app/(admin)/boards/components/TagModal/AddExistingTag.tsx
Tags er nå uppercase i legg til og filtrer-modalene
> chore(tags): set tags to uppercase in all modals

- tavla/app/(admin)/organizations/components/CreateOrganization/actions.ts
- tavla/app/(admin)/organizations/components/CreateOrganization/index.tsx
maxlength satt til 40. 50 virket litt langt ut. lmk om vi skal endre
> fix(organizations): limit name length

- tavla/helm/tavla/values.yaml
Vi hadde glemt å legge ved å faktisk skru på prometheus
> chore(monitoring): enable prometheus

- tavla/pages/[id].tsx
- tavla/src/Shared/utils/browserDetection.ts
Ifm. at tv-tavla plutselig kræsja legger jeg på litt sjekker og debug-meldinger til sentry for å fange opp feilen hvis den skjer igjen.
> fix(board): add debugging-info to exceptions in getServerSideProps

- tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
deleteTile bruker nå tile.uuid for å først hente ut tile-objektet som ligger i firestore, og så slette det. Da fikser vi problemet som ville oppstått 15. desember med codespace endring
> fix(TileCard): delete tile based on unique tile id

- tavla/pages/[id].tsx
> chore(board): silence sentry logs

- tavla/app/(admin)/boards/components/TagModal/actions.ts
Vi fikk opp feilmelding i sentry når noen prøvde å legge til en duplicate tag, og bruker fikk da ikke feilmelding i skjema.
Endrer slik at oppførselen nå er:
- hvis bruker prøver å legge til en lapp som finnes, men som ikke er lagt til nåværende tavle, så legges den eksisterende merkelappen til heller enn å lage en ny
- hvis bruker prøver å legge til lapp som finnes OG som er på nåværende tavle, får hen feilmelding i skjema, og ingenting logges til sentry
- hvis bruker allerede har to av samme merkelapper (før denne endringen ble gjort) filtreres disse bort når vi henter tags fra firebase, så bare én av de to vil finnes og kunne legges til tavler
- sentry logges kun når selve firebase-kallet gir en feil
> chore(edit): remove existing duplicate tags

- tavla/app/(admin)/utils/index.ts
VariantType error, som vi bruker på form feedback, er deprecated og skal byttes ut med negative. Det samme er info, som skal byttes ut med information.
Bytter ut typene, og endrer VariantType import fra entur/forms til entur/utils. Ingen synlige endringer i løsningen
> chore(error): update error messages variant from error to negative

- tavla/helm/tavla/values.yaml
---
Følger best practices med secrets håndtering.
Oppretter den samme secreten i external secrets manager, og refererer til denne gjennom helm charts
> feat(secrets): migrate secret to external secret manager

- tavla/app/(admin)/edit/[id]/components/MetaSettings/Adress.tsx
- tavla/package.json
- tavla/yarn.lock
Bumper pakken slik at vi slipper å få SSR-klaging fra Next. 
Bumpet pakken til `6.0.13`
> chore(deps): bump entur-dropdown

- backend/src/main.rs
---
Det hadde vært interessant å vite hvilke ider som er aktive, og vi vil dermed ha et godt estimat på en nedre grense av antall aktive tavler vi har i løsningen vår.
- Lager et nytt endepunkt i `/active/bids` (kan endre navn om ønskelig 😄 ) som returnerer en liste av tavle ider og antallet fra denne
Eksempel:
- ![image](https://github.com/user-attachments/assets/e0d2a7a2-87e9-40ff-8946-a753161d4638)
> feat(backend): endpoint for active board ids

- tavla/app/(admin)/edit/[id]/components/RefreshButton/index.tsx
- tavla/app/(admin)/edit/[id]/page.tsx
---
Endret variant til suksess og plassering, så det ser ut som skissene. Godkjent av designer
> style(edit): publish board position and bg color

- tavla/app/(admin)/boards/components/FilterButton/index.tsx
---
Samme aria label som navn på knappen
> fix(a11y): correct aria label filterbtn

- tavla/app/(admin)/organizations/components/Footer/index.tsx
- tavla/app/(admin)/organizations/components/UploadLogo/index.tsx
---
rette opp i wcag krav
alt tekst på org logo + riktig alt tekst på lagre infomelding
> fix(organizations): address WCAG issues voiceover and req 1.1.1

- tavla/app/components/ImageCarousel/ImageCarousel.tsx
- tavla/app/components/PreviewCarousel/index.tsx
---
Mer beskrivende alt tekst på landingssiden for bildekarusellen + lagt til aria-label på previewkarusell-knappene
> fix(landing): address WCAG issues 4.1.2 and 1.1.1

- tavla/app/(admin)/boards/components/Column/Delete.tsx
- tavla/app/(admin)/components/CreateBoard/NameAndOrganizationSelector.tsx
- tavla/app/(admin)/components/Delete/index.tsx
- tavla/app/(admin)/components/Login/Create.tsx
- tavla/app/(admin)/components/Login/Email.tsx
- tavla/app/(admin)/components/Login/Reset.tsx
- tavla/app/(admin)/components/Login/Start.tsx
- tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
- tavla/app/(admin)/organizations/components/CreateOrganization/index.tsx
- tavla/app/(admin)/organizations/components/DefaultColumns/ColumnModal.tsx
- tavla/app/(admin)/organizations/components/MemberAdministration/RemoveUserButton.tsx
---
lagt på h1 på alle modaler, og sørget for at aria label og knapper er like på disse
> fix(a11y): address WCAG issues for all modals

- backend/helm/backend/values.yaml
> feat(backend): migrate secret to external service

- tavla/app/(admin)/organizations/components/UploadLogo/index.tsx
---
fjerner preview-boks når logo ikke er lagt til
> fix(logo): remove default tavla logo

- tavla/app/(admin)/components/DeleteAccount/actions.ts
Liten bug med at man ikke slettet session-cookien når man slettet brukeren sin. Det åpner opp for at noen kan stjele session-iden, og man er utsatt for at noen stjeler sessionen din.
> fix(delete): remove session cookie when delete account

- tavla/pages/[id].tsx
---
Kommentar på manifestfarge
Added meta tag for theme color depending on `board.theme`
> style(board): theme color manifest

- tavla/pages/_document.tsx
- tavla/public/tavlevisning.webmanifest
---
(Beskriv endringene gjort, og legg gjerne ved bilder!)
> chore(board): add dark colors webmanifest

- tavla/src/Board/scenarios/Board/firebase.ts
---
(Beskriv endringene gjort, og legg gjerne ved bilder!)
> fix(board): return null if organization doesnt exist

- .github/pull_request_template.md
---
Å putte bilder i tabeller ser mye bedre ut enn å bare putte de inn, så prøver å snike inn dette hehe
La til en tabell i pr-templaten.
> chore(): add table in pr-template

- tavla/app/(admin)/tavler/[id]/rediger/components/ActionsMenu/index.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/DuplicateBoard/index.tsx
---
Unødvendig.
Skulle egentlig fjerne knappen, men den var visst allerede borte. Fjernet derimot litt unødvendig kode relatert til dupliser-knappen.
> chore(rediger): remove unused code

- tavla/app/(admin)/oversikt/components/Column/Name.tsx
---
Vi vil vise hvor mange av totalt antall tavler som tilhører en spesifikk mappe slik at brukeren får mer oversikt. 
Brukte getNumberOfBoardsInFolder(...) som ble implementert i #1855 til å hente antall tavler i en spesifikk mappe. For å kunne bruke denne asynkrone funksjonen på bunnen av et client-tre så ble det lagt til en client-side fetch og et nytt endepunkt så det går an å hente antallet tavler uten å prop-drille, legge til context, eller endre alle nivåene i treet til å være server-side. 
La også til en skeleton-loader fordi det ikke så bra ut at antallet poppet opp plutselig en stund etter refresh (ved innlogging går bra)
| ![image](https://github.com/user-attachments/assets/746a5878-211e-4e44-9f51-e4c04e63f3fb) | …
> feat(oversikt): show count of boards in folder

- .github/codeql.yml
- .github/workflows/codeql.yml
> chore(): add code scan workflow

- README.md
- tavla/app/help/page.tsx
Github -> GitHub
Øke profesjonalitet og førsteinntrykk
Github -> GitHub (hadde blanding rundt om)
> chore(help+README): Github -> GitHub

- tavla/app/privacy/components/ExpandableInfo.tsx
Øke profesjonalitet og førsteinntykk
| <img width="593" alt="Screenshot 2025-05-09 at 16 16 56" src="https://github.com/user-attachments/assets/fca78dff-9947-4461-b4ab-51f847627a93" /> | <img width="760" alt="Screenshot 2025-05-09 at 16 17 44" src="https://github.com/user-attachments/assets/01c05481-8a99-41e0-a127-1c138ef2111b" /> |
|<img width="244" alt="Screenshot 2025-05-12 at 13 32 10" src="https://github.com/user-attachments/assets/f8072025-6af0-4fde-b052-5a0303ef1c16" /> | <img width="231" alt="Screenshot 2025-05-12 at 13 31 45" src="https://github.com/user-attachments/assets/39a0d0e4-c61d-47ce-bd73-479e52505bf5" /> |
> chore(privacy): fix text on privacy page

- tavla/app/help/page.tsx
> fix(help): correct kakadu link

- .github/pull_request_template.md
Endre PR-template
Mer gøy i PRene
| <img width="1057" alt="Screenshot 2025-05-13 at 15 04 46" src="https://github.com/user-attachments/assets/45d1fbe5-4e3a-46e2-a1b5-c2e3b087a301" /> | <img width="1080" alt="Screenshot 2025-05-13 at 15 05 34" src="https://github.com/user-attachments/assets/8ef3656f-01f0-4a2e-9d64-455bac148c74" /> |
> chore(): update pull request template

- tavla/app/(admin)/components/TileSelector/utils.ts
- tavla/app/(admin)/hooks/useCountiesSearch.ts
Øke brukervennlighet
| <img width="467" alt="Screenshot 2025-05-14 at 14 33 30" src="https://github.com/user-attachments/assets/bf7ab745-f9ff-4f80-acc8-f3925f1d2aac" /> | <img width="513" alt="Screenshot 2025-05-14 at 14 33 03" src="https://github.com/user-attachments/assets/4efbc550-306c-4daf-ad39-1f29fd22aa7f" /> |
| | <img width="513" alt="Screenshot 2025-05-15 at 12 03 48" src="https://github.com/user-attachments/assets/148fcf93-4152-437b-94a7-5ebb21978b2d" /> |
> chore(rediger): sort counties list alphabetically

- tavla/.gitignore
- tavla/migrations/scripts/example.py
- tavla/migrations/scripts/init.py
- tavla/migrations/scripts/read_tile_column_count.py
---
Kan være greit med et ekstra eksempel hvor man bare leser fra databasen, derfor lastes det opp.
Legger til pycache i gitignore og legger til at man kan sende gjennom navn på local-db siden det ble noe tull der. 
La også inn scriptet som leser fra databasen og sjekker hvor mange av tavlene med flere tiles har ulike kolonner i tilesene.
> chore(): save a read tile column script

- tavla/app/page.tsx
Tydeliggjør at Tavla er gratis
| <img width="947" alt="Screenshot 2025-05-19 at 11 48 24" src="https://github.com/user-attachments/assets/e6b4319d-2c8d-4405-948d-fd52f1334e81" /> | <img width="849" alt="Screenshot 2025-05-19 at 11 47 58" src="https://github.com/user-attachments/assets/76fb630b-cf14-41d9-a938-49793c6a4bd8" /> |
| <img width="746" alt="Screenshot 2025-05-19 at 11 47 46" src="https://github.com/user-attachments/assets/8d8e158e-d76d-471a-9f20-931a7ef6a6e9" /> |  |
> chore(app): enhance gratis

- tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/FontSelect.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/ThemeSelect.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/index.tsx
Øke lesbarhet i løsningen - øke brukervennlighet
| <img width="600" alt="Screenshot 2025-05-15 at 14 32 27" src="https://github.com/user-attachments/assets/3b18848a-5b3f-47cc-90a0-83dbb0da1e3b" /> | <img width="572" alt="Screenshot 2025-05-15 at 14 31 34" src="https://github.com/user-attachments/assets/e6111a0f-4a70-483b-9030-42a3502e61b1" /> |
| <img width="378" alt="Screenshot 2025-05-15 at 14 32 08" src="https://github.com/user-attachments/assets/89cc5b62-3884-4aef-8e90-3312603d7987" /> | <img width="315" alt="Screenshot 2025-05-15 at 14 31 50" src="https://github.com/user-attachments/assets/8a020746-6e1f-4ef4-91fc-b9076ce8a888" /> |
> fix(chipgroup): increase spacing between title and chips

- tavla/app/(admin)/components/Footer/index.tsx
- tavla/app/(admin)/components/TopNavigation.tsx
- tavla/app/demo/page.tsx
- tavla/app/page.tsx
Ulik ordbruk på knapper og hvor knappene fører 
| <img width="1720" alt="Screenshot 2025-05-19 at 12 14 24" src="https://github.com/user-attachments/assets/875f9d1c-df65-4c11-b98c-2ce76315bf87" /> | <img width="1728" alt="Screenshot 2025-05-19 at 12 14 08" src="https://github.com/user-attachments/assets/31f2a664-7729-4c8d-b143-200b63b66e27" /> |
> chore(): change button text

- tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/ChoiceChipGroupGeneral.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/FontSelect.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/ThemeSelect.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/index.tsx
Standardisere komponenter for å redusere teknisk gjeld og redusere sjansen for feil
> chore(chipgroup): standardize choicechipgroup

- tavla/app/(admin)/components/CreateFolder/index.tsx
- tavla/app/(admin)/components/Delete/index.tsx
- tavla/app/(admin)/components/DeleteAccount/index.tsx
- tavla/app/(admin)/components/Login/index.tsx
- tavla/app/(admin)/components/SideNavBar.tsx
- tavla/app/(admin)/mapper/components/MemberAdministration/RemoveUserButton.tsx
- tavla/app/(admin)/oversikt/components/Column/Delete.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/index.tsx
Lagt til x (cancel)-knapp i små modaler også for å øke brukervennlighet 
Snakket med Magnus som mente dette burde finnes!
| <img width="567" alt="Screenshot 2025-05-16 at 13 16 11" src="https://github.com/user-attachments/assets/b9ddfdc4-303e-4c01-8ecd-84adb8c753ad" /> | <img width="524" alt="Screenshot 2025-05-16 at 13 14 34" src="https://github.com/user-attachments/assets/5e30e19d-fd21-4d10-9264-cea05969f9ee" /> |
> chore(modal): add x (cancel) button on small modals

- tavla/app/help/components/Questions.tsx
> fix(help): change word sound in question about combined stop

- tavla/app/(admin)/components/SideNavBar.tsx
- tavla/app/demo/components/DemoBoard.tsx
- tavla/app/demo/page.tsx
Øke spacing i demosiden
| <img width="1728" alt="Screenshot 2025-05-21 at 09 52 20" src="https://github.com/user-attachments/assets/55d93e0a-7cbf-4b6b-b6ae-52e5b8ec8591" /> | <img width="1728" alt="Screenshot 2025-05-21 at 09 52 02" src="https://github.com/user-attachments/assets/0cb8b2ce-3de3-49d4-8f81-ca664b86ef36" /> |
> fix(demo): spacing and alignment

- tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/TransportModeAndLines.tsx
Spesifisere hva man velger - spesielt med tanke på skjermleser feks
| <img width="396" alt="Screenshot 2025-05-22 at 18 10 04" src="https://github.com/user-attachments/assets/7070875c-50c8-4c45-a995-e8fc6014466e" /> | <img width="738" alt="Screenshot 2025-05-22 at 18 10 17" src="https://github.com/user-attachments/assets/83b96057-db20-4f8a-bf36-1c78727ce5c1" /> |
> chore(tavle): velg alle changed to velg alle linjer

- tavla/app/(admin)/components/CreateFolder/index.tsx
- tavla/app/(admin)/components/Delete/index.tsx
- tavla/app/(admin)/components/DeleteAccount/index.tsx
- tavla/app/(admin)/components/Login/index.tsx
- tavla/app/(admin)/components/SideNavBar.tsx
- tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/index.tsx
Bug i Sentry (close i oversikt)
> fix(modal): bug in close

- tavla/app/(admin)/components/Delete/index.tsx
- tavla/app/(admin)/components/DeleteAccount/index.tsx
- tavla/app/(admin)/mapper/components/MemberAdministration/RemoveUserButton.tsx
- tavla/app/(admin)/oversikt/components/Column/Delete.tsx
> chore(buttons): remove exclamation marks in buttons

- .github/pull_request_template.md
Siste dag med alenetid så nå kan kommentaren fjernes 🤌🏻
Justerer også litt på sjekkliste-teksten om nettlesere
> chore(): remove comment about working alone

- .github/pull_request_template.md
- tavla/README.md
Vi ønsker å gjøre PR-templaten litt mer konkret og relevant til vårt bruk. Vi ønsker også å utvide README slik at informasjonen om commits og branches ligger så nærme der det blir brukt som mulig. 
- Lagt til seksjon om commits og branching konvensjoner
- Utvidet informasjonen node versjonering
- Lagt til hvor man kan finne service keys'ene våre
> chore(github): update readme and pr template

- tavla/app/(admin)/oversikt/components/Column/Move.tsx
Som en bruker av Tavla
Ønsker jeg å bli informert om endringer av tilganger på tavler som flyttes
Slik at jeg enkelt kan administrere tilgangene i etterkant ved behov
|<img width="724" height="318" alt="image" src="https://github.com/user-attachments/assets/a0fe9f36-38d2-401e-8f0e-3b63c2b9d859" />|<img width="724" height="330" alt="image" src="https://github.com/user-attachments/assets/299b8afc-4bfa-496b-aed9-b824dc837edb" />|
> feat(mapper): add text about access change when moving to another folder

- tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/ColumnModal.tsx
- tavla/src/Board/scenarios/Table/components/Platform.tsx
- tavla/src/Shared/types/column.ts
Endret fra Plf tilbake til Plattform for å gjøre lettere å lese. 
|  <img width="783" height="125" alt="Screenshot 2025-08-26 at 11 19 02" src="https://github.com/user-attachments/assets/e99751ff-27e5-45cc-be07-5e29b0ab83f4" /> | <img width="818" height="128" alt="Screenshot 2025-08-26 at 11 19 38" src="https://github.com/user-attachments/assets/f9bdac5a-f22e-4fbd-a4e9-7cffa4fabac2" /> |  
| <img width="1445" height="336" alt="Screenshot 2025-08-26 at 11 21 28" src="https://github.com/user-attachments/assets/671ef52b-7f88-4482-8948-a3090745fa9b" /> |  <img width="1433" height="257" alt="Screenshot 2025-08-26 at 11 20 49" src="https://github.com/user-attachments/assets/e51bf7f4-4453-499f-9be0-19be6d7d5bcf" /> |
> fix(): Change from Plf to Plattform

- tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/utils.ts
- tavla/src/Board/scenarios/Board/index.tsx
- tavla/src/Board/scenarios/Board/utils.ts
- tavla/src/Board/scenarios/CombinedTile/index.tsx
- tavla/src/Board/scenarios/QuayTile/index.tsx
- tavla/src/Board/scenarios/StopPlaceTile/index.tsx
- tavla/src/Board/scenarios/Table/components/Destination.tsx
- tavla/src/Board/scenarios/Table/components/Deviation.tsx
- tavla/src/Board/scenarios/Table/components/Situation/index.tsx
- tavla/src/Board/scenarios/Table/components/Situations.tsx
- tavla/src/Board/scenarios/Table/components/TileSituations.tsx
- tavla/src/Board/scenarios/Table/index.tsx
- tavla/src/Board/scenarios/Table/useCycler.ts
- tavla/src/Shared/components/Tile/index.tsx
| <img width="1673" height="1255" alt="image" src="https://github.com/user-attachments/assets/eb69f6fa-8717-4851-b8c3-8915b4b70e15" /> | <img width="1673" height="1255" alt="image" src="https://github.com/user-attachments/assets/2b399370-d1a7-4e6b-b05a-fe47ac4449e5" /> |
|<img width="1673" height="1255" alt="image" src="https://github.com/user-attachments/assets/12bb35e9-c3c0-4422-83e2-11ad908d0334" />|<img width="1673" height="1255" alt="image" src="https://github.com/user-attachments/assets/fda0e1e2-2db0-4099-8e5d-7f77af38108e" />|
|<img width="1673" height="1255" alt="image" src="https://github.com/user-attachments/assets/9d3bd508-4f5b-48fd-9dc6-a18f256bff77" />|<img width="1673" height="1255" alt="image" …
> feat(tavla): implement new situation design

- tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/TransportPaletteSelect.tsx
- tavla/app/globals.css
- tavla/src/Shared/types/settings.ts
Flere har etterspurt muligheten til å ha grønne busser som et valg
| <img width="452" height="318" alt="Screenshot 2025-09-01 at 08 53 30" src="https://github.com/user-attachments/assets/3bd9e904-2556-4e27-975f-d953517fe654" /> | <img width="472" height="470" alt="Screenshot 2025-09-01 at 08 51 12" src="https://github.com/user-attachments/assets/b8685ebf-8e65-4af0-8555-4632394557bb" /> |
> feat(rediger): add green busses

- tavla/src/Board/components/BaseTile/index.tsx
- tavla/src/Board/hooks/useTileData.ts
- tavla/src/Board/scenarios/Board/utils.ts
- tavla/src/Board/scenarios/CombinedTile/index.tsx
- tavla/src/Board/scenarios/QuayTile/index.tsx
- tavla/src/Board/scenarios/StopPlaceTile/index.tsx
Tile komponentene har mye duplikasjon av kode og mye ansvar.
- Lage en samling for query av data i en egen hook
- Lage en Base-Tile som unngår duplikasjon av kode
> 🧹 kombinere Tile-Komponenter
