CODEOWNERS

1 review is required for merging into master. The users listed in CODEOWNERS will be set as reviewers by default on new pull requests.
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
https://help.github.com/articles/about-codeowners/

Add CODEOWNERS file for adding default reviewers

---

.stylelintrc
package-lock.json
package.json
src/components/bikeTable/styles.scss
src/components/checkbox/styles.scss
src/components/departureTiles/styles.scss
src/components/header/styles.css
src/components/searchPanel/styles.scss
src/containers/adminPage/styles.scss
src/containers/departureBoard/styles.scss
src/containers/landingPage/styles.scss
src/main.scss

Adds style linting with standard config (https://github.com/stylelint/stylelint-config-standard) 
New NPM scripts:
```
npm run eslint // run ESLint javascript linting
npm run stylelint // run Stylelint CSS linting
npm run lint // run both!
```

Add Stylelint with standard config

---

src/components/bikeTable/styles.scss
src/components/departureTiles/styles.scss

A quickfix improves the issue in #55 a little.

Hide overflowing departures

---

src/containers/departureBoard/DepartureBoard.jsx
src/utils.js

We like to handle all transportMode=coach as Bus. It will always have same icons and filter.
Therefore we filter out coach from api-result and replace it with type=bus.

DK-2398: Replaced transportMode=coach with transportMode='bus'

---

src/components/departureTiles/DepartureTile.jsx
src/containers/adminPage/SelectionPanel.jsx
src/utils.js

Still compatible with older setups.
--
Dersom man filtrerte vekk f.eks. trikk 11 Majorstuen frå Biermanns gate, ville denne forsvinne også frå Torshov, sjølv om man ville vise den der. Linjer vart filtrert globalt, mens no blir det filtrert per stasjon.

Filter lines per station, not globally

---

src/containers/Admin/DashboardPanel/index.tsx
src/containers/App.tsx
src/dashboards/Chrono/BikeTile/index.tsx
src/dashboards/Chrono/BikeTile/styles.scss
src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Chrono/DepartureTile/styles.scss
src/dashboards/Chrono/components/Tile/index.tsx
src/dashboards/Chrono/components/Tile/styles.scss
src/dashboards/Chrono/components/TileRow/index.tsx
src/dashboards/Chrono/components/TileRow/styles.scss
src/dashboards/Chrono/index.tsx
src/dashboards/Chrono/styles.scss
src/dashboards/Entur/BikeTile/index.tsx
src/dashboards/Entur/DepartureTile/index.tsx
src/utils.ts

Nytt, valgbar "Kronologisk visning", der alle enkeltavgangar får si eiga rad.

Kronologisk visningstype

---

src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Chrono/components/Tile/styles.scss
src/dashboards/Chrono/components/TileRow/index.tsx
src/dashboards/Chrono/components/TileRow/styles.scss
src/dashboards/Compact/BikeTile/index.tsx
src/dashboards/Compact/DepartureTile/index.tsx
src/dashboards/Compact/components/TileRow/index.tsx
src/dashboards/Compact/components/TileRow/styles.scss
src/logic/useStopPlacesWithDepartures.ts
src/types.ts
src/utils.tsx

Show icons for situations and cancellations, in **compact** and **chronological** views:
**Compact:**
**Chronological:**

ETU-1257: Show icons for situations and cancellations

---

src/dashboards/Compact/index.tsx

When there is stop places without departures in the compact dashboard, an empty column is assigned that takes up space to the right. 
This is fixed when empty bus stops are filtered out before `numberOfStopPlaces` is calculated.
We used "Dronningens gate, Trondheim" as the test case, where there are two empty bus stops.
https://tavla.entur.no/dashboard/@63-431938,10-393419/

Remove empty columns on dashboard

---

.circleci/config.yml
package.json

Since we're now on CircleCI's newer Node image we can (hopefully) use 'npm ci'. It didn't work on Node 8 because CircleCI used an old version of npm. Caching is not necessary with 'npm ci' because it deletes node_modules anyways.

Use 'npm ci' in CircleCI, remove caching of node_modules

---

.env.prod
.env.staging
.gitignore
CONTRIBUTING.md
package.json
src/auth.ts
src/containers/App.tsx
src/firebase-init.ts
webpack.config.js

Firebase tilbyr "SDK auto-configuration": https://firebase.google.com/docs/hosting/reserved-urls#sdk_auto-configuration
Det fungerer berre lokalt når man kjører `firebase serve`. `firebase serve` er fint for å teste produksjons-bygg før deploy, men dårlig for lokal utvikling, for man får ikkje hot-reloading osv. som webpack tilbyr.
Derfor har eg lagt til bruk av `.env.local` som man må ha for å bruke `npm start` (webpack-dev-server). Man kan putte FIREBASE_CONFIG i .env.local. Då kan me bruke configen frå miljøvariabelen i staden for å bruke auto-configen. `.env.local` blir ikkje sjekka inn i git, så eg har prøvd å forklare i CONTRIBUTE.md korleis man lagar denne fila.
Ved bruk av auto-config skjer initialisering av Firebase asynkront. Det kompliserer ting litt, for me må passe på at me …

Use Firebase autoconfig

---

src/containers/DashboardWrapper/styles.scss

For skjermer mindre enn 700px, bør paddingen rundt `DashboardWrapper` være mindre.
Før:
Etter:

Update dashboard-wrapper padding on smaller screens

---

src/containers/DashboardWrapper/Footer/styles.scss

Flyttet tilbakepila til venstre for å være på linje med resten av brukergrensesnittet, og gjort den samme høyde som knappene til høyre.
Før:
Etter:

Fix alignment of back arrow on dashboard

---

src/dashboards/Compact/styles.scss

Håndtakene for størrelsejustering av kolonner har blitt gjort tydligere, og kun synlige når musepekeren er tilstede. Elementet animeres inn ved mouseover.
Også lagt til en gradient på bunnen av kolonner.
Fixes atb-as/tavla#11, fixes atb-as/tavla#10

Oppdater størrelsejustering av kolonner

---

src/logic/useBikeRentalStations.ts

Forslag om å sortere bysykler på avstand fra `position`.
Det ser ut som at Entur SDK gir stoppesteder sortert på avstand, så gitt at det er riktig observert, kan man bare fjerne sorteringsfunksjonen i `fetchBikeRentalStations`.
Fixes atb-as/tavla#21

Remove alphabetical sorting of bike rental stations

---

src/dashboards/Compact/styles.scss

Fixes atb-as/tavla#24 
Liten bug når gradienten rendres fra blå til transparent i Safari.

Fix tile gradient rendering on safari

---

src/containers/DashboardWrapper/styles.scss
src/dashboards/Compact/styles.scss

Using Safari or Chrome on macOS with scroll bars enabled ("Always" in System Preferences > General) looks like this:
Before:
After:
Fixes atb-as/tavla#25

Remove unnecessary scrollbars

---

src/dashboards/Compact/styles.scss

Musepekeren til størrelsejusterings-håndtaket bør peke både opp og ned (nord og sør, ikke bare sør).

Update resizable-handle cursor to north-south

---

firestore.rules

`write` er ikke tillatt, da sletting ikke skal skje.

Noen grunnleggende regler for Firestore

---

src/services/firebase.ts
src/settings/FirestoreStorage.ts
src/settings/index.ts

Legger til støtte for automatisk synkronisering av settings fra Firebase. Det vil si at hvis noen endrer innstillingene for en ID-basert tavle, vil alle instanser av den tavla automatisk laste inn de nye innstillingene, uten refresh.
Legger også til en make-shift håndtering av ikkeeksisterende ID-er: redirecting til startsiden hvis det ikke finnes noe for den ID-en. Bedre enn det er nå, men vi må nok ta en overhaling av hvordan rutinga fungerer.

Listen for changes to settings in Firebase

---

src/auth.ts
src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Chrono/components/TileRow/index.tsx
src/dashboards/Compact/components/TileRow/index.tsx
src/utils.tsx

TypeScript throws errors if `strictNullChecks: true`.

Fix some null checks

---

src/containers/DashboardWrapper/Footer/index.tsx
src/containers/LandingPage/SearchPanel/index.tsx
src/dashboards/Timeline/index.tsx
src/service.ts
src/settings/UrlStorage.ts
src/utils.tsx
tsconfig.json
types/universal-ga/index.d.ts

Å sette `strict: true` er det samme som å aktivere følgande under-flagg. Så eg tenkte å ta eitt og eitt!

Activate noImplicitAny, fix errors

---

src/containers/Admin/index.tsx

Det kom eit par feil ved at `distance` var av typen `number | undefined`. No er den alltid `number`.

Use DEFAULT_DISTANCE so that `distance` cannot be undefined in Admin

---

CONTRIBUTING.md
src/auth.ts
src/containers/App.tsx
src/firebase-init.ts
src/settings/index.ts

Dersom man bruker Firebase Hosting kan man droppe config og la Firebase ordne det automatisk. Men det funker ikkje så bra lokalt. No som me uansett har configen for begge miljøa i repoet, kan me like godt forenkle litt og droppe støtten for denne automatiske konfigureringa.

Remove automatic config - rely on env variable

---

src/containers/Admin/LogoTab/index.tsx
src/containers/DashboardWrapper/BottomMenu/index.tsx
src/settings/index.ts

Legacy tavler cannot see lock and log in buttons on menu, and is notified to upgrade to new tavle on the logo page in admin

Fixed buttons and tabs for legacy tavler

---

src/logic/usePermittedTavle.tsx
src/routers/PrivateRoute/index.tsx

Å sjekke etter lovlig tilgang til Admin burde nå være ganske usynlig.

Fjernet feilmeldingsside idet Admin laster opp og permission er `null`

---

src/containers/Admin/DashboardPickerTab/index.tsx
src/containers/Admin/EditTab/StopPlacePanel/PanelRow/index.tsx
src/containers/Admin/EditTab/StopPlacePanel/index.tsx
src/containers/Admin/EditTab/index.tsx
src/containers/Admin/ThemeTab/index.tsx
src/containers/Admin/index.tsx
src/containers/App.tsx
src/containers/DashboardWrapper/BottomMenu/index.tsx
src/containers/DashboardWrapper/UpgradeTavlaBanner/index.tsx
src/containers/Error/index.tsx
src/containers/ThemeWrapper/ThemeContrastWrapper.tsx
src/containers/ThemeWrapper/ThemeProvider.tsx
src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Compact/DepartureTile/index.tsx
src/dashboards/Compact/index.tsx
src/logic/useNearestPlaces.ts
src/logic/useStopPlacesWithDepartures.ts

Fikser en haug med warnings i konsollen (alle unntatt de som angår `any`-typings). Hovedsaklig imports som ikke blir brukt og manglende return types.

Remove unused imports

---

src/containers/Admin/FloatingButtons/styles.scss

Ser at teksten i `FloatingButtons` er litt dårlig alignet i Safari. Å sette en line-height fikser problemet. Har ingen god forklaring på hvorfor 0.25rem var det som passet best, men det er "midt på" i Safari, og det påvirker ikke andre nettlesere.

Fix floating buttons for Safari

---

src/dashboards/Compact/styles.scss

- Ser at gradienten på bunnen av tiles har forsvunnet fordi man ikke kan sette opacity på CSS variabler. Løste dette ved å bruke en maske istedet. Det ser ut som om det er _grei_ støtte for `-webkit-mask-image` i browsere https://caniuse.com/#search=mask-image
- Oppdaterte også fargen på `.react-resizable-handle`
Fixes atb-as/tavla#31

Fix tile gradient

---

src/containers/DashboardWrapper/index.tsx

When the byline is the first element of the wrapper, it breaks the [`.bottom-menu:first-child` rule in BottomMenu/styles.scss](https://github.com/entur/tavla/blob/master/src/containers/DashboardWrapper/BottomMenu/styles.scss#L19). This means the left padding looks slightly off when byline is visible.

Fix BottomMenu padding issue on dashboard

---

src/containers/DashboardWrapper/index.tsx

initialLoading was never set to false and it turns out we don't need it at all.
Fixes #251

Fix showing departures when city bikes disabled

---

src/settings/index.ts

When editing some setting on the admin page, the new settings is persisted to Firestore.
When something is edited on Firestore, this triggers a new onSnapshot call.
The new snapshot call sets a new Settings object, although nothing is really changed.
This triggers a bunch of hooks that fetches new data.
This PR fixes this by ignoring the onSnapshot setter when on admin

Reduce a lot of unnecessary calls to JourneyPlanner when on admin

---

src/containers/Admin/EditTab/ZoomEditor/index.tsx
src/containers/Admin/EditTab/index.tsx
src/logic/useScooters.ts

`getScooters` blei kalt kvar gong `settings` endra seg. Det inkluderte altså `zoom`. I tillegg var det ikkje debounce på zoom-slider, så det blei fyrt av veldig mange kall om man dro i den. 
Har lagt på 200 ms debounce på zoom-kall, og getScooters blir berre kalt dersom relevante settings endrar seg.

Don't call getScooters if only zoom changed

---

src/dashboards/Chrono/styles.scss

There was bug in the chrono view where the handle was gone, and trying to drag one departure card vertically would increase the height of all the departure cards. There was some css that probably got lost in some merge that I've put back so that everything is working as expected.

Fix a bug in the handle of the chrono view

---

src/dashboards/Timeline/styles.scss

In a previous PR some .react-grid-layout css was added to the timeline stylesheet. There are no react grid items in the timeline view, so all happened was that the fade on the bottom of the map tile was reintroduced. This PR removes that code.

Remove some code that reintroduces the fade on the map tile in compact view.

---

package-lock.json
package.json
src/assets/icons/scooterOperatorLogo.tsx
src/components/Map/ScooterMarkerTag/index.tsx
src/components/Map/ScooterMarkerTag/styles.scss
src/components/Map/index.tsx
src/dashboards/Map/index.tsx
tsconfig.json

Added clustering to the map component through the useSupercluster-hook. The casting is because the useSupercluster-hook expects that exact type at those fields. 
It can be tuned by passing an options object. Passing Radius you control how for from coordinates it considers a point overlapping. For example typescript infers `type: 'Feature' as 'Feature',` to be of the type string, but the useSupercluster expects it to be `'Feature'` and only feature.

Added clustering to map component

---

src/containers/Admin/EditTab/BikeSearch/index.tsx
src/containers/Admin/EditTab/StopPlaceSearch/index.tsx
src/containers/LandingPage/SearchPanel/index.tsx

Når autosuggest er åpen bør den default velge første element i lista, slik at man bare kan trykke enter for å velge stedet.
Er støtte for dette fra designsystemet https://design.entur.org/komponenter/skjemaelementer/dropdown

Default til første element i autosuggest

---

src/components/Map/index.tsx

`getMap()` was null in certain states, which cased `getBounds()` to crash

Safari bugfix

---

src/containers/Admin/styles.scss

In the admin panel when switching tabs or selecting colors, a blue outline will be shown around the div in focus. This did not look so nice, so we removed the outlines seen in these screenshots:
Before:
After:

removed outline on focus for some divs in the admin panel

---

src/containers/Admin/EditTab/index.tsx
src/containers/Admin/EditTab/styles.scss
src/dashboards/Compact/MapTile/index.tsx
src/dashboards/Compact/index.tsx
src/settings/FirestoreStorage.ts
src/settings/index.ts

Map is now visible in compact mode independently of whether there are any scooters or not/if scooters are activated. Can now also show only bikes, only scooters and/or only stop places. Map has its own box in the admin panel, and can be toggled on/off.

Make own map box with toggle

---

src/dashboards/Compact/index.tsx

Make is possible to scroll on mobile by making the tiles on dashboard not draggable and not resizable while on mobile. It is still possible to drag and resize on web.

make tiles undraggable on mobile on compact dashboard

---

src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Chrono/components/Tile/styles.scss
src/dashboards/Chrono/index.tsx
src/dashboards/Compact/index.tsx

Updated chrono view to have a maximum amount of cards shown per row, in the same way it is done for compact view.
Before:
After:

Updated chronological view to match the new compact view

---

src/containers/Admin/EditTab/index.tsx
src/containers/Admin/EditTab/styles.scss
src/dashboards/Compact/index.tsx

Bug fix 1: Width of map and scooter tiles on mobile are now the same width as the rest of the tiles.
Bug fix 2: Map tile was rendered even though map wasn't active. Tile is now only rendered if there is any data and map is active.

Fixed bugs: width of tiles on mobile and map bug

---

src/components/Map/index.tsx
src/dashboards/Compact/styles.scss

**In compact mode on mobile**
Bug fix 1: Can now scroll on map as well as the other tiles. 
Bug fix 2: Edit-menu does not cover the last grid item in compact mode.

Map and menu bugs on mobile

---

manifest.json
src/index.html

Small fix for enabling a custom icon when adding website to homescreen on iOS.

add-to-homescreen icon for ios

---

src/dashboards/Compact/index.tsx
src/dashboards/Compact/styles.scss

When user is on a mobile device, the resize handles are removed from the tiles in the compact view. The functionality for actually resizing them are already disabled.
Also reduced the margin of the last grid item in compact mode from 7rem>5rem.

Fix resize handle mobile

---

src/containers/Admin/styles.scss

Change min-width on tab in tab-panel on small screens, s.t all text is visable.
Make fading on the right end of tab-list on mobile screens.
Before: left, after: right

Fix visual expression on tab-list on mobile

---

src/containers/Admin/EditTab/BikeSearch/index.tsx
src/containers/Admin/EditTab/ScooterPanel/index.tsx
src/containers/Admin/EditTab/ScooterPanel/styles.scss
src/containers/Admin/EditTab/StopPlaceSearch/index.tsx
src/containers/Admin/EditTab/ZoomEditor/index.tsx
src/containers/Admin/EditTab/ZoomEditor/styles.scss
src/containers/Admin/EditTab/index.tsx
src/containers/Admin/EditTab/styles.scss
src/containers/Admin/index.tsx
src/containers/Admin/styles.scss
src/containers/LandingPage/index.tsx
src/variables.scss

Updated the underlaying grid layout to the same kind used on Compact and Chrono view, in addition to styling the overall tile looks to match the new design sketches for the EditTab Panel.
The "Kollektiv" and "Bysykkel" tabs are still untouched, and do not match the new design yet.
Before:
After:

Updated EditTab's tiles to match the new design sketches

---

src/containers/Admin/EditTab/ScooterPanel/styles.scss
src/containers/Admin/EditTab/styles.scss
src/containers/Admin/styles.scss

Updated the styling for parts of the admin panel in order to make the filter chips and navbar colors handle contrast mode nicely again.
Before:
After:

fixed bugs which led to inconsistent color themes for admin panel

---

src/containers/App.tsx
src/dashboards/Chrono/index.tsx
src/dashboards/Compact/index.tsx
src/utils.tsx

The tile order is now stored in localStorage, but is set to default if no local ordering is found or if there is a mismatch between the contents of the stored order compared to the default one.

tileOrder is stored in localStorage

---

src/dashboards/Compact/components/TileRow/PlatformInfo/styles.scss

Platform-info on mobile did note scale before this change, se pictures below
Before:
After:

Fix font style on platform-info in compact view

---

src/dashboards/BusStop/DepartureTile/index.tsx
src/dashboards/BusStop/DepartureTile/styles.scss
src/dashboards/BusStop/index.tsx
src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Chrono/components/Tile/index.tsx
src/dashboards/Chrono/components/Tile/styles.scss
src/dashboards/Chrono/index.tsx
src/dashboards/Compact/components/Tile/index.tsx

Add walking distance in meters and minutes in chrono view. This is equivalent to what previously done in compact view.

Add walking distance (in meters and minutes) in chrono and busStop view

---

src/containers/Admin/EditTab/ToggleDetailsPanel/index.tsx
src/containers/Admin/EditTab/ToggleDetailsPanel/styles.scss
src/dashboards/BusStop/DepartureTile/index.tsx
src/dashboards/BusStop/DepartureTile/styles.scss
src/dashboards/Chrono/index.tsx
src/dashboards/Compact/DepartureTile/index.tsx
src/dashboards/Compact/components/TileRow/index.tsx
src/settings/index.ts

Added a toggle for track info in the admin panel, as well as track info now being visible in view "busstop".

Toggle for track info and track info in "busstop"

---

src/dashboards/Compact/components/TileRow/styles.scss
src/dashboards/Compact/index.tsx
src/dashboards/Compact/styles.scss

Updated the styling for compact view tiles to match the new design sheets in Figma.
Before:
After:

Updated the styling of compact view to match new design sheets

---

src/dashboards/Compact/BikeTile/index.tsx
src/dashboards/Compact/DepartureTile/index.tsx

The new design sheets has colorful icons in the header for tiles in compact view.
Before:
After:

updated transport icons to have colors

---

src/dashboards/BusStop/DepartureTile/index.tsx
src/dashboards/BusStop/MapTile/styles.scss
src/dashboards/BusStop/index.tsx
src/dashboards/BusStop/styles.scss
src/dashboards/Chrono/BikeTile/index.tsx
src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Chrono/index.tsx
src/dashboards/Chrono/styles.scss
src/dashboards/Map/DepartureTag/styles.scss
src/dashboards/Timeline/styles.scss

Added border radius in all views, in addition to some colorful transport mode icons where suitable.
Screenshots:

Border radius for tiles in all views

---

src/logic/useWalkInfo.ts

As in picture below, if position is _Jernbanetorget_ **and** stop place is _Jernbanetorget_, walking distance in minutes was previously set to NaN and meter set to zero.
Before:
After:

Fix bug when distance from stop place is zero

---

src/dashboards/BusStop/DepartureTile/styles.scss
src/dashboards/Chrono/components/Tile/styles.scss
src/dashboards/Compact/components/Tile/styles.scss

Change font colour on walking distance from purple to white, so that it is easier to separate this information from information on the next row. This is especially prominent in BusStop view, se pictures below.
Before:
After:

Change font colour on walkingDistance

---

src/dashboards/Chrono/DepartureTile/index.tsx
src/dashboards/Chrono/components/Tile/styles.scss
src/dashboards/Chrono/components/TileRows/styles.scss

Removed a bit of padding, scaled down transport icons.

tiles looks better on mobile devices

---

src/dashboards/Chrono/components/Tile/styles.scss

Chrono tiles had a bug where the user could scroll horizontally inside the tile.

fixed horizontal scroll in tile bug

---

src/dashboards/Chrono/BikeTile/index.tsx
src/dashboards/Chrono/BikeTile/styles.scss
src/dashboards/Chrono/components/TileRows/index.tsx
src/dashboards/Chrono/components/TileRows/styles.scss
src/dashboards/Compact/components/TileRow/styles.scss

Add walking distance (in meter and minutes) for each bike station in the bikeTile in Chrono view.
Before:
After:

Add walking distance on bike tile in chrono view

---

src/containers/Admin/EditTab/index.tsx

Upon entering the admin panel, a tooltip is shown underneath the distance edit panel. Saves to local storage the first time it is shown.

Tooltip added to distance edit field in admin panel

---

package-lock.json
package.json
src/containers/App.tsx
src/containers/styles.scss
src/dashboards/Compact/index.tsx
types/react-ios-pwa-prompt/index.d.ts

On third visit on Tavla add-to-homescreen-prompt is shown on iOS. It's only shown once.
`"react-ios-pwa-prompt": "chrisdancee/react-ios-pwa-prompt#pull/71/head"` was needed because the original npm package had some issues with CaseSensitivePathsPlugin. This PR fixed the problem, but it was not merged when we needed it: https://github.com/chrisdancee/react-ios-pwa-prompt/pull/71

Pwa onboarding

---

src/dashboards/Chrono/BikeTile/index.tsx
src/dashboards/Chrono/components/TileRow/index.tsx
src/dashboards/Chrono/components/TileRow/styles.scss

Add a tileRow component in Chrono view equivalent to the tileRow component in Compact view. Previously, the walkingDistance in bikeTile in Chrono view was using tileRow in Compact view, which we want to avoid.

Add tileRow to Chrono view

---

src/containers/Admin/EditTab/index.tsx

Input field for editing distance in admin panel now reacts to every digit, without having to push "enter" for the distance to be set correctly.

Fixed input-bug

---

src/dashboards/Timeline/index.tsx
src/dashboards/Timeline/styles.scss

Add walking distance (in minutes and meters) in timeline view. The walking information will be in the top right corner on each tile when possible. But when there's little space, the information is wrapped on two lines. (The latter is shown in the photo on small screen below)
It's possible to toggle of walking information if not of interest. 
Before:
After (on desktop):
After (on small screens and mobile):

Add walking distance in timeline view

---

src/components/Header/DashboardHeader.tsx

Remove "Finn din tavle på entur.no eller i entur-appen" on mobile.
This info takes up a lot of space on the screen on mobile, and doesn't add that much value.
Before:
After:

Remove "Finn din tavle.." on mobile

---

src/containers/App.tsx

Changed path to icons from absolute to relative, because the browsers treats these links as relative anyways and the hostname ended up being added twice to the URLs. 
Example:
`tavla.staging.entur.no/tavla.staging.entur.no/images/logo/logo-192x192.png`
is now
`tavla.staging.entur.no/images/logo/logo-192x192.png`

fixed double hostname for src to icons in manifest generation

---

src/containers/Admin/EditTab/StopPlacePanel/styles.scss

Wrap switches below stop place name if no space

---

src/dashboards/BusStop/DepartureTile/index.tsx
src/dashboards/BusStop/components/Tile/index.tsx
src/dashboards/BusStop/components/Tile/styles.scss
src/dashboards/BusStop/components/TileRows/index.tsx
src/dashboards/BusStop/components/TileRows/styles.scss
src/dashboards/BusStop/index.tsx
src/dashboards/BusStop/styles.scss
src/dashboards/Chrono/styles.scss

Busstop now got similar grid, tile and tilerow system like compact and chrono. Layout improvements on mobile and desktop. Longpress functionality added.
Map is now at the bottom of the for both desktop and mobile. Can possibly change this at a later time, if having the map to the right of the first departure tile would be better.

Restructuring of busstop, now with longpress and new grid

---

src/containers/Admin/EditTab/index.tsx
src/containers/Admin/EditTab/styles.scss
src/dashboards/Chrono/styles.scss
src/dashboards/Compact/styles.scss

The margin added between tiles on the grid also puts margin on
the top of the tiles, making the margin 2 rems too big above them.
Also, the header in Admin Edit Tab was too far to the left.
BEFORE:
AFTER:

Reduce margin above tiles, add left margin to edit tab header

---

src/dashboards/Chrono/components/TileRows/index.tsx
src/dashboards/Chrono/components/TileRows/styles.scss

Updated styling for TileRows in Chrono, with improvements in vertical alignment and font-sizing.
Before/after:

tweaked styling for tilerows in chrono view

---

src/dashboards/BusStop/MapTile/index.tsx

Difficult to scroll in busStop view on desktop when zoom in map is activated.

Disable zoom in map in busStop view on desktop

---

src/containers/App.tsx

The PWA prompt is now only shown on iOS devices, because Chrome on Android is promoting "Add to Home Screen" automatically if a valid manifest and service worker is provided with a website.
Also, added a note that the user has to be in Safari to create a PWA.
Before:
After:

pwa is now only shown on iOS

---

src/containers/Admin/EditTab/index.tsx

Dynamic height of tiles in edit-panel. Scaling factor is set based on the content of the tile.
Before:
After:

Dynamic tile height in edit-tab

---

src/containers/Admin/EditTab/index.tsx

Height in large mode on smaller screens were a bit too short, so I adjusted the row height a bit to fit most screens perfectly.

added a bit more padding to avoid scroll section in busstop tile

---

src/settings/UrlStorage.ts

The map is hidden by default and the map is the only place to see where the scooters are, so it makes more sense that scooters also are defaulted to hidden.

Scooters are hidden by default

---

src/containers/Admin/EditTab/StopPlacePanel/index.tsx

If all transport modes for a stop place are toggled off, this deselects the checkbox for the stop place as well, and vice versa.

EditTab toggle improvements

---

src/containers/Admin/EditTab/StopPlacePanel/styles.scss

Font size were changing when a stop was toggled, this is now fixed.
Before | After:

Fixed font size variations in StopPlacePanel

---

src/dashboards/Chrono/components/Tile/styles.scss

In dark mode the color in header cell in chrono view was of wrong color.
Before:
After:

Fix font color in header cell in chrono view

---

src/containers/MyBoards/BoardCard/index.tsx
src/services/firebase.ts
src/settings/FirestoreStorage.ts
src/settings/index.ts

Alsorefactor previous function to be more descriptive. Update function-names in relevant files.
Introduserer en ny funksjon som oppdaterer flere felter på en gang. Hensikten er å ikke trigge unødvendig mange update-jobber. I tillegg virket det litt rart at man skulle gjøre et nytt kall for hvert felt man ønsker å oppdatere hvis man egentlig bare ville oppdatere x antall felter samtidig. Vurderte å endre på den eksisterende funksjonen, men den brukes også andre steder, så løsningen var å lage en egen funksjon for å oppdatere flere på en gang.
Sjekket loggene i firebase konsoll, og det fungerer tilsynelatende som tiltenkt ved at antall ganger `deleteImageFromStorage` blir kalt reduseres betraktelig. Bildet under viser loggene fra en opplastning og sletting (pluss et separat kall nederst).

Add function to update multiple fields at once

---

package-lock.json
package.json

Fjernet den pakken i forrige PR da jeg ikke så noe bruk for den i prosjektet. Det var ganske middels minus smart da det er den som lar prosjektet bli deployet automatisk fra circle-ci. I det minste har vi funnet ut hva den brukes til ✌️

Putte tilbake firebase-tools i dev dependencies 

---

src/assets/icons/scooterOperatorLogo.tsx
src/assets/logos/Bolt.svg
src/constants.ts

🛴Bolt scooters added to the application🛴
The only changes are that the Bolt icon is added to /assets and included in the logic of `ScooterOperatorLogo` component. The operator ID is introduced in the global constant (`ALL_ACTIVE_OPERATOR_IDS`) defining which mobility operators to use from the mobility API.
Before | After
--- | ---

Add Bolt scooters

---

src/utils.tsx

Utvider nøklene for avganger til å være en kombinasjon av ID hentet gjennom entur/sdk og planlagt avgangstid.

Gi unike nøkler til alle avganger

---

src/components/LoginModal/EmailLogin/index.tsx

🔐 
Tilbakemeldingene til brukeren ved login burde være generelle slik at man ikke kan gjette seg frem til brukernavn/e-poster. 
Med denne oppdateringen vil tilbakemeldingen se lik ut ved feil brukernavn eller feil passord.
Før | etter
--- | ---

Generalisert tilbakemelding ved feil brukernavn eller passord

---

src/containers/MyBoards/BoardCard/index.tsx
src/containers/MyBoards/BoardCard/styles.scss

Denne PRen, i motsetning til PR #451, fikser feilen ved hjelp av css. Hovedproblemet lå i at posisjonell styling på knappen `OverflowMenu` ikke medførte at menyen fulgte med. Innholdet ble derfor lagt i parent-divs og disse er satt til å plasseres med flexbox. 
Før | Etter
:----------|----------:

Fix visual error on overflow menu in MyBoards

---

src/dashboards/BusStop/index.tsx

Slik jeg har skjønt det fører den if-en fra 118 til 123 til at `stopPlacesWithDepartures` ble forskjellig på hver render. Det førte til at loopen ble uendelig om ikke ifen 152 til 154 kicket inn og hindret at noe state ble satt i useeffecten. Endret derfor til å kjøre filtreringen inni useeffecten. Jeg gjorde noen andre refactoringer her som jeg synes ga mening. Åpen for innspill om det er noe en er uenig i.

Fikse uendelig loop i useeffekten til holdeplass-view

---

webpack.config.js

God mandag. Slik det sto ble staging alltid valgt, da env som passes inn nå er et objekt. Med andre ord har egentlig ikke prod vært oppe og gått i helgen. Til og med noen som har laget issue på det.  Ble introdusert i forbindelse med oppdateringen av webpack, så min feil. Endringene under burde fikse det.
Commit 2 og 3 skal fikse henholdsvis feil i fontloadingen og at webpack bruker 'development' som mode i alle tilfeller.

Set correct .env variables

---

package-lock.json
package.json
src/containers/Admin/EditTab/index.tsx
src/containers/DashboardWrapper/BottomMenu/index.tsx
src/containers/LandingPage/SearchPanel/index.tsx
src/containers/MineTavlerModal/index.tsx
src/logic/useBikeRentalStations.ts
src/logic/useStopPlacesWithDepartures.ts

Denne er bak i køen for #457 da den har med de samme commitsene. 
Her oppgraderes ts og koden refaktoreres til å håndtere feil ts påpeker i den gamle koden. Det er også med en fiks for logikken bak å kunne ha samme stoppested to ganger. Slik koden var ble den unike id-en som ble satt for to entries av samme stoppesteder borte i filtreringsprosessen når man henter stoppesteder med avganger. Dette skal nå ha blitt riktig med siste commit på denne PR-en.

Upgrade typescript

---

src/dashboards/Compact/components/TileRow/styles.scss

Denne PR'en muliggjør å scrolle horisontalt for å se senere avgangstider i Kompakt visning. Dette skal funke på både desktop og mobil.
Synlig scrollbar er fjernet, mye fordi den overlappet en del med avgangstidene.

Horisontal scrolling av avgangstider

---

package-lock.json
package.json
src/auth.ts
src/components/LoginModal/EmailLogin/index.tsx
src/components/LoginModal/EmailSent/index.tsx
src/components/LoginModal/ResetPassword/index.tsx
src/components/LoginModal/Signup/index.tsx
src/components/LoginModal/index.tsx
src/containers/Admin/LogoTab/index.tsx
src/containers/Admin/NameTab/index.tsx
src/containers/DashboardWrapper/BottomMenu/index.tsx
src/containers/Error/ErrorPages.tsx
src/containers/MyBoards/BoardCard/index.tsx
src/containers/MyBoards/index.tsx
src/containers/Navbar/index.tsx
src/firebase-init.ts
src/services/firebase.ts
src/settings/FirestoreStorage.ts
src/settings/index.ts

Tjena! 
Her skjer det litt av hvert. Hovefordelen med å oppgradere til firebase 9 skal være at det lar webpack (evt andre bundlere) droppe å ta med deler av koden som ikke brukes, som igjen vil gjøre appen vår mindre. Google tree-shaking, det gjorde i alle fall jeg. Rent praktisk vil det si at man i stedet for å importere firebase og dotte seg inn på hva enn man skal ha bare importerer de respektive funskjonene man trenger.
F. eks:
```
firebase.auth().sendPasswordResetEmail(inputs.email, actionCodeSettings)
```
Bir til 
```
sendPasswordResetEmail(auth, inputs.email, actionCodeSettings)
```
Hvor auth er instansen som blir initialisert i `firebase-init.ts`
Hvor stor forskjell utgjør dette? 
Den nette sum av 32Kb aka at appen vår blir ca 1% mindre. Hvor imponerende dette er kan diskuteres, …

Upgrade firebase

---

firebase.json

Vi fant ut tidligere i dag at prod ikke funket på mobil og klødd oss i hodet et par timer nå. 
Slik vi har skjønt det sjekker firebase hva slags device man er på, og firebase/auth henter script fra apis.google.com om man er på mobil. Denne er ikke whitelistet i content security policy headeren, og blir følgelig ikke kjørt. Før omskrivingen til firebase 9 fikk man samme feilen, men appen fungerte tilsynelatende ok. Etter omskrivingen gjør den ikke det. 
I staging finner man nå nyeste master som altså ikke funker, mens prod er rullet tilbake til før omskrivingen. En kan sjekke oppførselen mellom de to forskjellige der. Litt vanskelig å reprodusere dette lokalt, da alt fungerer fint der (mye mulig pga at localhost ikke setter noe content security policy header på responsen sin?). 
Forsøkt …

Whitelist apis.google.com in Content-Security-Policy header

---

src/containers/Admin/EditTab/index.tsx

Denne PRen fikser en feil i Admin-panelet der innstillings-tilen for vær og kart ikke har en satt startverdi når de hentes fra `settings`. Dette gjør at `form`-komponenten starter som _uncontrolled_ for så å bli _controlled_., noe React ikke liker (https://reactjs.org/docs/forms.html#controlled-components). Fiksen er så enkel som at showMap og showWeather settes default til `false` hvis verdien deres ikke er satt i `settings`.

Fiks «A component is changing an uncontrolled input of type checkbox to be controlled.»-feil i Admin-panelet

---

manifest.json
src/containers/App.tsx

Denne PRen oppdaterer noen verdier i Manifest-filene som lages som gjør at `src` for URL-en ikke lenger er invalid. Er en god del ekstra som kan og sikkert burde gjøres med PWA-delen av web appen, men det tar ikke denne PRen for seg

Fikse feilmelding om src URL in Manifest invalid 

---

manifest.json
src/containers/App.tsx

Denne tilbakerullingen gjøres da den originale PRen fikset en warning, men innførte en error. Denne feilen viste seg ikke før etter litt tid og var derfor ikke oppdaget da PRen ble laget. Ved å rulle tilbake blir det «mindre feil» og lettere å ta for seg dette problemet på nytt for hvem som helst ved en senere anledning. 
Reverts entur/tavla#468

Revert "Fikse feilmelding om src URL in Manifest invalid "

---

src/settings/index.ts

På grunn av oppgradering til firebase web version 9 har syntaks endret seg. Det å oppdatere `document.exists` til `.exists()` ble glemt og denne PRen legger det til. Fiksen gjør at man igjen bli auto-redirectet til startsiden hvis man skriver inn en utilgjengelig tavle-id i URL-feltet.
https://firebase.google.com/docs/firestore/query-data/get-data#web-version-9_1

Fix app not redirecting to root on page that doesnt exist

---

package-lock.json
package.json
src/components/Map/index.tsx
src/containers/Admin/EditTab/BikePanel/index.tsx
src/containers/Admin/EditTab/BikeSearch/index.tsx
src/containers/Admin/EditTab/StopPlaceSearch/index.tsx
src/containers/Admin/EditTab/index.tsx
src/containers/DashboardWrapper/index.tsx
src/dashboards/BusStop/MapTile/index.tsx
src/dashboards/Chrono/BikeTile/index.tsx
src/dashboards/Chrono/MapTile/index.tsx
src/dashboards/Compact/BikeTile/index.tsx
src/dashboards/Compact/MapTile/index.tsx
src/logic/useBikeRentalStations.ts
src/logic/useWalkInfoBike.ts
src/utils.tsx

🚲 
This PR migrates the part of the app considering bike stations to utilize the mobility v2 API using the entur SDK.
The reason why many files are changed is primarily due to the different format of the returned data using the type `Station`. The primary changes are in the custom hook `useBikeRentalStations()`, the majority of other file changes are adaptations to the new data format. 
The commit-log includes multiple Work-In-Progress commits (due to unknown migration scope) which may be squashed for prettier history. The drawback being a big bulk of changes with less traceability.
Changes:
* Rewrite useBikeRentalStation() to use mobility v2
* Using SDK-function getStations() to get nearby stations (within user selected radius)
* ❗Updated entur/sdk package: Using New SDK-function …

🚲 Bike station migration 🚲 : Moving to mobility API (v2)

---

src/containers/DashboardWrapper/BottomMenu/index.tsx

Denne PRen ser ut til å fikse at menyen ikke ble borte på scroll. Fiksen var i bunn og grunn å fjerne et krav om at `isWeb` måtte være sant, noe det ikke er på mobil. Jeg stusser litt over hvordan dette har fungert i det hele tatt noen ganger hvis dette faktisk er fiksen, så si gjerne fra hvis du ser noen potensielle bi-effekter av dette. 
Koden har også blitt litt refakturert for lesbarhet.
Tesstet på PC og mobil

Make functionality for hiding menu on scroll work as intended

---

functions/src/index.ts
src/containers/MyBoards/index.tsx
src/services/firebase.ts
src/settings/index.ts

Denne PRen forbedrer funksjonaliteten til egendefinert URL ved hjelp av to endringer:
- Det er nå mulig å sette tavla si til en URL som eksisterer, men er satt med `isScheduledForDelete === true`. Dette ga før en feilmelding om at denne url-en ikke er tilgjengelig. Når man gjør dette slettes den tavla som har url-en man ønsker med en gang før man lager en kopi av nåværende tavle med den nye urlen og setter gamle til `isScheduledForDelete = true`.
- I Mine tavler vises nå ikke lenger tavler som har `isScheduledForDelete === true` lenger. Dette gjør at man ikke lenger får duplikater i listen.

Improve custom url backend

---

src/components/WeatherTile/styles.scss

Realtime-ikonene havnet over værinformasjonen. Nå havner de under, som er ønsket oppførsel.

Increase z-index of weather-tile in map view

---

.github/dependabot.yml

Dependabot sjekker for ofte etter updates og lager for mange PRer, dette er en update for å prøve å minske det problemet

Update dependabot to try fix update interval

---

webpack.config.js

Leste meg litt opp på [webpack](https://webpack.js.org/configuration/devtool/ ) og fant ut at devtool ikke er noe man trenger å ha i prod (som vi kanskje burde skjønt basert på navnet :Pp) og som jeg ikke ser noe behov for at vi har i prod. 
En kjapp sjekk viser at det reduserer js-bundlene med ca 75% som for oss vil si ca 3MB. Google-søket mitt til [kilder](https://www.energuide.be/en/questions-answers/do-i-emit-co2-when-i-surf-the-internet/69/) av ubekreftet kvalitet sier at én MB internett er ca 20g CO2. Antar vi rundt 200 sidenedlastinger per dag (fant ikke nøyaktig tall i firebase-konsollen på dette så det er basert på 60 (ekte tall) daglige brukere og antatt 3-4 lastinger per bruker) vil det si 200 * 20 * 3 * 365 / 1000 = 4380 kg CO2 spart per år. Det virket faktisk som en del så …

Gjør tavla mer klimavennlig!

---

src/assets/icons/ThemeDashboardPreview.ts
src/components/Map/index.tsx
src/containers/App.tsx
src/containers/DashboardWrapper/BottomMenu/index.tsx
src/containers/DashboardWrapper/index.tsx
src/containers/Error/ErrorPages.tsx
src/containers/Error/index.tsx
src/containers/LandingPage/SearchPanel/index.tsx
src/containers/LandingPage/index.tsx
src/containers/MyBoards/BoardCard/OverflowMenu/index.tsx
src/containers/MyBoards/BoardCard/index.tsx
src/containers/MyBoards/index.tsx
src/dashboards/BusStop/index.tsx
src/dashboards/Chrono/index.tsx
src/dashboards/Compact/index.tsx
src/dashboards/Map/index.tsx
src/dashboards/Timeline/index.tsx
src/main.tsx
src/routers/PrivateRoute/index.tsx
src/service.ts
src/settings/index.ts
src/types.ts
src/utils.tsx

Ved å gjøre om `<Router />` til `<BrowserRouter />` og legge på noen `// eslint-disable-next-line @typescript-eslint/no-explicit-any` der `any`-typen faktisk er ønsket, fjerner denne PRen alle warnings som kommer opp i konsollen når man kjører `npm run lint`.

Fix all lint warnings

---

src/containers/DashboardWrapper/BottomMenu/index.tsx

Denne PRen innfører en enkel fiks som gjør at bunnmeyen ikke «gjemmer seg» rett etter innlasting når man er på mobil. Det er ønskelig at den forblir synlig for å tydlig vise brukeren mulighetene menyen gir, samt at tavler med så få tiles at det ikke kan scrolles ville aldri ha mulighet til å vise bunnmenyen igjen.

Gjør at bunnmenyen forblir synlig på mobil ved innlasting

---

src/containers/Admin/EditTab/index.tsx

Boksen som lar deg velge hvordan du vil vise været i talva di var litt for høy fra breakpoint xxs og under. Denne PRen endrer høyden fra 3 til 2.

Endre høyden på værinnstillinger i settings

---

src/containers/Admin/ShareTab/components/BoardOwnersList.tsx
src/containers/Admin/ShareTab/components/SharedWithRows.tsx
src/containers/Admin/ShareTab/index.tsx
src/containers/MyBoards/index.tsx
src/services/firebase.ts

Etter at den nye delte-tavler-funksjonaliteten ble lagt til i staging ble noen områder for forbedring funnet. Denne PRen inneholder de relevante fiksene. 
- Varsel med modal om at du må være owner er nå basser på listen av owner fra `settingsContext` og ikke snapshotet som hentes ved update. Dette er gjort av hensyn til hastighet. `settingsContext` er tilgjengelig for oss før `ownersData` er, noe som gjør at man unngår å i noen tilfeller få opp modalen når man faktisk er en eier, men venter på å fetche data. Dette burde heller ikke gå utover sikkerheten, da selv om man skulle greie å manipulere settings til å si at man er en owner, vil fortsatt ingen kall gjort til firestore om å endre ting fungere på grunn av sikkerhetsregler og -sjekker.
- Når man skal fjerne en eier eller invitasjon …

Småfikser for delte tavler

---

firestore.indexes.json

Deploy to staging gir følgende feil: 
``` firestore: The following field overrides are defined in your project but are not present in your firestore indexes file:
[invites.receiver] -- (ASCENDING) (DESCENDING) (CONTAINS) (ASCENDING)
? Would you like to delete these field overrides? Selecting no will continue the
rest of the deployment. (y/N) ? Would you like to delete these field overrides? Selecting no will continue the
rest of the deployment. (y/N) ? Would you like to delete these field overrides? Selecting no will continue the
rest of the deployment. (y/N) 
Too long with no output (exceeded 10m0s): context deadline exceeded
```
Denne PRen legger til filen som beskriver indeksen opprettet i firebase console slik at man ikke får spørsmål om man ønsker å overskrive dataen. 
Testet ved å …

Legg til manglende indeksfil for at deploy ikke skal feile

---

src/components/Modals/RemoveSelfFromTavleModal.tsx

Enda en PR som fikser utilsiktet oppførsel i Shared Boards. Før denne fiksen kunne det hende siden lastet inn på nytt (for å tvinge at rettigheter oppdateres) før man hadde fullført requesten til firestore om å fjerne seg fra `owners`. Dette førte til at man i noen tilfeller ikke klarte å fjerne seg selv fra talva. Ved å legge til den manglende `await`-delen vil nå fjerningen alltid fullføre før siden lastes inn på nytt.

Fix remove self from board not being async await

---

.github/dependabot.yml

Dependabot should only create PRs for patch and minor updates, which are easier to merge because they should not have any breaking changes.
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore

Don't let Dependabot create PRs for major upgrades

---

src/logic/useStopPlacesWithDepartures.ts
src/types.ts
src/utils.tsx

Both `getStopPlaces` and `getStopPlacesWithDepartures` from the SDK were used before. Both were needed to get the data we needed. Both these use the JourneyPlanner query `stopPlaces`. When writing the GraphQL query ourselves, we can combine these into one and only request what we need. This leads to a HUGE reduction in payloads transferred. Especially since Tavla asks for a lot of departures.

Use JP v3 for departures, combine and optimize queries

---

src/components/Map/RealtimeVehicleTag/TooltipContent/index.tsx
src/containers/Admin/EditTab/RealtimeDataPanel/PermanentLinesPanel.tsx
src/containers/Admin/EditTab/RealtimeDataPanel/index.tsx
src/logic/getStopPlacesWithLines.ts
src/services/realtimeVehicles/types/line.ts
src/types.ts
src/utils.tsx

`pointsOnLink` can be undefined, and this caused a crash when creating
`stops` in `getStopPlacesWithLines.ts:124`.
Fixed types to handle undefined values, and refactored `RealtimeDataPanel`
where `pointsOnLink` was used.
Also added util function, `filterMap`.

Fix crash from missing pointsOnLink

---

.circleci/config.yml
functions/package.json
package-lock.json
package.json

Using Node 16 leads to some serious `node-gyp` related issues with npm install that we haven't been able to solve.

Downgrade to Node 14 because of build issues with node-gyp

---

src/components/WeatherTile/index.tsx
src/containers/Admin/EditTab/BikeSearch/index.tsx
src/logic/useBikeRentalStations.ts
src/logic/useMobility.ts
src/logic/useStopPlacesWithLines.ts
src/utils.tsx

AbortController is not supported by all browsers. But our usage of the abort controller is more an optimization than critical functionality. So this fake AbortController stub should be good enough.

Avoid errors if AbortController not supported

---

src/logic/useNearestPlaces.ts

Fixes a bug were the list of nearby stop places did not list all the relevant, because bike rental stations and scooters also was listed in the result list

Bug fix for stop places nearby

---

src/components/DateRow/index.tsx
src/components/DateRow/styles.scss
src/dashboards/BusStop/components/TileRows/index.tsx
src/dashboards/Chrono/BikeTile/index.tsx
src/dashboards/Chrono/components/TileRows/index.tsx
src/dashboards/Compact/BikeTile/index.tsx
src/dashboards/Compact/components/TileRow/index.tsx
src/dashboards/Compact/components/TileRow/styles.scss
src/dashboards/Map/DepartureTag/index.tsx
src/dashboards/Map/DepartureTag/styles.scss
src/logic/useStopPlacesWithDepartures.ts
src/types.ts
src/utils.tsx

- Implemented for Compact, Chrono, BusStop and Map
[Kan testes i staging](https://tavla.staging.entur.no/t/ggmVjIorQJi3sWD3FYUU)
Compact:
Chrono:
BusStop:
Map:

ETU-25891: Indicate next day on departures

---

src/dashboards/Compact/DepartureTile/index.tsx
src/dashboards/Compact/components/TileRow/index.tsx
src/dashboards/Compact/components/TileRow/styles.scss
src/logic/useStopPlacesWithDepartures.ts

In compact view the date was pushed under the next time item on small screens. Fixed using equal padding between items.
Also:
- moved divider between items
- Ask for departures the next two days (172800 seconds. Default was 1 day)

ETU-25891: Fix date styling issue

---

src/containers/Admin/EditTab/index.tsx
src/containers/Admin/EditTab/styles.scss
src/containers/App.tsx
src/settings/index.ts

**Problem:**
When developers push new code, the existing Tavles are not necessary updated with the new features/fixes. 
**Solution:**
The possibility to refresh all Tavler on queue through the admin-panel.
When new code is pushed to master, the users can refresh their Tavler through the admin panel by clicking "last inn tavler på nytt". 
**Before:**
**After:**

Refresh Tavle from admin panel

---

src/components/EmptyStopTile/EmptyStopTile.tsx
src/containers/Admin/EditTab/StopPlacePanel/StopPlacePanel.tsx
src/dashboards/BusStop/components/BusStopTile/BusStopTile.tsx
src/dashboards/Chrono/ChronoDepartureTile/ChronoDepartureTile.tsx
src/dashboards/Compact/CompactDepartureTile/CompactDepartureTile.tsx

Because of changes to how we fetch and present data, we no longer filter out stopplaces with no departures on dashboards, but they are filtered out in the admin panel. This PR removes the admin panel filtering so the user can remove empty stopplaces if they want, and adds a new tile that is shown whenever a stopplace has no departures.

Add EmptyStopTile, similar to ErrorTile

---

src/containers/Admin/ShareTab/components/AddNewOwnersInput.tsx

Motivasjon: 
- Felt for tavle-eier er ikke smart
Problemet her er at feltet for å legge til eier av ei tavle indikerer ikke at det er e-postadresse som skal fylles inn.
Løsningen her er å legge noe i koden som gjør at inputfeltet skjønner at det er e-post og kan foreslå dine e-postadresser.

added autocomplete field for better uu

---

src/containers/Admin/ShareTab/components/EditableBoardTitle.tsx

Problem: 
Inne på "Deling" ligg namnet til Tavla med eit rediger-ikon bak. Ved å tab'e gjennom og trykke enter så hopper den raskt over i rediger-modus et sekund før den hopper ut igjen.
Løsning: 
Fikset bug med redigerknappen sånn at man kan ha fokus på knappen, trykke enter og redigere.

2.1.1: Tastatur

---

src/dashboards/BusStop/components/BusStopTile/BusStopTile.module.scss
src/dashboards/BusStop/components/BusStopTile/BusStopTile.tsx
src/dashboards/Chrono/ChronoDepartureTile/ChronoDepartureTile.module.scss

Change from "spor" to "platform" made cell header text overflow in chrono and busstop dashboards

Made overflowing text cut off in chrono and busstop table headers

---

src/dashboards/BusStop/components/BusStopTile/BusStopTile.tsx
src/dashboards/Chrono/ChronoDepartureTile/ChronoDepartureTile.tsx
src/logic/use-stop-place-with-estimated-calls/departure.ts

* Sort departures by departure time. This was previously done by the api.

sort-by-departure-time

---

src/hooks/useThemeHandler.ts

Styling was not cleared from body when navigating to front page.
To reproduce, go to admin panel, set theme to non-default, then click the Entur logo to go to the front page.
bug
intended

Small fix for theme styling bug

---

src/components/RadioCard/RadioCard.module.scss

This is contrast compliant on default theme and looks alright in other themes, though I think we might need to consider a larger color overhaul if we want all themes to be compliant.

1.4.11 Kontrast for ikke-tekstlig innhold

---

src/containers/ResponsiveGridDashboard/ResponsiveGridDashboard.tsx

Previously used location.key, which changes when navigating the site, even if on the same URL. Causes problems, e.g. tavle (key: 123) -> rediger -> back to tavle (key:456)

Fixes layout not storing correctly on navigation

---

graphql-generated/journey-planner-v3.ts
graphql-schemas/journey-planner-v3.json
src/dashboards/BusStop/components/BusStopTile/BusStopTile.tsx
src/dashboards/Chrono/ChronoDepartureTile/ChronoDepartureTile.tsx
src/logic/use-stop-place-with-estimated-calls/useStopPlaceWithEstimatedCalls.journey-planner.graphql
src/logic/use-stop-place-with-estimated-calls/useStopPlaceWithEstimatedCalls.ts

Currently, we fetch the next 200 departures and map through them. Chrono and StopPlace dashboards can only display about 20 per screen, which means we have a lot of unnecessary stuff fetched and loaded.

Makes it possible to fetch custom number of departures

---

.graphqlconfig
src/dashboards/BusStop/components/BusStopTile/BusStopTile.tsx
src/dashboards/Chrono/ChronoDepartureTile/ChronoDepartureTile.tsx
src/dashboards/Responsive/ResponsiveDepartureTile/ResponsiveDepartureTile.tsx

Partially reverts change in #917
Now fetches the next 200 departures (default value) like before, but limits to 20 departures per line.

fix(departures): revert to fetching surplus data and filtering client-side

---

src/containers/DashboardWrapper/DashboardWrapper.tsx
src/hooks/useUpdateLastActive.ts
src/settings/settings.ts

Adds field to settings that is updated daily if website is running. Can be used to check for inactive boards.

feat(settings): add "last active" field

---

.husky/pre-commit
package.json
yarn.lock

`yarn install` now automatically installs husky, which runs pre-commit hooks validating linting and formatting

feat(husky): added pre-commit hooks

---

tavla/src/tiles/admin/StopPlaceTile/components/StopPlacePanel/PanelRow/index.tsx
tavla/src/tiles/admin/StopPlaceTile/components/StopPlaceSearch/index.tsx

fix(admin): better handling of duplicate stopplaces

---

next-tavla/pages/admin/[id].tsx

The header logo has different colors in dark and light themes. The Admin-page uses Entur colors regardless of theme, and should not change the header logo based on theme in settings.
Before:
After:

fix(theming): do not set logo based on theme on admin

---

next-tavla/pages/[id].tsx
next-tavla/src/Admin/scenarios/Landing/index.tsx
next-tavla/src/Admin/scenarios/ThemeSettings/ThemeSettings.cy.tsx
next-tavla/src/Admin/scenarios/ThemeSettings/index.tsx
next-tavla/src/Shared/types/settings.ts
next-tavla/src/Shared/utils/converters.test.ts
next-tavla/src/Shared/utils/converters.ts

Changed the default theme to be dark when creating a board. A field in the theme settings is changed from "default" to "entur" and therefor a converter was created.

fix(theme): dark as default theme and add converter

---

next-tavla/src/Admin/scenarios/SelectLines/index.tsx
next-tavla/src/Admin/scenarios/SelectLines/styles.module.css

feat(edit): grid layout for toggle lines

---

next-tavla/src/Board/scenarios/QuayTile/index.tsx
next-tavla/src/Shared/graphql/fragments/lines.graphql
next-tavla/src/Shared/graphql/index.ts

Added tableheader with transporticons  to the quaytile. Shows public code and description if they are defined

feat(edit): added tableheader to the quaytile

---

next-tavla/src/Admin/scenarios/Edit/index.tsx
next-tavla/src/Admin/scenarios/Edit/reducer.tsx
next-tavla/src/Admin/scenarios/ToggleColumns/index.tsx
next-tavla/src/Shared/types/column.ts

Added toggle columns to the edit page. the component only changes the first tile in the tiles list and not the rest. Not supposed to be where its put but added to show functionality

feat(edit): toggle optional columns

---

next-tavla/src/Admin/scenarios/Edit/index.tsx
next-tavla/src/Admin/scenarios/TileSettings/components/QuaySettings.tsx
next-tavla/src/Admin/scenarios/TileSettings/components/StopPlaceSettings.tsx
next-tavla/src/Admin/scenarios/TileSettings/components/TileSettingsWrapper/styles.module.css
next-tavla/src/Admin/scenarios/ToggleColumns/index.tsx
next-tavla/src/Admin/scenarios/ToggleColumns/styles.module.css

Added the toggle column component to the tileoverview component. Fixes error when creating a new board by using the button on the landing page and doesn't use the first tile in the list but the certain tile tiles overview.

feat(edit): adds toggle to tileoverview

---

next-tavla/src/Admin/scenarios/Edit/styles.module.css

fix(edit): adds border to the admin page

---

next-tavla/src/Board/scenarios/Table/components/Situation/index.tsx
next-tavla/src/Board/scenarios/Table/components/Situation/styles.module.css
next-tavla/src/Board/scenarios/Table/components/Situations/index.tsx

Added functionality to the table such that if a line has more than 1 deviation it alternates between each deviation. Each is shown for 5 seconds before it switches to the next one. 
Can for example use line 81, "jernbanetorget" to test

feat(table): alternates between deviations in table

---

next-tavla/src/Admin/scenarios/Edit/styles.module.css
next-tavla/src/Shared/components/Header/index.tsx
next-tavla/src/Shared/styles/pages/admin.module.css

feat(header): remove tagtext from header

---

next-tavla/src/Board/scenarios/Table/styles.module.css

fix(board): fixed bug where tablerows spread if there are few rows

---

next-tavla/src/Admin/scenarios/ShareTable/index.tsx

fix(typo): typo in ShareTable heading

---

next-tavla/pages/edit/[id].tsx
next-tavla/src/Board/scenarios/Table/components/TableHeader/styles.module.css
next-tavla/src/Board/scenarios/Table/components/Time/styles.module.css
next-tavla/src/Shared/styles/themes/default.css
next-tavla/src/Shared/styles/themes/light.css

Move transport icons next to header: 
Remove pink color on late departure: 
Move toast to top:

fix(edit + board): clarify information 

---

next-tavla/src/Admin/scenarios/TilesOverview/index.tsx

When a tab is deleted, an empty screen is shown. 
Set a use state for the active tab and set it to the first tab when any tab is deleted. 
| Before   |  After |
:-------------------------:|:-------------------------:

fix(board): show first tab's content when another tab is deleted

---

next-tavla/src/Admin/scenarios/BoardTitle/index.tsx
next-tavla/src/Admin/scenarios/BoardTitle/styles.module.css
next-tavla/src/Admin/scenarios/Edit/index.tsx
next-tavla/src/Admin/scenarios/Edit/reducer.ts
next-tavla/src/Admin/scenarios/Edit/styles.module.css
next-tavla/src/Shared/types/settings.ts

Made it possible to edit and save the name of a table. For tables without a name, this will default to "Tavla". Changes will not be saved to Firebase unless the "Save table"-button is clicked.

feat(edit): change and save title

---

next-tavla/package.json
next-tavla/src/Admin/scenarios/BoardList/components/Row/index.tsx
next-tavla/src/Admin/scenarios/Boards/index.tsx
next-tavla/src/Admin/scenarios/Info/index.tsx
next-tavla/src/Admin/scenarios/Info/styles.module.css
next-tavla/src/Admin/scenarios/TableHeader/index.tsx
next-tavla/yarn.lock

Created a component with a popover that shows information about which stops the board contains.

feat(boards): show additional board information

---

next-tavla/src/Admin/scenarios/Edit/reducer.ts

Changed direction of how the tiles are build up. The tiles and tabs will now be displayed from left to right (regular reading direction). 
|Before | After |
|--------|-----|
|<img width="682" alt="image" src="https://github.com/entur/tavla/assets/64562118/9eb4a454-9580-4a9b-8b93-1958f2c641cf"> | <img width="649" alt="image" src="https://github.com/entur/tavla/assets/64562118/eac39929-3a9e-4629-a79b-3569887e322c">|
|<img width="1708" alt="image" src="https://github.com/entur/tavla/assets/64562118/f55f91b8-de5c-4253-9442-11f228b2ace3">|<img width="1681" alt="image" src="https://github.com/entur/tavla/assets/64562118/2590ad7b-4c2f-4118-8392-2b617b17ec56">|

feat(edit): change direction of the tiles

---

next-tavla/src/Admin/scenarios/Boards/index.tsx
next-tavla/src/Admin/scenarios/Boards/styles.module.css
next-tavla/src/Admin/scenarios/CreateBoard/index.tsx
next-tavla/src/Admin/scenarios/Landing/index.tsx
next-tavla/src/Admin/scenarios/Landing/styles.module.css

- moved Button that creates a board from landing page to its own component that can now be reused multiple places
- added new "Create Board" component to Landing page 
- added new "Create Board" component to Boards

feat(boards): create board from "my boards" 

---

next-tavla/src/Admin/scenarios/Edit/components/TilesOverview/index.tsx

When a new tab is added, it is expected that the newest tab will be opened. 
Has set the newest tab to be active.
| Before | After |
|--------|------|
| ![image](https://github.com/entur/tavla/assets/64562118/59807b1a-2e3c-4843-862b-c80563f1271f)| <img width="240" alt="image" src="https://github.com/entur/tavla/assets/64562118/347313a2-cd43-4010-9ec4-3eeda4a19284">|

feat(edit): set active tab to be the newest added tab

---

next-tavla/src/Admin/scenarios/Boards/hooks/useSortBoardFunction.ts
next-tavla/src/Admin/scenarios/Boards/index.tsx

Updated default sorting of my boards to be by the last modified. 
_"Som bruker av tavla antar jeg når jeg lagrer en ny tavle - at den havner på toppen, sortert etter sist oppdatert - ikke etter navn."_

feat(boards): update default sorting to be by the last updated

---

next-tavla/src/Admin/scenarios/Edit/components/AutoSave/index.tsx

Fixed autosave:
- if user edits "edit board" page, the last modified date will not be updated
- save the board only when changes were made, and not when the page was opened

fix(edit): update autosave

---

next-tavla/src/Admin/scenarios/Boards/components/Column/Actions.tsx
next-tavla/src/Admin/scenarios/Boards/components/Column/DraggableColumn.tsx
next-tavla/src/Admin/scenarios/Boards/components/Column/LastModified.tsx
next-tavla/src/Admin/scenarios/Boards/components/Column/Link.tsx
next-tavla/src/Admin/scenarios/Boards/components/Column/Name.tsx

Found that the `SortableColumn`-component's name was easy to confuse with the `SortableColumn`-type which indicates if a column can be sorted in an ascending or descending order. Switched to `DraggableColumn`, which is more accurate.

fix(code quality): clarified component name

---

next-tavla/pages/edit/organizations.tsx
next-tavla/src/Admin/components/AdminHeader/index.tsx
next-tavla/src/Admin/scenarios/Boards/components/Column/Tags.tsx
next-tavla/src/Admin/scenarios/Organizations/index.tsx
next-tavla/src/Shared/types/featureFlag.ts

- created an empty page for organizations with link: /edit/organizations 
- button (link) in admin header that leads to organizations page
- put button that leads to organizations page behind feature flag

feat(organizations): created organizations page and linked from header

---

next-tavla/src/Admin/utils/firebase.ts

Removes the board reference from a user when the board is deleted.
Should also be done to organizations when their datatypes are more mature.

fix(firebase): removing board reference from user when board is deleted

---

next-tavla/src/Admin/scenarios/Edit/components/FontsizeSelector/index.tsx
next-tavla/src/Board/scenarios/Board/index.tsx
next-tavla/src/Board/scenarios/Board/utils.ts

If user has not chosen fontsize, the default textsize will be set depending on number of tiles in the board. 
1 tile - large text
2 tiles - medium text
3 tiles and more - small text

feat(board): default behaviour for textsize

---

next-tavla/src/Admin/scenarios/CreateBoard/components/AddStops.tsx
next-tavla/src/Admin/scenarios/Edit/components/AddTile/index.tsx
next-tavla/src/Admin/scenarios/Edit/index.tsx

Display the input fields in columns instead of in rows in the modal. This resolves the "dancing" issue and overflow.

styling(create): flexColumn for add stops in modal

---

next-tavla/src/Admin/scenarios/CreateBoard/components/Name.tsx
next-tavla/src/Admin/scenarios/Edit/components/AddTile/index.tsx
next-tavla/src/Admin/scenarios/Edit/index.tsx

Fix a warning when the name field value changes from ```undefined```.  Also search icon in quay dropdown. Remove console log.

fix(create): fix warning when name is undefined

---

next-tavla/pages/api/board.ts
next-tavla/pages/api/organization.ts
next-tavla/src/Admin/scenarios/CreateBoard/components/AddStops.tsx
next-tavla/src/Admin/scenarios/CreateBoard/components/AddToOrganization.tsx
next-tavla/src/Admin/scenarios/CreateBoard/components/CreateBoardButton.tsx
next-tavla/src/Admin/scenarios/CreateBoard/components/Organization.tsx
next-tavla/src/Admin/scenarios/CreateBoard/hooks/useOrganizations.ts
next-tavla/src/Admin/scenarios/CreateBoard/index.tsx
next-tavla/src/Admin/scenarios/CreateBoard/utils/create.ts
next-tavla/src/Admin/types/createBoard.ts
next-tavla/src/Admin/utils/fetch.ts
next-tavla/src/Admin/utils/firebase.ts

- new step in the creating board modal
- new api end point for getting all user's organizations (showing in dropdon in the modal)
-  update create board (post) request so it either creates a boared for user or for organization
- if no organization is chosen, the board will be saved as user's private board

feat(create): modal step to assign new board to organization

---

next-tavla/src/Admin/scenarios/Edit/components/SelectLines/index.tsx
next-tavla/src/Board/scenarios/Table/components/Line/index.tsx
next-tavla/src/Shared/components/TransportIcon/index.tsx
next-tavla/src/Shared/components/TravelTag/index.tsx

Uses `transportSubmode` to render a more precise icon in certain scenarios, i.e. for car ferries vs high speed ferries.

feat(transport icon): added icon for carferries

---

next-tavla/src/Admin/components/DeleteModal/index.tsx
next-tavla/src/Admin/scenarios/Boards/components/SelectOrganization/index.tsx
next-tavla/src/Admin/scenarios/Boards/components/SelectOrganization/styles.module.css
next-tavla/src/Admin/scenarios/Edit/index.tsx
next-tavla/src/Admin/scenarios/Landing/index.tsx
next-tavla/src/Admin/scenarios/Organizations/index.tsx
next-tavla/src/Shared/styles/global.css
next-tavla/src/Shared/styles/reset.css

Removed some styling on the `eds-h1` class that resulted in `<Heading1>` being rendered as smaller than it should be in some places. In the components where `<Heading1>` should actually be rendered smaller, it was replaced by `<Heading2 as='h1'>`, giving it the same size but correct semantics.

fix(headings): removed h1 styling

---

next-tavla/src/Admin/scenarios/Edit/components/SaveStatus/index.tsx
next-tavla/src/Admin/utils/time.ts

Earlier, when displaying a timestamp that occured yesterday but still less than 24 hours ago, the timestamp would be displayed in the `HH:MM` format, which in some cases could be confusing.
This PR will instead display the time difference in seconds/minutes/hours/..., or a timestamp if specified.

feat(time): more accurately display timestamps that occurred yesterday

---

next-tavla/src/Admin/scenarios/Boards/components/Column/Tags.tsx
next-tavla/src/Admin/scenarios/Boards/components/FilterButton/index.tsx
next-tavla/src/Admin/scenarios/Boards/components/Search/index.tsx
next-tavla/src/Admin/scenarios/Boards/components/ToggleBoardsColumns/index.tsx
next-tavla/src/Admin/scenarios/Boards/index.tsx
next-tavla/src/Shared/styles/global.css
next-tavla/tsconfig.json

- tags inside boards table will now be read like this: "list with 2 elements". "merkelapp: oslo sentrum, item 1 of 2",....
- notification badge in filter button: says how many tags are selected for filter
- choose columns: changed to contain text

fix(accessibility): tags, filter and choose columns

---

next-tavla/src/Admin/utils/formActions.ts

If organization name consists of only whitespaces, the organization will not be created

chore(organization): not allow org name to contain only whitespaces

---

tavla/src/components/MigrationBanner.tsx
tavla/src/routes/Admin/index.tsx
tavla/src/routes/LandingPage/index.tsx
tavla/src/routes/MyBoards/OwnedBoards/GridView/GridView.tsx
tavla/src/routes/MyBoards/OwnedBoards/OwnedBoards.tsx
tavla/src/routes/MyBoards/index.tsx
tavla/src/scenarios/ErrorPages/NoTavlerAvailable.tsx

The banner will be shown in:
- landing-page
- edit boards-page 
- my boards-page

feat(banner): show banner and remove option to create new boards in old 'entur tavla'

---

next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx

feat(lines): remove occasional duplicate lines

---

next-tavla/app/(admin)/boards/components/Column/Delete.tsx
next-tavla/app/(admin)/components/Delete/index.tsx
next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/index.tsx
next-tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/styles.module.css
next-tavla/app/(admin)/organizations/components/MemberAdministration/InviteUser.tsx
next-tavla/app/(admin)/organizations/components/MemberAdministration/MemberList.tsx
next-tavla/app/(admin)/organizations/components/MemberAdministration/RemoveUserButton.tsx
next-tavla/app/(admin)/organizations/components/MemberAdministration/index.tsx
next-tavla/app/(admin)/organizations/components/MemberAdministration/styles.module.css
next-tavla/src/Admin/types/organizations.ts
next-tavla/src/Shared/styles/global.css

When editing an organization, the member administration table now has two colum names ("E-post" and "Valg"). It looks like this:
When deleting a member, a modal opens up asking for confirmation:
I tried to change the memberAdministration component to using semantic HTML and corresponding table elements  instead of'`<div>`. I also placed most of the modal-logic inside `RemoveUserButton`.

feat(organization): table columns and delete member modal

---

next-tavla/app/(admin)/components/Login/Reset.tsx
next-tavla/app/(admin)/utils.ts

When clicking on reset password, the textfield turns green and a success-toast appears
Results:

feat(login): reset password link confirmation

---

next-tavla/app/(admin)/boards/components/Column/Actions.tsx
next-tavla/app/(admin)/boards/components/Column/Delete.tsx
next-tavla/app/(admin)/boards/utils/formActions.ts
next-tavla/app/(admin)/edit/[id]/components/Buttons/Copy.tsx
next-tavla/app/(admin)/edit/[id]/components/Buttons/Open.tsx
next-tavla/app/(admin)/edit/[id]/components/Buttons/index.tsx
next-tavla/app/(admin)/edit/[id]/page.tsx

I tried to 'reuse' the buttons from `Actions.tsx`, and changes were made since they were iconbuttons and not normal buttons. They are still unchanged in the boards overview page, see picture below.
- <img width="1612" alt="image" src="https://github.com/entur/tavla/assets/74315929/1d33375c-3705-4b52-a645-1cdfb5505027">
- ![image](https://github.com/entur/tavla/assets/74315929/2b41dab1-83d2-4a90-b9ea-883376d5b148)

feat(edit): board actions in edit page

---

next-tavla/app/(admin)/components/CreateBoard/index.tsx

SetOrganization to undefined if user has ticked checkbox. No default counties will show on next page

fix(create): create board with no default org settings

---

next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
next-tavla/app/(admin)/utils/time.ts
next-tavla/src/Board/scenarios/Table/components/WalkingDistance.tsx
next-tavla/src/Shared/graphql/index.ts
next-tavla/src/Shared/graphql/queries/walkingDistance.graphql

If walking duration can't be calculated it is indicated with "-". Also improvements to avoid weird time displays, such as "4 t og 60 min"

feat(board): format walking duration

---

next-tavla/pages/[id].tsx
next-tavla/src/Shared/components/Footer/index.tsx

fix(footer): switch text and logo based on theme

---

next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx

There were two problems: 
- It was not possible to turn on/off the switch if it was just enabled and saved
- The switch were automatically off if other stuffed were changed and saved (even if it should have been on)

fix(edit): switch toogling and automatic off-state on walking distance

---

next-tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
next-tavla/app/(admin)/edit/[id]/page.tsx

Cause: If meta-settings are not present, location is undefined. This causes the server to throw an error in edit board page. 
Before: Throws error in production
- ![image](https://github.com/entur/tavla/assets/74315929/b85eea77-82e2-488c-8eec-4891a19fb7a3)
After
- <img width="1499" alt="image" src="https://github.com/entur/tavla/assets/74315929/b5c6838d-2ab2-4066-8795-7f923d5c7a90">

fix(edit): edit board page when meta field missing

---

next-tavla/app/(admin)/components/Footer/index.tsx
next-tavla/app/(admin)/components/Preview/index.tsx
next-tavla/app/components/FloatingContact.tsx
next-tavla/app/layout.tsx
next-tavla/app/page.tsx

feat(support): add support email buttons

---

next-tavla/app/page.tsx
next-tavla/app/privacy/components/ExpandableInfo.tsx
next-tavla/app/privacy/page.tsx

Also removed double footer in /privacy page, and fix aligning of icons in links in /privacy.
**Before:** 
**After:**

style(landing): compact view

---

next-tavla/app/(admin)/boards/components/Column/Name.tsx
next-tavla/app/(admin)/boards/components/Column/Organization.tsx
next-tavla/app/(admin)/boards/components/Search/index.tsx
next-tavla/app/(admin)/boards/components/TableRows/index.tsx
next-tavla/app/(admin)/utils/constants.ts

Det er ikke mulig å både søke på tavle navn og organisasjon, kun en av delene.

feat(boards): add org to search

---

next-tavla/app/(admin)/components/TileSelector/index.tsx
next-tavla/app/(admin)/edit/[id]/page.tsx
next-tavla/app/(admin)/hooks/useQuaySearch.ts
next-tavla/src/Shared/components/Header/index.tsx
next-tavla/src/Shared/components/TravelTag/index.tsx
next-tavla/src/Shared/graphql/index.ts
next-tavla/src/Shared/graphql/queries/quaySearch.graphql
next-tavla/src/Shared/styles/reset.css

feat(tile): add lines to TileSelector

---

next-tavla/app/(admin)/components/CreateBoard/index.tsx

fix this:
- <img width="764" alt="image" src="https://github.com/entur/tavla/assets/74315929/c6c39b39-cfec-4965-8934-af5cca4fbd0a">
Now, the dropdown is empty when disabled

fix(create):empty org dropdown on personal board choice

---

next-tavla/app/(admin)/boards/components/FilterButton/index.tsx
next-tavla/app/(admin)/boards/components/TableRows/index.tsx
next-tavla/app/(admin)/boards/hooks/useSearchParamReplacer.ts
next-tavla/app/(admin)/boards/page.tsx

**Slow filter caused by NextJS routing**
`router.replace()` behaved slow to update the browsers history stack (tested with React profiler), so the main solution was to use the alternative [history API ](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#using-the-native-history-api) to fix the performance issues. 
This also makes sorting in /boards faster compared to before 
Also did some refactoring in `Filterbutton` and `page`

fix(routing): Fix filter and board sorting performance

---

next-tavla/app/(admin)/components/CreateBoard/components/StopPlaceList.tsx
next-tavla/app/(admin)/components/Footer/index.tsx
next-tavla/app/(admin)/components/Login/index.tsx
next-tavla/app/(admin)/components/SideNavBar.tsx
next-tavla/app/(admin)/components/TopNavigation.tsx
next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
next-tavla/app/(admin)/hooks/useLocalStorage.ts
next-tavla/app/(admin)/layout.tsx
next-tavla/app/demo/components/CreateUserButton.tsx
next-tavla/app/demo/components/DemoBoard.tsx
next-tavla/app/demo/page.tsx
next-tavla/app/layout.tsx
next-tavla/app/page.tsx
next-tavla/app/privacy/page.tsx
next-tavla/src/Board/scenarios/Board/index.tsx
next-tavla/src/Board/scenarios/Table/index.tsx

- Use local storage to store the demo board. Created a custom hook to keep track of and update the local storage, so it _can_ be used by other components if needed in the future -> if demo board is no longer supposed to be in local storage (e g moved to firestore), the hook can be omitted
- still need to pass the demoboard prop down to the tilecard to listen for changes in the tiles. not optimal, but the only solution i found to be able to update local storage (it doesnt seem there is a way to listen to changes in the local storage)
- if demo board, show another error text on "gåavstand" (see pic 2)

feat(demo): possible to try tavla without creating a user

---

next-tavla/app/(admin)/components/Login/Email.tsx
next-tavla/app/verify/[oob]/page.tsx

Tried to follow this turtorial: https://firebase.google.com/docs/reference/rest/auth#section-confirm-email-verification
When doing this curl command (with the right api-key and oob code):
```
curl 'https://identitytoolkit.googleapis.com/v1/accounts:update?key=[API_KEY]' \
-H 'Content-Type: application/json' --data-binary '{"oobCode":"[VERIFICATION_CODE]"}'
```
This is the output:
By using the oobCode one can find the field to check if the email is verified even thought the message we are displaying to the user says otherwise. 
It is hard to check this using the emulator, so it need to be checked in the dev-env. 
If the `applyActionCode` funtion is failing (as it does if one presses the link from the outlook-email), it goes to the `catch`-block trying to manually check if the email is …

fix(verify): manual check if email is verified

---

next-tavla/app/page.tsx
next-tavla/src/Board/scenarios/Table/index.tsx

Before (in dark mode):
- ![image](https://github.com/user-attachments/assets/b278f04e-b4fc-4a20-b864-7079f707a0b8)
After:
- ![image](https://github.com/user-attachments/assets/98101e61-d184-45c1-943b-c915cce32079)
Also changed preview board on homepage to be darkmode:
- ![image](https://github.com/user-attachments/assets/5d2234a4-10dc-4dea-9323-aac2bd4a1676)

fix(boards):Text color preview

---

next-tavla/app/(admin)/boards/components/FilterButton/index.tsx

Before:
- <img width="1655" alt="image" src="https://github.com/user-attachments/assets/2c7bcaad-d163-4f12-a9d7-e391e1895849">
After:
- <img width="1563" alt="image" src="https://github.com/user-attachments/assets/7ce40e4c-8548-4047-b408-d4ba70a3709c">

chore(boards): change text filter tags button

---

next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx

The change applies to mobile view
before:
- ![image](https://github.com/user-attachments/assets/a95e0e6a-20f3-4d0a-b749-793cc4b5d9cd)
After:
- ![image](https://github.com/user-attachments/assets/f1683db8-061f-42aa-ad4a-5ef19ef85c5a)

chore(board): spacing between tilecard name and action buttons

---

next-tavla/app/(admin)/components/Footer/components/DeleteUser.tsx
next-tavla/app/(admin)/components/Footer/components/actions.ts
next-tavla/app/(admin)/components/Footer/index.tsx
next-tavla/app/(admin)/utils/firebase.ts
next-tavla/app/(admin)/utils/index.ts
next-tavla/app/layout.tsx

feat(user): delete user

---

next-tavla/app/(admin)/edit/[id]/actions.ts
next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
next-tavla/app/(admin)/edit/[id]/components/TileList/index.tsx
next-tavla/app/(admin)/edit/[id]/page.tsx
next-tavla/app/demo/components/DemoBoard.tsx

**Change order of tiles in boards**
This works in both /edit and for demoboards. 
- Made a `TileList` wrapper for the `TileCard` components to keep track of the order of the tiles, as the original parent component was a server component
- Uses debounce to not trigger frequent requests to the backend for saving tiles
Result:
- <img width="1251" alt="image" src="https://github.com/user-attachments/assets/8612cff6-8a5e-4dfc-bfb4-6981bada8a63">
- <img width="1248" alt="image" src="https://github.com/user-attachments/assets/82b40bd4-6d2d-4888-89e2-f6f93884ba3e">
- <img width="1250" alt="image" src="https://github.com/user-attachments/assets/eb9b309e-6976-42c3-8770-69c09a23c8a1">

feat(board): change order of tiles

---

next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
next-tavla/app/(admin)/edit/[id]/components/TileCard/utils.ts

As long as location is set, one can set offset based on walking distance. If the location is not set, the checkbox for ticking off is not shown.

feat(tile): set offset based on walking distance

---

next-tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx

De eneste casene man vil vise checkboken for å forskyve tiden basert på gåavstand er: 
- Når man har adressen og distansen er et nummer
- Når man har adressen og distansen er undefined
Man vil altså ikke vise checkboksen om:
- Man ikke har en adresse
- Distansen er satt til `NaN` (lokasjonen og stoppestedet er for langt unna hverandre). 
Eksempel om et stoppested er i Trondheim og et er i Oslo, og adressen er satt til å være i Oslo:

fix(offset): not show checkbox if distance is NaN

---

tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
tavla/app/(admin)/edit/utils.ts
tavla/app/(admin)/utils/index.ts

stops action after clicking on save tile if displayname is only whitespace. Returns formerror instead
After:
- ![image](https://github.com/user-attachments/assets/6cb6d113-ddc1-4ac6-bad1-a01152ef9464)

fix(edit): display name error handling

---

tavla/app/demo/components/DemoBoard.tsx
tavla/app/demo/components/ExpandableInformation.tsx
tavla/app/demo/page.tsx

The "Hva du kan gjøre med Tavla om du logger inn" is changed to an expandable panel. 
One of two "Opprett bruker" is removed.

style(demo): move information to an expandable panel 

---

tavla/app/(admin)/organizations/components/Organizations.tsx

Illustrasjon lagt til, vi tar en runde senere på at opprett org knappen kanskje kan flyttes (Hannah ser på det først)

style(organizations): add illustration to empty org page

---

tavla/app/(admin)/boards/components/BoardTable/index.tsx
tavla/app/(admin)/components/IllustratedInfo/index.tsx

feat(boards): add button to empty board page

---

tavla/app/(admin)/edit/utils.ts
tavla/src/Shared/components/TravelTag/index.tsx

Bytter fra de svarte transportmiddel-ikonene til samme som vi har på retning-dropdown, dvs hvitt ikon inni boks med farge.
Før:
Etter:

feat(tileselector): add correct icons to stopplace-selector dropdown

---

tavla/src/Shared/hooks/useQuery.ts

Meldt inn som issue på github: Tavla på mobil blir utdatert når man bytter til en annen tab eller går ut av nettleser. Setter nå at ny fetch av data skjer hver gang man går inn på tavla-taben på nytt.
Obs: la leve i dev litt så vi catcher bugs

fix(board): set board update on renewed focus of tab

---

tavla/app/(admin)/components/Preview/index.tsx
tavla/app/page.tsx
tavla/src/Shared/utils/previewBoards.ts

Added auto-rolling carousel of previewboards to landing page:
On mobile:

feat(landing): carousel of preview boards

---

tavla/app/(admin)/components/PreviewCarousel/index.tsx
tavla/app/(admin)/edit/[id]/components/Preview/index.tsx
tavla/app/globals.css
tavla/app/page.tsx
tavla/src/Shared/utils/previewBoards.ts

Hele tavler i preview-karusellen, kan nå vise logo, klokke og flere tiles. OBS: bruker samme komponent som preview i både demo og edit så gjerne sjekk at det ikke er ødelagt
Mobil:

feat(landing): show full boards on landing page

---

tavla/app/(admin)/components/Delete/actions.ts
tavla/app/(admin)/components/Delete/index.tsx

problemet er at toasten må legges til kun dersom sletting av org går gjennom, og jeg har ikke fått til å sjekke det på en ordentlig måte. har derfor flyttet halve error-håndteringen ut av slette-funksjonen. 
dette funker som en quick-fix, men jeg antar det ikke er sånn her vi egt har lyst til å gjøre det. plis hjelp
(kommer ikke opp toast i denne situasjonen)

fix(organizations): delete-toast does not appear until org is deleted

---

tavla/app/(admin)/organizations/components/Organizations.tsx
tavla/app/(admin)/organizations/page.tsx
tavla/app/(admin)/utils/firebase.ts

Problem: 
- If a board was in an organization, and the board got deleted, the board was not removed from the organization-collection in Firestore. Hence, the number of "antall tavler" on the organizations-page was wrong. This is now removed. 
New look:

fix(organization): delete board from organization collection

---

tavla/app/(admin)/edit/[id]/components/TileCard/useLines.ts
tavla/src/Shared/assets/env.ts
tavla/src/Shared/graphql/utils.ts

Endrer et-client-name til "entur-tavla", som er den standarden developer docs anbefaler: https://developer.entur.org/pages-journeyplanner-journeyplanner
Ble anbefalt dette etter å ha spurt om økning i open-admins, vi er nå en del av enturs delte rate limits og har økt til 10 000.

fix(graphql): change et-client-name to increase rate limit

---

tavla/app/(admin)/edit/[id]/components/Preview/index.tsx
tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
tavla/app/(admin)/edit/[id]/page.tsx

Småplukk i edit på mobil:
- Overflow av metasettings fikset
Før:
Nå:
- Overflow i visning av linjer i tilecard:
Nå:
Tavlestørrelse på mobil:
Nå:

fix(edit): remove overflow of settings and adjust preview size on mobile

---

tavla/app/(admin)/edit/[id]/actions.ts
tavla/app/(admin)/edit/[id]/compatibility.ts
tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx

Laget en transformer som mapper alle gamle linjeIDer til nye linjeIDer. Grunnen til at vi tar med både gammel og ny linjeId er slik at vi klarer å hente ut avganger nå for de gamle linjeIDene, og når skiftet skjer (15. desember), så klarer vi å hente ut nye avganger med de nye IDene uten å måtte gjøre noen kodeendringer og "passe på" at det funker. Det som skjer nå er at vi sender både gammel og ny ID inn til journey-planner, og får tilbake avganger på de linjene som faktisk har avganger.
Det var et annet litt mer tricky case som handlet om at de nye linjeIDene er allerede lagt inn som linjer i GraphQL, derav vi får to av samme linjer i prod nå:
Det bydde på to litt ulike tilnærminger. 
De to som er like er henholdsvis den gamle og den nye linjeIDen. 
1. Jeg kunne valgt å filtrert bort de …

chore(board): transform old line ids to new

---

tavla/app/(admin)/edit/[id]/compatibility.ts

Inni makeBoardCompatible ble whitelistedLines satt til undefined for alle tavler som ikke hadde whitelistedLines fra før av. Fikset at den ikke blir satt til noe hvis den ikke allerede finnes.
Funka lokalt for meg, filtreringen på gamle til nye linje-IDer skjer også i selve TileCard så trenger ikke ta høyde for de som ikke har satt whitelisted lines her.

fix(edit): bug where address could not be set

---

tavla/app/(admin)/components/CreateBoard/NameAndOrganizationSelector.tsx

Before:
- ![image](https://github.com/user-attachments/assets/95ecb331-8079-494a-af2b-3a255bec6f15)
After:
- ![image](https://github.com/user-attachments/assets/2dfdfc6d-27be-4655-9636-b4df9da7515c)

style(create): create modal changes

---

tavla/app/(admin)/edit/[id]/components/Footer/index.tsx
tavla/app/(admin)/edit/[id]/components/MetaSettings/Adress.tsx
tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
tavla/app/(admin)/organizations/components/DefaultColumns/index.tsx

Mye fra kortet som ikke kan gjøres pga designsystemet. Har økt størrelse og satt til å være ved siden av overskriften på kolonner.
Før:
Nå:
I org settings:

style(tooltips): increase size of tooltip icons and align with headings

---

tavla/src/Shared/components/TravelTag/index.tsx

style(edit): remove transportMode icons from platform dropdown on mobile

---

tavla/middleware.ts
tavla/next.config.js
tavla/package.json
tavla/pages/[id].tsx
tavla/src/Shared/utils/logger.ts
tavla/yarn.lock

Eksprimentell pr! Har lagt til:
- pakkene pino og pino-pretty
- logger.ts som en generell logger som alle filer kan bruke (som skal bruke samme severity-levels som GCP)
- middleware: logger alle requests og responses (har valgt ut noen felter, dette kan endres på). til nå logger denne BARE på tavlevisning
- egen log i selve tavlevisning for å få ut board-id og organization name. her kan det også fint legges på flere felter
Tanken er å få ut dette i dev for å sjekke om logger da dukker opp i dev-prosjektet i GCP. sannsynligvis vil det dukke opp i GKE, vi skriver til stdout (tror jeg)

feat(logging): add request logging to board page

---

tavla/app/(admin)/edit/[id]/components/MetaSettings/Adress.tsx

For å try/catche actions som utføres på serveren så må vi bruke handleSubmit istedenfor ren tradisjonell form-action. Det viser også [dokumentasjonen til next](https://nextjs.org/docs/pages/building-your-application/data-fetching/forms-and-mutations). 
Dette er en quick fix for å vise en annen toast dersom saveLocation failer. Vi burde gå opp sammen hvordan vi generelt bør håndtere error fra server i frontend.

feat(error): handle failed saveLocation

---

tavla/app/(admin)/organizations/components/DefaultColumns/actions.ts
tavla/app/(admin)/organizations/components/FontSelect/actions.ts
tavla/app/(admin)/organizations/components/MemberAdministration/CountiesSelect/actions.ts

La på revalidatePath på column, font og county select, så man ser de oppdaterte verdiene med en gang istedenfor å måtte refreshe siden

fix(organizations): add missing revalidatepath on org settings

---

tavla/pages/[id].tsx

Til vi vet hva vi skal logge, og hvordan vi skal gjøre det, så fjerner vi bare midlertidlig logging på tavlevisningen. Inntil videre fjerner vi ikke middlewaren, men har det som en todo å gjøre det hvis vi finner ut at vi ikke skal custom-logge noe fra løsningen vår.

chore(board): remove logging 

---

tavla/app/(admin)/hooks/useQuaySearch.ts
tavla/src/Shared/graphql/index.ts
tavla/src/Shared/graphql/queries/quaySearch.graphql
tavla/src/Shared/types/graphql-schema.ts

Fjerner koden som bruker journeyPattern til å slenge på "- Retning sentrum" på noen plattformer, da team data har bekreftet at disse ikke er pålitelige. Fjernet derfor også journeyPattern fra graphQL-spørringen, den ble ikke brukt til noe annet.
Ref. brukermeldt bug der "- Retning sentrum" på Kværner lå på feil plattform på Kværner, den ser nå sånn ut:

fix(edit): remove direction from platform selector

---

tavla/app/(admin)/organizations/components/Organizations.tsx
tavla/app/globals.css
tavla/tailwind.config.ts

style(organizations): change background color on card to grey

---

tavla/app/(admin)/components/TileSelector/utils.ts
tavla/app/(admin)/edit/[id]/actions.ts
tavla/src/Shared/graphql/index.ts
tavla/src/Shared/graphql/queries/quayCoordinates.graphql
tavla/src/Shared/graphql/queries/stopPlaceCoordinate.graphql
tavla/src/Shared/graphql/queries/walkingDistance.graphql

I dagens løsning støtter vi ikke ut å hente koordinater for multimodale stopp. Et multimodalt stopp er et stopp som har flere plattformer. F. eks er Oslo S og Jernbanetorget et multimodalt stopp. I spørringen i dag når man skal hente ut gåavstand, så henter man ikke ut koordinatene til multimodalen, men kordinatet til første quayen som ligger under multimodalen. 
Bakgrunn: hvis man har en tavle satt opp i RG5, så viser det at gåavstanden til Dronningens gate er 4 minutter og til Oslo S 3 minutter. Dette er veldig rart da Oslo S er lengre unna enn Dronningens gate. Se slack her: https://entur.slack.com/archives/C9QDFPPQV/p1723182790373569 og her: [Message in Slack](https://entur.slack.com/archives/C071P1WECR0/p1723117138779809).
- Skriver om walkingDistanceQuery til å ta inn `from` og `to` …

fix(board): use coordinates to get walking distance for multimodal coordinates

---

tavla/app/(admin)/boards/components/TagModal/actions.ts
tavla/app/(admin)/edit/[id]/actions.ts
tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
tavla/app/(admin)/edit/[id]/page.tsx
tavla/app/(admin)/utils/firebase.ts
tavla/src/Board/scenarios/Board/firebase.ts

Tre getBoard-funksjoner er nå kombinert til én.
I tillegg går det ikke lenger an å gå inn på en random tavle-url og få opp en tom tavle (tavla.entur.no/123), det gir nå 404-side. Obs: må kjøres opp med yarn build-start for å sjekke dette.

chore(edit): refactor three getBoard-functions to one common

---

tavla/app/components/ContactForm.tsx
tavla/app/components/actions.ts

Det å legge til e-post er optional. Grunnen til at vi vil ha med en checkbox er at vi vil at de aktivt skal ta et valg at e-posten ikke skal legges ved fordi vi vil _helst_ at folk faktisk skal legge den igjen.

feat(contact): make email optional in form

---

tavla/app/(admin)/components/HorizontalNavBar.tsx
tavla/app/(admin)/components/Login/index.tsx
tavla/app/(admin)/components/SideNavBar.tsx
tavla/app/(admin)/components/TopNavigation.tsx

Hamburger/sidemenyen vises igjen når skjermen er mindre enn 768px. Fikset også at linken for "Prøv Tavla" ikke ser ut som den er faded.

fix(sidenav): show hamburger meny on screen smaller than 768px

---

tavla/app/actuator/prometheus/route.ts
tavla/helm/tavla/values.yaml
tavla/package.json
tavla/yarn.lock

Installerer pakken prom-client og setter opp endepunktet /actuator/prometheus som viser default metrics, vi kan senere sette opp custom metrics. Neste steg er å få metrics inn i grafana. Metrics på endepunktet ser sånn ut i dag:
Vi har prøvd å følge guiden i Entur developer docs: https://enturas.atlassian.net/wiki/spaces/ESP/pages/1120960798/Metric+collection men litt usikker på om vi har gjort konfigurasjonen riktig med helm. @AlexanderBrevig hvis du har tid hadde det vært supert om du kunne ta en titt på denne PR-en og bekrefte at vi ikke mangler noe for at dette skal funke i dev og prod 😃

feat(monitoring): install prometheus and add /actuator/prometheus endpoint

---

.github/dependabot.yml

Det er mer hensiktsmessig å oppdatere pakker én gang i uka. Sikkerhetsoppdateringer kommer likevel så fort det er nye vulnerabilities. 
Interval "daily" er fin å ha i begynnelsen, men er nå ikke nødvendig lenger.
-> "weekly"
- Mandag
- 08:00

feat(dependabot): schedule dependabot weekly

---

tavla/app/(admin)/boards/components/Column/Name.tsx

Tavle-navn i tabellen på /boards er nå clickable på mobil

fix(boards): set board name to be link in table in mobile view

---

tavla/app/(admin)/boards/components/BoardTable/index.tsx
tavla/app/(admin)/components/IllustratedInfo/index.tsx
tavla/app/(admin)/organizations/components/Organizations.tsx

Endret ordlyd og lagt til opprett-knapp på tom organisasjons-side, så den matcher tom tavle-siden.

style(organizations): add button to empty org page

---

tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx

Når man trykker på "Avbryt"-knappen i TileCard (og har gjort endringer) åpnes bekreftelses-modalen hvor du får mulighet til å lagre en gang til. Trykker man avbryt igjen lagres ikke endringene.

fix(edit): cancel-button in TileCard triggers modal

---

tavla/README.md
tavla/helm/tavla/values.yaml
tavla/pages/[id].tsx
tavla/sentry.client.config.ts
tavla/sentry.edge.config.ts
tavla/sentry.server.config.ts
tavla/src/Board/scenarios/QuayTile/index.tsx
tavla/src/Board/scenarios/StopPlaceTile/index.tsx
tavla/src/Shared/graphql/utils.ts

Denne PR-en fikser sentry-konfigurasjonen vår så dsn-variabelen også er tilgjengelig på klientens browser (og vi får tak i feil derfra).
I tillegg legges det på en custom error-catching når fetch fra journeyplanner feiler, timer ut eller ikke returnerer noe data.
edit: legger også på custom feilmelding når server-side fetch feiler.
For å teste dette lokalt må du først:
- kommentere ut `enabled: process.env.NODE_ENV !== 'development',` fra de tre sentry-config-filene
- sjekke at localhost-feilmeldinger ikke er filtrert bort i sentry-prosjektet (inn på sentry web client)
- endre dsn-variabelnavnet på env.local til `NEXT_PUBLIC_SENTRY_DSN_URL`
så må du kræsje fetch, f eks ved å endre timeout-verdien til et veldig lavt tall.
Bør dukke opp i sentry:

feat(sentry): capture error in Sentry when departure fetch fails

---

tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
tavla/app/(admin)/edit/[id]/components/TileList/index.tsx

Fikser bug der det ikke gikk an å slette stoppested når whitelistedLines var satt, fordi codespace endringen gjorde at objektet i firebase ikke var lik tile-objektet hos klient. 
La på en sjekk som kan delvis fjernes etter 15. desember

fix(edit): allow removing tile after whitelistedLines is set

---

tavla/app/(admin)/edit/[id]/components/Footer/actions.ts
tavla/app/(admin)/edit/[id]/components/Footer/index.tsx
tavla/app/(admin)/edit/[id]/components/MetaSettings/Adress.tsx
tavla/app/(admin)/edit/[id]/components/MetaSettings/FontSelect.tsx
tavla/app/(admin)/edit/[id]/components/MetaSettings/Organization.tsx
tavla/app/(admin)/edit/[id]/components/MetaSettings/Title.tsx
tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
tavla/app/(admin)/edit/[id]/components/ThemeSelect/index.tsx
tavla/app/(admin)/organizations/components/CountiesSelect/index.tsx
tavla/app/(admin)/organizations/components/DefaultColumns/index.tsx
tavla/app/(admin)/organizations/components/FontSelect/index.tsx
tavla/app/(admin)/organizations/components/Footer/index.tsx
tavla/app/(admin)/utils/index.ts

- Lagt til at man viser en alert i stedet for toast.
- De ulike innstillingene i `MetaSettings.tsx` er også skilt ut i fire andre kompoenter: `Title.tsx`, `Address.tsx`, `Organization.tsx` og `FontSelect.tsx`. Synes det ble ryddigere sånn. Legger også opp til mer gjenbrukbarhet i fremtiden hvis vi vil gjøre noe her.
- I all hovedsak er det lagt på en `<FormError />` overalt, sammen med en `useActionState()`

feat(settings): show error alert to user if firebase fail in edit and organization

---

tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts

Tror en bug sneik seg med når sentry-PR-en ble merga inn.
Prøver å logge organisasjons-ID, men variabelen oid finnes ikke, så endrer til toOrganization

chore(MetaSettings): change sentry parameter from oid to toOrganization

---

tavla/app/(admin)/edit/[id]/compatibility.ts
tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx

Siden det er etter 15. desember, kan vi fjerne de delene av koden som skulle kjøre før switch-datoen.
- fjerner `SWITCH_DATE `og `NEW_LINE_IDS` som aldri brukes lenger
- fjerner if-sjekken på lines som var der for å håndtere case før 15. desember
- i `makeBoardCompatible`, switcher nå kun fra de gamle til de nye, heller enn å legge til begge som vi gjorde før.
Det funker nå fint å både laste inn gamle whitelistedlines, og å lagre nye (som lagres med nye id-er)
Legg merke til at filtreringen på lines som skjer i TileCard fortsatt må være der, virker som om både gamle og nye linjer fortsatt sender data når man spør 🤔 
altså: `lines = lines.filter((line) => !OLD_LINE_IDS.includes(line.id))`

fix(compatibility): remove unused code after codespace change

---

tavla/app/(admin)/boards/components/TagModal/actions.ts

This PR checks tags for all user board to check for duplicate tags.
When adding new tags for a board, we only check for duplicates for the current board and not every board a user has. Therefore, an user can add the tag "Privat" in board 1 and "privAT" in board two, and get two different tags with the same name (in uppercase).
- Added `getAllTags` to get all tags a user has created across their boards
- rename `fetchTags` to `fetchBoardTags` to highlight its use
When adding  tag to a new empty board named '_legg til org_':

fix(boards): check duplicate tags across all user boards

---

tavla/app/(admin)/edit/[id]/components/Footer/actions.ts
tavla/app/(admin)/edit/[id]/components/Footer/index.tsx
tavla/app/(admin)/edit/utils.ts
tavla/app/(admin)/organizations/components/Footer/actions.ts
tavla/app/(admin)/organizations/components/Footer/index.tsx
tavla/app/(admin)/utils/index.ts

In Organization
In Board
We previously stored footers with only whitespaces in our db and we want to avoid that.
- Show the user a warning message when they try to store a footer containing only whitespace (board and organization). Our designer has approved the visual changes 🎨 
- If the footer is empty, delete the field (board and organization) in out db. In board, the override is still stored if the footer is empty
1. When org and board footer is set, the switch turns off for a couple of seconds after override is set, before returning to its intended state (similar to fontsize ).  
Thanks

fix(footer): no whitespace text

---

tavla/pages/[id].tsx
tavla/src/Board/scenarios/QuayTile/index.tsx
tavla/src/Board/scenarios/StopPlaceTile/index.tsx

Vi ønsker å konsekvent kun logge feil til Sentry på nederste nivå (dvs. ved firebase- eller graphQL-kall). Denne PR-en fjerner derfor "dobbel" logging, som lå i index- eller page-filer.
- fjerner kode vi la til i tavlevisningen for å feilsøke tidligere - inkludert Sentry-logging om noe går galt i getServerSideProps (for dette skal heller fanges der firebase-kallet skjer)
- fjerner Sentry-logging om graphQL-spørring returnerer "tom" data. Vi har heller logging på om en feil oppstår tidligere i prosessen.

chore(sentry): remove duplicate sentry-logging

---

tavla/app/(admin)/boards/page.tsx
tavla/app/(admin)/components/CreateBoard/NameAndOrganizationSelector.tsx

---
Spurt om av en fylkesoperatør. To småplukk i én.
Legger til teller over board-tabellen:
Endrer overskrift:

feat(boards): add board counter and change modal heading

---

tavla/src/Board/scenarios/Board/index.tsx
tavla/src/Board/scenarios/QuayTile/index.tsx
tavla/src/Board/scenarios/StopPlaceTile/index.tsx

---
Som vi snakket med SJ om, kan vi forbedre tavlevisningen på mobil slik at den ikke viser kun én avgang på hvert stoppested når man har mange stoppesteder (som de har). Ved å gjøre denne endringen styrker vi samarbeidet vårt med en viktig partner av Entur.
Gjort Board-komponenten scrollable når den tar opp over 100% av skjermhøyden. Hver tile vil minimum ta opp 30 view height, men mer om man har færre tiles.
Board med mange tiles (scrollbar på siden, men den synes ikke her):
Board med få tiles ser ut som før og kan ikke scrolles:

feat(board): add scrolling in mobile view for boards with many tiles

---

tavla/app/(admin)/actions.ts
tavla/app/(admin)/components/Delete/actions.ts
tavla/app/(admin)/components/Login/actions.ts
tavla/app/(admin)/edit/[id]/page.tsx
tavla/app/(admin)/organizations/page.tsx
tavla/app/(admin)/utils/firebase.ts
tavla/app/api/upload/route.ts
tavla/app/demo/page.tsx
tavla/app/layout.tsx
tavla/app/page.tsx

---
1) Det skal ikke være mulig å "stjele" noens bruker ved å få tak i session cookie etter at de har logget ut. Ved å invalidere token i firebase auth sikrer vi at det ikke kan skje
2) Vi har mange mulige måter å sjekke om en bruker har tilgang til en side/handling eller ikke. Vi ønsker å gjøre dette på samme måte overalt.
Vi revoker en brukers personlige token på utlogging. Dvs at dersom man har tilgang på noen andres session cookie, kan man ikke lenger sette den manuelt og være innlogget som dem etter at de selv har logget ut. En konsekvens av dette er at dersom du nå logger ut på ett device (eller i én browser), logges du ut av alle
Reduserer fra tre metoder å sjekke om bruker er logget inn, til én:
- `verifySession`-metoden (som vi tidligere brukte rundt om kring) kalles kun inne i …

chore(login): force firebase to invalidate token and refactor cookie functions

---

tavla/pages/[id].tsx
tavla/public/site.webmanifest

---
Vår kontaktperson fra Chilligroup ønsker å ha lik bakgrunnsfarge på mobilvisning av tavla, så det blir en bedre brukeropplevelse for deres sluttbrukere.
La til bg color på body i pages, som er basert på board sitt theme. Det gjør at hele siden har lik farge på mobilvisning

style(board): full screen bg color on mobile

---

tavla/app/(admin)/actions.ts
tavla/app/(admin)/boards/components/TagModal/actions.ts
tavla/app/(admin)/edit/[id]/actions.ts
tavla/app/(admin)/edit/[id]/components/Footer/actions.ts
tavla/app/(admin)/edit/[id]/components/MetaSettings/actions.ts
tavla/app/(admin)/edit/[id]/components/RefreshButton/actions.ts
tavla/app/(admin)/edit/[id]/components/ThemeSelect/actions.ts
tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
tavla/app/(admin)/edit/[id]/page.tsx
tavla/app/(admin)/organizations/[id]/page.tsx
tavla/app/(admin)/organizations/components/CreateOrganization/actions.ts
tavla/app/(admin)/organizations/components/MemberAdministration/actions.ts
tavla/app/(admin)/utils/firebase.ts
tavla/app/(admin)/utils/index.ts
tavla/src/Shared/types/settings.ts

---
Vi har i dag feltene "editor" på brukere og "editors" på organisasjoner som alltid er tomme lister. Opprinnelig tenkte man at man skulle skille på en editor og owner av en tavle, men funksjonaliteten har ligget ubrukt i 10 mnd. Vi vil fjerne for å redusere teknisk gjeld og gjøre koden mer forståelig.
Når en organisasjon opprettes, opprettes ikke editors-feltet. Editor/editors fjernet fra sjekken på om en bruker har tillatelse til å endre på en tavle eller organisasjon, og feltene er fjernet fra tilsvarende type-deklarasjoner.

chore(user): remove unused editor field form user and organization

---

tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
tavla/app/(admin)/edit/[id]/page.tsx

---
Vi endrer slik at siden oppfyller UU-krav
- Endret aria-label på knapp så den matcher den faktiske teksten på knappen
- Lagt på aria-label på div rundt preview av tavla så det går an å gå forbi den

fix(edit): change wrong aria-label and add label to preview div

---

tavla/app/(admin)/edit/[id]/components/ActionsMenu/index.tsx
tavla/app/(admin)/edit/[id]/components/Buttons/Copy.tsx
tavla/app/(admin)/edit/[id]/components/DuplicateBoard/index.tsx
tavla/app/(admin)/edit/[id]/page.tsx

---
Lettere for folk å se tavla URLen
Lagt til at man kan se URLen i en copyable text, fjernet knappen, og flyttet ut slett-tavle-knappen.

feat(edit): show tavle url in copyable text

---

tavla/app/(admin)/edit/[id]/actions.ts
tavla/app/(admin)/edit/[id]/components/MetaSettings/WalkingDistance.tsx
tavla/app/(admin)/edit/[id]/components/MetaSettings/index.tsx
tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
tavla/app/demo/components/ExpandableInformation.tsx
tavla/src/Board/scenarios/Table/components/WalkingDistance.tsx

---
Mange bruker adresse og gangavstand feil, og skjønner ikke at man må inn i TileCard for å skru på gangavstand for hver enkelt tile.
Vi flytter ut, da det ikke er noe poeng i å sette adresse uten å sette gangavstand.
- Gangavstand erstatter Adresse i MetaSettings.
- Når adresse settes, legges gangavstand til alle tiles automatisk. 
- Trenger ikke lenger visible-felt på walkingDistance-objektet: det opprettes og slettes når adresse settes eller fjernes.
- De som tidligere har satt adresse men ikke gangavstand vil _ikke_ plutselig få opp gangavstand, men om de lagrer TileCard eller oppdaterer adresse vil de det.

feat(edit): move walking distance to meta settings

---

tavla/app/(admin)/edit/[id]/components/CompressSurvey/index.tsx
tavla/app/(admin)/edit/[id]/page.tsx
tavla/app/(admin)/utils/index.ts
tavla/helm/tavla/values.yaml
tavla/next.config.js

---
Vi vil undersøke om folk ønsker muligheten til å komprimere innholdet før vi faktisk utvikler funksjonaliteten.
- Legger til "Komprimer Tavle" som en ekstra innstilling:
- Klikk på lagre-knapp åpner følgende modal, lenket til en posthog survey:
- Resultatene av undersøkelsen finnes under "Surveys" i Posthog dashboard
Denne PR-en er knyttet til en hypotese, når den er prodsatt starter vi måling. Vi må huske å sette et vindu for hvor lenge vi vil måle

feat(edit): fake door with survey for compress board setting

---

tavla/app/(admin)/edit/[id]/actions.ts
tavla/app/(admin)/edit/[id]/components/TileCard/actions.ts
tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
tavla/app/(admin)/edit/[id]/components/TileList/index.tsx
tavla/app/(admin)/edit/[id]/components/ViewType/actions.ts
tavla/app/(admin)/edit/[id]/components/ViewType/index.tsx
tavla/app/(admin)/edit/[id]/page.tsx
tavla/app/demo/components/ExpandableInformation.tsx
tavla/app/demo/page.tsx
tavla/src/Board/scenarios/Board/index.tsx
tavla/src/Board/scenarios/CombinedTile/index.tsx
tavla/src/Board/scenarios/Table/components/Destination.tsx
tavla/src/Board/scenarios/Table/components/Line/index.tsx
tavla/src/Board/scenarios/Table/components/Platform.tsx
tavla/src/Board/scenarios/Table/components/RealTime.tsx
tavla/src/Board/scenarios/Table/components/Time/AimedTime.tsx
tavla/src/Board/scenarios/Table/components/Time/ArrivalTime.tsx
tavla/src/Board/scenarios/Table/components/Time/ExpectedTime.tsx
tavla/src/Board/scenarios/Table/index.tsx
tavla/src/Shared/graphql/fragments/departure.graphql
tavla/src/Shared/graphql/index.ts
tavla/src/Shared/hooks/useQuery.ts
tavla/src/Shared/types/column.ts
tavla/src/Shared/types/settings.ts
tavla/src/Shared/types/tile.ts

---
Vi har fått flere henvendelser som handler om det er mulig å slå sammen stoppesteder til ett stoppested. Det er flere plasser hvor det ligger stoppesteder ganske nærme hverandre, og man ønsker å kunne slå disse sammen i stedet for å ha to separate tiles. I tillegg er det flere som har uttrykt at de ønsker å kunne se alt som går i en spesifikk retning, så vi har en hypotese om at ved å klare å kombinere flere plattformer så vil dette problemet også blir løst i større grad. 
OBS: i første omgang er det kun mulig å enten kombinere alle stoppestedene i tavla, eller ingen, men det er lagt opp i databasen at man kan ha flere kombinerte tiles. 
- Det skal nå være mulig å velge visningstype i innstillinger. 
- Databasen har fått et nytt felt: `combinedTiles: [{ids: }]` hvor man legger inn …

feat(board): support for combining tiles

---

tavla/app/components/Banner.tsx
tavla/app/layout.tsx

---
Ny funksjonalitet om kombinerte stoppesteder ligger litt gjømt nede i innstillinger på rediger tavle. Dette er et forsøk på å promotere det i større grad.
- Lagt til banner-komponenten fra design-systemet. Vi er blitt enige om at denne skal ligge på alle sider så lenge man er innlogget. 
- Lagrer i localstorage om man har dismissa banneren eller ikke
- Må ha en `<ClientOnly>` wrappa rundt fordi banneren bruker en tooltip som gir duf hydration error

feat(banner): add banner to promote new functionality for combined tiles

---

tavla/app/(admin)/components/TileSelector/index.tsx
tavla/next.config.js

---
Vi vil få feedback på hvordan folk synes det er å opprette tavler.
- legger til posthog event for når tile er lagt til. I posthog vises da en survey til bruker første gang de gjør denne handlingen (så lenge de er på edit-siden, ikke demo, forhåpentligvis).
- Skjema i posthog:
Går videre til fritekstfelt med forklaring
OBS: inntil videre er den bare i localhost, dev og prod har csp som blokkerer

feat(edit): add posthog survey after created board

---

tavla/app/unsupported-browser/page.tsx
tavla/package.json
tavla/pages/[id].tsx
tavla/src/Shared/utils/browserDetection.ts
tavla/yarn.lock

---
Vi ønsker å gi bedre informasjon til brukere om hvorfor tavla muligens ikke funker, og forhåpentligvis redusere antall henvendelser om at tavla ikke virker
- Lagt til egen fil med browser-funksjoner igjen (ble fjernet for en stund siden)
- Bruker redirectes til egen side om browser er for gammel
- Browserversjoner som redirectes er de UNDER chrome 45, firefox 49, safari 9.1. Merk at vi egentlig heller ikke støtter et par versjoner over disse (feks er chrome 49 det laveste vi støtter), men jeg setter litt lavere grenser for å ta hensyn til mulige forskjeller i OS osv.
Gammel browser-siden har jeg sjekket at vises helt ned til chrome 39.

feat(board): redirect to custom info-page if client browser is too old

---

tavla/pages/[id].tsx

---
FRAM sier flere av deres tavler kræsjer, vi har hatt en brå økning i antall 307 (redirect) requests siden prodsettingen i går

fix(board): remove redirect on unsupported browser

---

tavla/app/(admin)/components/Login/Create.tsx
tavla/app/(admin)/components/Login/Email.tsx
tavla/app/(admin)/components/Login/Google.tsx
tavla/app/help/components/Questions.tsx
tavla/next.config.js
tavla/package.json
tavla/yarn.lock

---
Vi vil senke terskelen for å opprette bruker på tavla, og innlogging med google gjør at man bypasser problemet med verifiseringsmail som tar lang tid
Lagt til "Logg inn med google"-knapp på modal for innlogging og ny bruker.
Trykk på knappen gir popup-vindu hvor bruker kan velge google-kontoen sin. De logges så inn, og redirectes til /boards som vanlig.
OBS: firebase tilbyr automatisk lenking mellom kontoer med samme e-post som er logget inn med to forskjellige metoder, så det trenger ikke vi å tenke på.
Kjent feil:
- vi viser "Vent litt.." imens bruker har popup åpen, denne forsvinner ikke med en gang når bruker lukker popup. Dette er en kjent firebase auth feil.

feat(login): add google SSO

---

tavla/app/(admin)/edit/[id]/components/TileCard/index.tsx
tavla/src/Board/scenarios/CombinedTile/index.tsx

---
Vi tror at siden stoppestedsnavnet ligger i selve tabellen, så trengs det ikke å vises på toppen heller.

feat(board): remove heading on combined board

---

tavla/app/(admin)/components/TileSelector/index.tsx
tavla/app/(admin)/components/TileSelector/utils.ts
tavla/app/(admin)/edit/[id]/page.tsx
tavla/app/demo/components/DemoBoard.tsx

---
Redusere antall klikk med 2 for folk som skal lage tavle for et stoppested.
- når platform-select er tom tilsvarer dette "vis alle"
obs: annen mulig løsning er å sette dropdownen til "vis alle"-verdien med en gang, men det viste seg å være vanskelig (kan ikke sette default-valg enkelt i dropdown-komponenten)
obsobs: hele tileselector-komponenten er jo HELT krise, alt av form handling skjer på en annen måte enn det vi gjør ellers

feat(edit): submit empty platform select to show all platforms

---

tavla/src/Board/scenarios/Table/components/Time/ExpectedTime.tsx
tavla/src/Shared/utils/time.ts

---
På møtet med Fram i sted fikk vi innspill på at tidene noen ganger er litt "optimistiske" (som de hadde fått fra sine brukere). F. eks at når det sto at det var 3 minutter til den gikk, så var det faktisk 2 minutter og noen sekunder. 
Dette er forståelig at skjer siden vi kun henter avganger hvert 30 sekund - dette er ikke noe vi tar høyde for i koden i dag. 
F. eks la oss si at det er 2 minutter og 1 sekund (02:01) til avgangen går. Som koden er i dag, så vil man da runde nedover til 2 minutter. Men dette vil være misvisende om man ser på skjermen rett før det er en ny fetch av avganger, da vil pr def være 01:31 minutter til avgangen går, og ikke 2 minutter - dermed vil man ikke rekke avgangen om man tenker man har 2 minutter på seg, men egentlig så er den 30 sekunder mindre. Det er …

fix(time): show adjusted time to avoid optimistic times

---

tavla/app/(admin)/boards/components/Column/Tags.tsx
tavla/app/(admin)/boards/components/Column/index.tsx
tavla/app/(admin)/boards/utils/index.ts
tavla/app/(admin)/utils/types.ts
tavla/app/globals.css
tavla/src/Shared/types/meta.ts

---
Grunnen til at vi gjør det er at vi ønsker å prodsette, men AtB vil gjerne ha tid til å omorganisere tavlene sine i mapper basert på de tagsa de har. Derfor gjeninnfører vi tags, men det er ikke mulig å fjerne eller legge til noen tags. Denne PRen skal bli revertet på mandag igjen når de har fått plasser tavlene sine i riktige mapper, og vi ikke lengre trenger denne funksjonaliteten. 
Lagt ved merkelapper som en kolonne i tabellen.

chore(tags): add tags to board table

---

tavla/app/(admin)/boards/components/Column/Delete.tsx
tavla/app/(admin)/boards/utils/actions.ts
tavla/app/(admin)/components/CreateOrganization/actions.ts

---
Det er ikke intuitivt at man redirectes til /boards om man står i en spesifikk mappe og sletter en tavle.
Når man nå sletter en tavle i en mappe, så redirectes man til denne mappen, og ikke til oversikten over alle tavler og mapper.

fix(boards): redirect to specific folder on create or delete

---

tavla/app/(admin)/boards/[id]/BreadcrumbsNav.tsx
tavla/app/(admin)/boards/[id]/page.tsx
tavla/app/(admin)/edit/[id]/page.tsx
tavla/package.json
tavla/src/Shared/styles/reset.css
tavla/yarn.lock

---
Enklere å navigere rundt for brukeren.
Breadcrumbs navbaren vises kun om man er inne på en tavle, en speisfikk mappe eller en tavle i en mappe.

feat(boards): add breadcrumbs navbar

---

tavla/app/(admin)/components/Login/Email.tsx

---
Vi ønsker at nettsiden skal se fin og funksjonell ut, også på mobil. Ved å fikse at knappene ikke overflower og overlapper bidrar vi til det.
- La til kolonne-sortering på knappene på små skjermer
|Før|Etter|
|-----|-----|
|![image](https://github.com/user-attachments/assets/9c941ec5-5b64-4640-aa1d-0bb8eed7ede8)|![image](https://github.com/user-attachments/assets/e62efdac-e98b-46b1-890f-3ec5b5bf9460)|

fix(login): fix login buttons overflowing on mobile

---

tavla/app/(admin)/boards/[id]/page.tsx
tavla/app/(admin)/components/CreateBoard/NameAndOrganizationSelector.tsx
tavla/app/(admin)/components/CreateBoard/actions.ts
tavla/app/(admin)/components/CreateBoard/index.tsx
tavla/app/(admin)/edit/[id]/components/Settings/actions.ts
tavla/app/(admin)/edit/[id]/components/Settings/components/Organization.tsx
tavla/app/(admin)/edit/[id]/components/Settings/index.tsx
tavla/app/(admin)/hooks/useOrganizations.ts
tavla/app/(admin)/utils/index.ts

---
Gjøre det enklere for brukere å flytte og velge en mappe ved opprettelse av tavle. Nå er det ikke mulig å _ikke_ velge en mappe. 
- Fjernet sjekkboksen for om det skal være en privat tavle -> det er erstattet med et valg i dropdownen som heter "Ingen mappe"
- Når man står i en spesifikk mappe, så er dette default valgt når man oppretter ny
- Når man står ved oversikten, så er default "Ingen mappe" valgt
| Før | Etter |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/173a22bf-dd98-440c-95a1-c7adcbbcac4b) | ![image](https://github.com/user-attachments/assets/52215083-5d77-44da-813c-7b1ca604fc5c) |

feat(folder): folder dropdown with all options

---

tavla/app/(admin)/boards/components/Column/Delete.tsx
tavla/app/(admin)/boards/utils/actions.ts
tavla/app/(admin)/utils/firebase.ts
tavla/pages/[id].tsx
tavla/src/Board/scenarios/Board/firebase.ts

---
Var ikke mulig å slette en tavle fra rediger-siden. Grunnen til dette var at den trodde `bid` var en `oid`, så det ble feil. Nå henter jeg organisasjonen basert på `bid` i stedet for å hente det fra slugs i URLen. 
- Henter organisasjonen/mappen basert på board-id som kommer inn, og ikke basert på URLen.
- Renamet en funksjon

fix(edit): delete board 

---

tavla/app/demo/components/ExpandableInformation.tsx

---
Ved å bytte til button fra div så blir den tab-fokuserbar og plukkes også opp som et interaktivt element for skjermleser
(fokus-farge matcher ikke resten av komponentene, men det gjør heller ikke entur-ikonet)
Byttet til button fra div i expandableinformation

fix(demo): make expandable focusable for a11y

---

tavla/app/(admin)/boards/components/Column/Name.tsx

---
Designet har mer luft mellom ikon og navn på elementet fordi det ser bedre ut. 
La til 4 px mer luft mellom ikon og navn på element. 
|Før|Etter|
|---|-----|
|![image](https://github.com/user-attachments/assets/006d8e36-9cb5-44d2-aeb3-7d26b8fc6800)|![image](https://github.com/user-attachments/assets/063d74e7-e447-4de2-a061-28429fe5a317)|

fix(oversikt): add space between icon and name

---

tavla/package.json
tavla/yarn.lock

---
Lage en baseline for OKR om å finne ut hvor greit det var å lage en tavle.
- Denne skal kun vises når man er inne på /rediger siden for en tavle, og ikke på /demo. 
- Den skal vises når man legger til et stoppested én gang. 
OBS! Vi må huske å bytte denne til /rediger i posthog-surveyen.

chore(rediger): add survey

---

tavla/next.config.js

---
Vi vil at brukere som har bokmerket oversiktssiden fremdeles skal sendes til oversikten selv etter endring av slug-navn. 
La til en permanent redirect i next.config.js

chore(oversikt): add redirect

---

tavla/app/(admin)/oversikt/page.tsx
tavla/app/(admin)/oversikt/utils/actions.ts
tavla/app/(admin)/oversikt/utils/index.ts

---
Fint å se hvor mange tavler man har
Lagde en funksjon som teller antall tavler i mapper og legger det sammen med private tavler.
|Før|Etter|
|---|-----|
|![image](https://github.com/user-attachments/assets/236fc28a-186e-4c5f-b253-b56d9346daca)|![image](https://github.com/user-attachments/assets/4f58b8db-3242-48e6-9278-04eebd2ebde2)|

feat(oversikt): add a count of all boards belonging to user

---

tavla/package.json
tavla/yarn.lock

---
Det er en sårbarhet som er funnet i versjonen vi har som handler om at man kan bypasse autorisasjon i middleware: [se her](https://sec.okta.com/articles/nextjs-CVE-202529927/). Vi har ikke middleware, men det kan være fint å oppgradere likevel slik at vi patcher sårbarheten og slik at vi ikke "glemmer" om vi plutselig skal ha autorisering i middleware i fremtiden. 
Release notes til Next 15.2: https://nextjs.org/blog/next-15-2
Ingenting her som skal tilsi en forandring for vår del.
- Oppgradert til Next 15.2.3
- Linting av package.json filen

feat(next): upgrade to next 15.2.3

---

tavla/package.json

---
Kommandoen `next lint --fix && prettier .` kjørte hos meg bare i en evig loop med veldig mye overload av feedback i terminalen. Etter å ha konferert litt med stackoverflow og chatteren viser det seg at denne kommandoen bare printer alle endringene. 
Ved å legge på `--write` på slutten fikser kommandoen at hver fil blir formatert riktig og ferdig før linteren kjører på videre.

fix(): fix cleanup commandos

---

tavla/app/(admin)/mapper/[id]/rediger/page.tsx
tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/Footer.tsx
tavla/app/(admin)/tavler/[id]/rediger/components/Settings/index.tsx

---
Vi vil på sikt fjerne alle infomeldinger på mappenivå. På tavlenivå har vi lagret infomeldinger som kan ha en `override` skrudd på, slik at man bruker mappens infomelding. Vi vil fjerne muligheten til å sette en infomelding på mappenivå, samtidig som vi beholder `override`-logikken før vi migrerer over feltene i databasen. Dette for å forhindre at migreringen potensielt blir ufullstendig. 
Fjernet `footer`-funksjonalitet på mappenivå, og fjernet muligheten til å toggle hvilken infomelding som skal vises i tavleredigeringen. 
| bilde | bilde |

chore(): remove folder footer

---

tavla/app/(admin)/oversikt/components/Column/Actions.tsx
tavla/app/(admin)/oversikt/components/Column/Delete.tsx
tavla/app/(admin)/oversikt/components/Column/Move.tsx
tavla/app/(admin)/oversikt/utils/actions.ts
tavla/app/(admin)/tavler/[id]/rediger/components/Settings/actions.ts
tavla/package.json
tavla/yarn.lock

---
Gjøre det enkelt for folk å flytte tavler.
- Mulighet for å flytte en tavle direkte i tabellen.
- Laget en modal med "flytt" som parameter -> her kan man bla seg gjennom mappene man har
- Oppdaterte entur-pakke i samme slengen
| ![image](https://github.com/user-attachments/assets/a31f1738-d147-4612-9216-acd429a162af) | ![image](https://github.com/user-attachments/assets/64b1c618-65a3-4124-a9c9-5a3a4a7b874c) |

feat(tabell): move board

---

tavla/app/(admin)/oversikt/components/Column/Move.tsx
tavla/src/Shared/styles/reset.css

---
Når listen av mapper ble lang, så vistes de ikke i modalen. Det gikk heller ikke an å scrolle i listen.
- La til en generell styling i `reset.css` på dropdown-containeren. Denne sørger for at dropdownenlisten alltid vil ligge _under_ selve dropdownen, som igjen fører til at det er mulig å scrolle i dropdownen og i modalen.
| ![image](https://github.com/user-attachments/assets/6508e73b-6c5e-49bc-b357-05868bf0e285) | ![image](https://github.com/user-attachments/assets/d2a6f5c4-011b-4448-8500-71929cf3f939) |

style(modal): show long dropdown

---

tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/utils.ts

Potential fix for [https://github.com/entur/tavla/security/code-scanning/1](https://github.com/entur/tavla/security/code-scanning/1)
To fix the issue, we need to rewrite the regular expression to avoid overlapping ranges and explicitly define the intended character set. Instead of using `a-å` and `A-Å`, we can explicitly list all the characters in the Norwegian alphabet, including both uppercase and lowercase letters. This ensures that the regular expression is unambiguous and matches only the intended characters.
The updated regular expression will explicitly list the characters: `a-zæøåA-ZÆØÅ`.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore(tilecard): fix overly permissiv regex range

---

tavla/app/(admin)/components/Delete/index.tsx
tavla/app/(admin)/mapper/[id]/page.tsx
tavla/app/(admin)/mapper/components/MemberAdministration/RemoveUserButton.tsx
tavla/app/(admin)/oversikt/components/Column/Delete.tsx

---
Iterasjon 3 av mapper.
- Lagt til en slett knapp på spesifikk tavle side
- Alle funksjonalitet fantes fra før.
| ![image](https://github.com/user-attachments/assets/ff2ad1e5-ab47-44d1-869c-b56900d2545f) | ![image](https://github.com/user-attachments/assets/ecd4bd9e-cb09-47db-ae80-cdeb61b5159e) |

feat(mappe): add delete button

---

tavla/app/(admin)/components/TileSelector/index.tsx

Forbedre brukeropplevelsen til brukeren 
https://github.com/user-attachments/assets/0059f500-8364-4656-92be-148828d13219
https://github.com/user-attachments/assets/3851df13-ba4a-40dd-a486-a1c436eca471

fix(rediger): remove written input when select element is selected

---

tavla/app/(admin)/components/CreateBoard/NameAndOrganizationSelector.tsx

Fjern autocomplete der det er unødvendig slik at ikke brukeren tenker informasjonen lagres/hentes fra andre steder

fix(opprett tavle): remove autocomple on tavle-name

---

tavla/app/(admin)/components/CreateBoard/index.tsx
tavla/app/(admin)/mapper/[id]/page.tsx
tavla/app/(admin)/oversikt/components/EmptyOverview.tsx
tavla/app/(admin)/oversikt/page.tsx
tavla/app/help/components/Questions.tsx

Bedre brukeropplevelse - det skal ikke være mulig å søke eller se tabellen når listen er tom. Hvis listen er tom så viser vi en infomelding som sier at det er tomt her. 
| <img width="1727" alt="Screenshot 2025-05-14 at 14 47 39" src="https://github.com/user-attachments/assets/227b5499-f6c5-4ee7-9796-4fb4f3c25849" /> | <img width="1728" alt="Screenshot 2025-05-20 at 08 57 55" src="https://github.com/user-attachments/assets/e9546f32-0feb-44d7-bf1c-1cb02ee534de" /> |
| <img width="1728" alt="Screenshot 2025-05-15 at 13 09 23" src="https://github.com/user-attachments/assets/005dbd9a-3ce1-429a-92b0-c3ee2cb5a825" /> | <img width="1728" alt="Screenshot 2025-05-20 at 08 58 16" src="https://github.com/user-attachments/assets/08a6fd30-dd53-4615-b0e8-4ba1ca321fd5" …

chore(oversikt/mapper): add empty table state

---

tavla/app/(admin)/components/SideNavBar.tsx

Fjerne feilmelding i Sentry som dukker opp når brukere trykker på lukk i mobilmenyen

fix(menu): changed from close to setIsOpen(false)

---

tavla/app/providers.tsx
tavla/sentry.client.config.ts

Vi vil ikke samle inn data fra brukeren mens vi venter på å få implementert cookie-consent, så vi disabler sentry og posthog.

chore(): disable tracking while waiting for cookies

---

tavla/src/Shared/components/Clock/index.tsx

Klokken går feil på noen tavler - brukerinnspill

fix(clock): add timezone and format

---

tavla/app/help/components/Questions.tsx

I FAQ-siden oppgir vi at vi støtter nettlesere helt ned til Safari 8.1, dette stemmer ikke.
Endret fra "Safari 8.1" til "Safari 10.1" 🤓

chore(faq): update safari version

---

tavla/migrations/scripts/001_migrate_footer.py
tavla/migrations/scripts/002_read_tile_column_count.py
tavla/migrations/scripts/init.py
tavla/migrations/scripts/test.py

Vi ønsker å flytte en del av dokumenteringen av migreringsjobbene fra Confluence tettere opp til koden. Det gjør det lettere å forholde seg til det tekniske på ett sted, og det teoretiske på et annet sted. 
Lagt til docstrings for bedre dokumentering av bakgrunnen for hver migreringsjobb (og script). 
Lagt til flere kommentarer i selve koden. 
-  [x] Skal vi ha med datoer??
-  [x] Se igjennom kommentarer her: https://enturas.atlassian.net/wiki/spaces/TT1/pages/5358420081/Migrere+databaser

chore(migrations): document migration scripts

---

tavla/src/Board/scenarios/Table/components/Destination.tsx
tavla/src/Board/scenarios/Table/components/Situation/index.tsx
tavla/src/Board/scenarios/Table/components/TableRow/index.tsx

Destinasjon i Tavla kuttes horisontalt på topp og bunn
| <img width="1371" alt="Screenshot 2025-05-26 at 10 01 40" src="https://github.com/user-attachments/assets/2b133967-6378-4292-8d96-7ce638fa8154" /> | <img width="1364" alt="Screenshot 2025-05-26 at 10 00 22" src="https://github.com/user-attachments/assets/3e3be3c9-673b-4da0-a20c-1a5b8ea8c807" /> |

fix(): text in tavla is no longer cut

---

tavla/src/Board/scenarios/Table/components/TableHeader/index.tsx
tavla/src/Board/scenarios/Table/components/Time/ExpectedTime.tsx
tavla/tailwind.config.ts

Bokstaver i destinasjonsnavn som går inn i kjelleren blir kuttet på bunnen, så vi vil øke lineheight med litt der det skjer. Testet det på andre tekststørrelser og det ser ikke ut som det var nødvendig (vet ikke hvorfor).
Testet med 1.05em og det ble ikke bra nok, så 1.1em it is. 
Så også i firefox at Innstilt fløt inn i oppsatt tid, så endret den linjehøyden fra sm til base også.
| ![image](https://github.com/user-attachments/assets/7a71d396-e103-4cee-a200-a53dfe3a222a) | ![image](https://github.com/user-attachments/assets/6963ca25-3418-446a-bd87-a8ced0150b14) |
|<img width="259" alt="image" src="https://github.com/user-attachments/assets/e9d9ce26-04e4-4a59-a8e2-6ca7fc869b20" />|<img width="246" alt="image" …

chore(): change lineheight for base font size and switch to base for cancelled-text

---

tavla/src/Board/scenarios/CombinedTile/index.tsx
tavla/src/Board/scenarios/Table/components/Destination.tsx
tavla/src/Board/scenarios/Table/index.tsx

Vi ønsker ikke å vise avvik som allerede vises under stoppested/plattform for å forhindre rot. Derfor skal en filtreringsfunksjon fjerne de fra situasjonsobjektet til en destinasjon (nå) og en hel tavle (senere). 
Slår også sammen situasjonsobjekter ved kombinert tavle om de deler ID og slår sammen origin. Trodde jeg kunne bruke den nye filtreringsfunksjonen til dette derfor gjorde jeg det her hehe
| <img width="1490" alt="image" src="https://github.com/user-attachments/assets/a082863d-9a7e-44b6-8c71-6b2f3aefb150" /> | <img width="1490" alt="image" src="https://github.com/user-attachments/assets/42861fb5-a7b4-4ab1-99fd-89deeae5814f" /> |
|<img width="1490" alt="image" src="https://github.com/user-attachments/assets/5bfe9f9e-c29e-4dd7-9d1e-46dfbeda40ae" …

feat(tavle): filter out already shown situations from destinations

---

tavla/src/Board/scenarios/Table/components/Destination.tsx
tavla/src/Board/scenarios/Table/components/Platform.tsx

Hadde ikke fikset alle kolonnene når jeg håndterte problemet med tekstoverflow, men dette skal være den siste kolonnen. La til riktig linjehøyde og håndtering av overflow. 
Endret også "Plattform" til "Plf." som tittel på kolonnen fordi det irriterer meg at det tar opp så voldsomt mye plass, og dette er det Ruter bruker i sin løsning så det burde gå ganske greit (forhåpentligvis). Kan endre tilbake om vi finner ut at folk ikke forstår hva det er. 
| <img width="1696" height="1266" alt="image" src="https://github.com/user-attachments/assets/77efb6f4-aff3-4065-a03a-86d2f65c8975" /> | <img width="1696" height="1266" alt="image" src="https://github.com/user-attachments/assets/845ed1d7-0535-43c7-8bb6-75cb86f91332" /> |

fix(tavle): add line spacing and text overflow handling for stopplace column

---

tavla/src/Board/scenarios/CombinedTile/index.tsx
tavla/src/Board/scenarios/QuayTile/index.tsx
tavla/src/Board/scenarios/StopPlaceTile/index.tsx
tavla/src/Board/scenarios/Table/components/Situation/index.tsx
tavla/src/Board/scenarios/Table/components/StopPlaceDeviation/index.tsx
tavla/src/Board/scenarios/Table/index.tsx

Jeg forsto ikke hvorfor dersom det er inkludert origin for en situasjon at den skulle få mer spacing på topp og bunn selv om det var jeg som la inn stylingen for en uke siden. Da det ble lagt inn var det kun kombinerte tavler som skulle ha origin, noe som ikke er tilfellet lengre. Så jeg lagde en separat komponent for situasjoner som skal ligge på kombinerte tavler da den trenger mer spacing på topp og bunn enn en ordinær situasjon gjør, i håp om at det blir mer forklarende i fremtiden. 

chore(): create separate component for combined situations

---

tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/TransportPaletteSelect.tsx

Default tema på en tavle er mørk, og da vil vi at dette skal reflekteres i transportfargeforhåndsvisningen også. 
Ved opprettelse av en helt fersk tavle: 
| <img width="1334" height="1266" alt="image" src="https://github.com/user-attachments/assets/0779e0fb-2b27-4109-bcd9-fd4f4b2e247e" /> | <img width="1334" height="1266" alt="image" src="https://github.com/user-attachments/assets/5c21132c-e329-40e1-8c1e-952cc1f431a8" /> |

fix(rediger): make dark bg default for transport settings

---

tavla/app/globals.css
tavla/src/Board/scenarios/Table/components/Deviation.tsx
tavla/src/Board/scenarios/Table/components/Line/index.tsx
tavla/src/Board/scenarios/Table/components/TableColumn/index.tsx
tavla/src/Board/scenarios/Table/index.tsx
tavla/src/Shared/components/TravelTag/index.tsx
tavla/tailwind.config.ts

Dette er en oppgave som er en del av arbeidet med å forbedre avviksinformasjon i Tavla. Denne PRen implementerer ny visning av en avviks-kolonne helt til venstre i Tavla som skal vise om en avgang er innstilt, eller om den har et avvik. Den endrer også designet på TravelTag dersom en avgang er innstilt til det nye designet. 
| <img width="1678" height="1252" alt="image" src="https://github.com/user-attachments/assets/6fa592b8-9624-40ce-9575-0d4f4f9e17e4" /> | <img width="1678" height="1252" alt="image" src="https://github.com/user-attachments/assets/81206d53-e5b9-4eeb-988e-971f4431916a" /> |
|<img width="1678" height="1252" alt="image" src="https://github.com/user-attachments/assets/45cd1fa4-4b44-40ad-b28d-9d6a5477444b" />|<img width="1678" …

feat(tavla): implement new cancelled call design

---

tavla/.prettierrc.js

Tailwindcss prettier slutta å funke tydeligvis etter import organizer prettier pluginen ble lagt til.

fix(): update tailwindcss prettier config

---

tavla/src/Board/scenarios/Table/components/Destination.tsx
tavla/src/Board/scenarios/Table/components/Deviation.tsx
tavla/src/Board/scenarios/Table/components/Line/index.tsx
tavla/src/Board/scenarios/Table/components/Platform.tsx
tavla/src/Board/scenarios/Table/components/TableCell/index.tsx
tavla/src/Board/scenarios/Table/components/Time/AimedTime.tsx
tavla/src/Board/scenarios/Table/components/Time/ArrivalTime.tsx
tavla/src/Board/scenarios/Table/components/Time/ExpectedTime.tsx

TableRow er feilaktig kalt det da det er en celle egentlig. 

chore(): rename TableRow to TableCell

---

tavla/app/(admin)/tavler/[id]/rediger/components/TileCard/ColumnModal.tsx
tavla/src/Shared/types/column.ts

Ulik rekkefølge på kolonner-elementer og det som vises i forhåndsvisningen. Det bør være 1:1, sånn at vi forventningsstyrer brukeren. 
| <img width="884" height="424" alt="image" src="https://github.com/user-attachments/assets/15f437eb-9da9-492d-ae7f-ad36a2adcf9b" /> | <img width="884" height="424" alt="image" src="https://github.com/user-attachments/assets/c9e33467-b00e-486d-8e63-ecc3b7a03e8d" /> |

chore(rediger): synchronize edit columns with columns in tavle

---

tavla/app/(admin)/hooks/useQuaySearch.ts

I noen tilfeller om man legger inn et stoppested og ønsker å velge flere plattformer så hopper plattformene rundt, noe som blir synlig ved at neste gang man vil legge til en plattform så er det endringer i fremkomstmidlene som er tilgjengelige. Dette skjer kun når plattformen ikke har publicCode eller description. Tallet som vises da er indexen i map som brukes for å gå gjennom alle plattformene som tilhører et stoppested. 
Ett eksempel på dette er Brensholmen ferjekai, hvor en av plattformene er en ferjekai og de to andre er buss, her har ferjen ID "NSR:Quay:96171" mens bussene har ID "NSR:Quay:110819" og "NSR:Quay:110820". 
| | |
|-|-|
|<img width="1024" height="488" alt="image" src="https://github.com/user-attachments/assets/b7c306ca-2e31-4d51-9a6f-e2c5b20aba30" />|<img width="1024" …

fix(rediger): sort quays on id

---

tavla/app/(admin)/components/Login/index.tsx
tavla/app/(admin)/components/MobileNavbar.tsx
tavla/app/(admin)/components/Navbar.tsx

Navbaren på mobil skalerer dårlig, logoen blir veldig liten og knappene tar større plass enn de trenger. 
- For ikke-innlogget bruker: 
- Menyen vises nå for ikke-innloggede brukere (før bare synlig for innlogget)
- "Ofte stilte spørsmål" og "Test ut tavla" er begge flyttet fra navbaren og inn i menyen på mobilvisning
- For innlogget bruker: 
- "Mine tavler" er flyttet inn i menyen
`gap` og størrelse på knapper som vises i mobil navbar er justert slik at de bedre skal skalere på små mobiler. 
| <img width="384" height="676" alt="image" src="https://github.com/user-attachments/assets/26b5756c-4636-4314-bd1b-ab9590f8ff44" /> | <img width="382" height="670" alt="image" src="https://github.com/user-attachments/assets/560a9458-0c09-4c6f-82ff-94583eecee79" /> …

fix(navbar): add navbar responsiveness for mobile

---

tavla/app/(admin)/components/Navbar.tsx

Ved hover på "Test ut Tavla" i navbaren når en bruker er logget ut kommer den rødoransje linjen til høyre for teksten, i stedet for under. Vi vil at den skal være under. 
- Endret fra `flex:col` til `flex-col` :))
| <img width="575" height="109" alt="image" src="https://github.com/user-attachments/assets/9d045afd-80cf-4f68-81c9-f6a9b8a87b28" /> | <img width="591" height="99" alt="image" src="https://github.com/user-attachments/assets/139ac7de-b338-4e0d-9113-8a6dc68dc28c" /> |

fix(landing): fix navbar hover highlight

---

tavla/app/(admin)/tavler/[id]/rediger/components/Settings/actions.ts
tavla/app/(admin)/tavler/[id]/utils.ts

Etter #1986 så dukker det opp en feilmelding når man kommer fra /oversikt eller /mapper/[id] til /rediger, denne dukker ikke opp hvis man refresher /rediger. 
Viser seg at title ikke er satt i formData når /rediger-endepunktet kalles første gang - derfor trigges en feilmelding. På sikt burde man se på hele flyten ved endringer her - men for å fikse uten større omskrivning så er det gjort en enkel fiks.

fix(rediger): avoid error message that occurs when opening admin for a Tavle

---

tavla/src/Shared/components/TravelTag/index.tsx

Flytog og flybuss har ikke lilla slik som i appen, bruker sine standard farger for tog og buss. 
| <img width="1448" height="810" alt="Screenshot 2025-08-26 at 13 20 26" src="https://github.com/user-attachments/assets/ac83c293-cf59-4c5b-8498-19d9f08961fd" />  | <img width="1449" height="537" alt="Screenshot 2025-08-26 at 13 21 00" src="https://github.com/user-attachments/assets/13812449-45b4-4268-9db8-f08db83fef49" /> |

chore(): airport colors

---

tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/TransportPaletteSelect.tsx
tavla/app/(admin)/tavler/[id]/rediger/components/Settings/components/WalkingDistance.tsx
tavla/app/(admin)/tavler/[id]/rediger/components/Settings/index.tsx

"Instillinger" har blitt veldig "høyre-tung" særlig med alle buss-farge-valgene. Så på noen småendringer for å forbedre litt
|<img width="1258" height="1527" alt="image" src="https://github.com/user-attachments/assets/961f656d-e9cb-4a98-b743-c45c3a9c35c0" />| <img width="1258" height="1527" alt="image" src="https://github.com/user-attachments/assets/4df7c375-79f2-4010-8c57-190628e4ac61" />|

feat(rediger): make styling improvements to Instillinger on admin page

---

tavla/src/Board/scenarios/CombinedTile/index.tsx
tavla/src/Board/scenarios/QuayTile/index.tsx
tavla/src/Board/scenarios/StopPlaceTile/index.tsx

Avviksmeldinger havner midt på skjermen ved få avganger, skal ligge i bunn
| <img width="1832" height="1527" alt="image" src="https://github.com/user-attachments/assets/421dac1c-f796-4a2d-980c-26d9e5a01f2d" />|<img width="1832" height="1527" alt="image" src="https://github.com/user-attachments/assets/27bd8f79-83b7-4a73-84f8-1aae8d5a9eb0" />|

fix(tavla): move tile situations to bottom if few departures

---

tavla/app/globals.css

Tidligere grønn farge for busser er for blasst.
| <img width="655" height="485" alt="Screenshot 2025-09-09 at 13 36 57" src="https://github.com/user-attachments/assets/c4af90dc-1d92-46b2-90b9-06226778fa40" /> | <img width="777" height="562" alt="Screenshot 2025-09-09 at 13 35 48" src="https://github.com/user-attachments/assets/bfee44fc-85f0-4a5e-80f3-aeecff17e987" /> |

fix(): change from dark-mobility to contrast-mobility

---

tavla/app/(admin)/components/Login/Create.tsx
tavla/app/(admin)/components/Login/Email.tsx
tavla/app/(admin)/utils/index.ts

---
Det er irriterende for brukeren å fylle inn alt på nytt dersom de skriver inn en liten ting feil, dette skal hjelpe. 
Lagt inn state som passer på epost dersom aktiviteten (innlogging eller opprettelse av ny konto) feiler.
|Før|Etter|
|-----|------|
|<img width="460" height="763" alt="image" src="https://github.com/user-attachments/assets/d68775ce-9584-4006-9531-4ec190d54721" />|<img width="460" height="763" alt="image" src="https://github.com/user-attachments/assets/9c1ebfb4-3690-480e-93f7-f36cefdde07a" />|
|<img width="460" height="763" alt="image" src="https://github.com/user-attachments/assets/c7128155-f0c2-467d-99b1-aa6b8bf1348b" />|<img width="460" height="763" alt="image" src="https://github.com/user-attachments/assets/b2975eb9-2c13-4ada-ba40-0e2cd8653dbb" />|
|<img width="460" …

fix(landing): input email stays in case of error

---

tavla/app/(admin)/components/CreateFolder/index.tsx

Når en bruker trykker på "avbryt" på "Opprett mappe" på oversiktssiden eller trykker utenfor modalen lukkes den ikke, det er uheldig, men ikke kjempekritisk fordi man kan trykke seg ut ved "X". 
- `onClick={close}` => `onClick={() => setIsOpen(false)}`
| <img width="570" height="656" alt="image" src="https://github.com/user-attachments/assets/fced2413-e124-43c2-a664-f4c7494e4592" /> | <img width="963" height="661" alt="image" src="https://github.com/user-attachments/assets/4dedb5ac-f77e-4f0b-a587-2ba5a25a71c3" /> |

:bug: fiks mappelukking ved 'avbryt'

---

tavla/src/Shared/components/TravelTag/index.tsx

Flytransportfargene blir ikke gjennomsiktig lilla når f.eks flytoget er innstilt. 
- `transportMode` --> `colorMode`
| <img width="1481" height="898" alt="image" src="https://github.com/user-attachments/assets/2de56575-b64a-49ad-ad55-33bacb2bf575" /> | <img width="1479" height="895" alt="image" src="https://github.com/user-attachments/assets/e9422233-8eff-4035-8957-c8177e65a940" /> |

:lipstick: fiks gjennomsiktig farge for flytransport

---

tavla/next.config.js

SSO innlogging via Google sluttet å funke da vi merget inn #1922 siden vi gjorde endringer i CSPen som gjorde den strengere. Ved å legge til Firebase i frame-src tillater vi iFrame med opprinnelse fra Firebase.
- Leg til https://ent-tavla-dev.firebaseapp.com/ i frame-src 'self' i next.config.js

🐛 legg til firebase i frame sikkerhetsheader

---

tavla/src/Board/scenarios/Table/useCycler.ts

Vi opplevde at innimellom vistes ikke avviksmeldingen på bunnen av en tile, selv om det fantes avvik på en eller flere av avgangene. Var ikke tydelig hva som forårsaket det. 
Etter litt detektivarbeid fant jeg ut at dette skjer når lista med avvik blir kortere (fordi avgangene endres, finnes ikke lenger like mange avvik) og index-en blir "out of bounds". Feks vises avvik 4/4, men så hentes nye avganger og det finnes bare 3 avviksmeldinger. 
-  Har lagt på en til `useEffect` som kjører dersom length eller index endrer seg, den setter index til 0 dersom index er større eller lik lengten på lista (out of bounds) 
Bildet viser et eksempel der feilen oppstod hvor index for Majorstua var `1`, men lengden på lista var `1` og dermed var index 1 out of bounds

🐛 Reset index for cycler if length of array changes and current index is out of bounds
